import React,{useState,useEffect,useRef} from 'react';
import {mobileCopy,mobileRoute,mobileSource,mobileChecked,type MobileAccess,type AppNumber} from '../lib/aadhaar-mobile';
import {createSpeechSession,type SpeechSession} from '../lib/speech-client';
import type {DirectoryLanguage} from '../lib/service-directory';
export default function AadhaarMobileHelp({language,stopOtherAudio}:{language:DirectoryLanguage;stopOtherAudio:()=>void}){
 const c=mobileCopy[language], [access,setAccess]=useState<MobileAccess>('unknown'),[app,setApp]=useState<AppNumber>('unknown'),[error,setError]=useState('');const speech=useRef<SpeechSession|null>(null);
 useEffect(()=>{speech.current=createSpeechSession(()=>{},{en:'en-IN',hi:'hi-IN',te:'te-IN'}[language]);const stop=()=>{if(document.hidden)speech.current?.stop()};document.addEventListener('visibilitychange',stop);return()=>{speech.current?.stop();document.removeEventListener('visibilitychange',stop)}},[language]);
 const route=mobileRoute(access,app);
 return <details className="aadhaar-mobile-help"><summary>{c.title}</summary><fieldset><legend>{c.access}</legend><div className="prep-options">{(['yes','no','first','unknown'] as const).map((v,i)=><button type="button" key={v} aria-pressed={access===v} onClick={()=>{speech.current?.stop();setAccess(v);setApp('unknown');setError('')}}>{c.choices[i]}</button>)}</div></fieldset>{access==='yes'&&<fieldset><legend>{c.app}</legend><div className="prep-options">{(['same','different','unknown'] as const).map((v,i)=><button type="button" key={v} aria-pressed={app===v} onClick={()=>{speech.current?.stop();setApp(v);setError('')}}>{c.appChoices[i]}</button>)}</div></fieldset>}<p className="prep-next" role="status">{c[route]}</p><p>{c.note}</p><small>{c.reviewLabel}: {mobileChecked} · UIDAI</small><div className="row"><a href={mobileSource} target="_blank" rel="noreferrer">{c.source} ↗</a><button type="button" onClick={async()=>{stopOtherAudio();try{setError('');await speech.current?.speak(c[route],.9)}catch{setError(c.audio)}}}>{c.listen}</button><button type="button" onClick={()=>speech.current?.stop()}>{c.stop}</button></div>{error&&<p role="alert">{error}</p>}</details>
}
