import React,{useEffect,useRef,useState} from 'react';
import {regions} from '../lib/regions';
import {makeCase,casePack,followupCalendar,farmChoices,farmLabels,caseReviewed,caseReviewDue,caseSources,rulesCurrent,type CaseInput,type CasePlan} from '../lib/action-cases';
import {createSpeechSession,type SpeechSession} from '../lib/speech-client';
import type {DirectoryLanguage} from '../lib/service-directory';
import './action-case.css';
const intro={en:['Action assistant','Prepare a useful result, then take it to the official service.'],hi:['कार्रवाई सहायक','काम का मसौदा तैयार करें, फिर आधिकारिक सेवा पर ले जाएँ।'],te:['పని సహాయకుడు','ఉపయోగకరమైన ముసాయిదా తయారు చేసి అధికారిక సేవకు తీసుకెళ్లండి.']};
export default function ActionCase({kind,language,offline,children}:{kind:'farm'|'grievance';language:DirectoryLanguage;offline:boolean;children?:React.ReactNode}){
 const [input,setInput]=useState<CaseInput>({kind,region:'',issue:kind==='farm'?'unknown':'delay',summary:'',remedy:''}),[plan,setPlan]=useState<CasePlan|null>(null),[reviewed,setReviewed]=useState(false),[error,setError]=useState(''),[date,setDate]=useState(''),[notice,setNotice]=useState(''),[outcome,setOutcome]=useState('prepared'),[other,setOther]=useState(false),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[current,setCurrent]=useState(()=>rulesCurrent());
 const speech=useRef<SpeechSession|null>(null),result=useRef<HTMLElement|null>(null);
 useEffect(()=>{speech.current=createSpeechSession(p=>setBusy(p!=='ready'), 'en-IN');const stop=()=>{if(document.hidden)speech.current?.stop()};document.addEventListener('visibilitychange',stop);const timer=setInterval(()=>setCurrent(rulesCurrent()),30000);return()=>{clearInterval(timer);speech.current?.stop();document.removeEventListener('visibilitychange',stop)}},[]);
 useEffect(()=>{speech.current?.stop();setReviewed(false)},[language]);
 function change(key:keyof CaseInput,value:string){speech.current?.stop();setInput(old=>({...old,[key]:value}));setPlan(null);setReviewed(false);setOutcome('prepared');setError('');setNotice('')}
 function build(){try{setPlan(makeCase(input));setReviewed(false);setError('');setNotice('');setTimeout(()=>result.current?.focus(),0)}catch(e){setError((e as Error).message)}}
 function save(text:string,name:string,type:string){try{const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);setNotice(name.endsWith('.ics')?'Calendar file prepared. Open it in your calendar and choose its reminder settings; delivery is not confirmed.':'Action-pack download requested. Check Downloads. It contains your draft; keep it private on shared devices.')}catch{setError('Download failed. Select and copy the visible draft instead.')}}
 function download(calendar=false){try{if(!plan||!reviewed||!rulesCurrent()||plan.blocked)throw Error('Review the current draft first.');save(calendar?followupCalendar(date):casePack(plan),calendar?'saathi-follow-up.ics':'saathi-action-pack.txt',calendar?'text/calendar;charset=utf-8':'text/plain;charset=utf-8')}catch(e){setError((e as Error).message)}}
 async function speak(text:string){try{await speech.current?.speak(text,.9)}catch{setError('Voice is unavailable. Read or use the buttons instead.')}}
 async function dictate(){if(!consent||busy)return;try{const text=await speech.current!.listen();change('summary',text)}catch{setError('Voice input is unavailable. Type a short description instead.')}}
 const excluded=kind==='grievance'&&input.issue==='excluded';
 return <section className="case-agent" aria-label="Action assistant">
 <header><p className="case-kicker">{intro[language][0]} · Guided workflow</p><h2>{kind==='farm'?'Resolve a missing PM-KISAN payment':'Prepare a government-service complaint'}</h2><p>{intro[language][1]}</p><p className="case-scope">Rules-based preparation, draft and calendar tools. No AI model, live account access or automatic submission is connected.</p>{language!=='en'&&<p role="status">This new workflow and speech are currently in English. Hindi/Telugu versions need review; the existing translated guidance is under “Other service guidance”.</p>}</header>
 <div className="case-steps" aria-label="Workflow stages"><span>1 · Describe</span><span>2 · Review result</span><span>3 · Use & follow up</span></div>
 <p>Do not enter Aadhaar, account, phone or registration numbers, OTPs, names or addresses. Nothing entered here is sent to a model or saved on this site. Reloading clears this case; an exported file may remain on your device.</p>
 {!current&&<p role="alert">This guidance needs a source review. New drafts and downloads are paused. Read the official guidance directly.</p>}
 <label>State or Union Territory<select value={input.region} onChange={e=>change('region',e.target.value)}><option value="">Choose your region</option>{regions.map(r=><option key={r}>{r}</option>)}</select></label>
 {kind==='farm'?<fieldset><legend>What did the official status show?</legend><div className="case-options">{farmChoices.map(x=><button key={x} type="button" aria-pressed={input.issue===x} onClick={()=>change('issue',x)}>{farmLabels[x]}</button>)}</div>{!offline&&<a href={caseSources.status} target="_blank" rel="noopener noreferrer">Check Know Your Status securely ↗</a>}<p>Your selection is self-reported, not verified by Saathi. Do not guess.</p></fieldset>:<label>What kind of problem?<select value={input.issue} onChange={e=>change('issue',e.target.value)}><option value="delay">Government service delayed</option><option value="incorrect">Incorrect government record or response</option><option value="unavailable">Government service not provided</option><option value="excluded">RTI, court case or personal/family dispute</option></select></label>}
 {excluded?<div role="status"><h3>This complaint route is not appropriate</h3><p>CPGRAMS excludes RTI, court/subjudice matters and personal/family disputes. Use the relevant official or qualified adviser’s route. This assistant will not prepare a CPGRAMS draft for that category.</p></div>:<>
 <label>{kind==='farm'?'Anything else? Optional, without private identifiers.':'What happened? Name the service, approximate dates, earlier action and what remains unresolved.'}<textarea value={input.summary} maxLength={1200} rows={4} onChange={e=>change('summary',e.target.value)} placeholder={kind==='farm'?'Optional additional facts':'Example: My residence-certificate request is pending. I asked the issuing office for an update but have not received a reason for the delay.'}/></label>
 <details><summary>Speak the description instead</summary><label><input type="checkbox" checked={consent} onChange={e=>{setConsent(e.target.checked);if(!e.target.checked)speech.current?.stop()}}/> I allow browser/device speech processing, which may send audio online. I will not speak private identifiers.</label><button disabled={!consent||busy} onClick={()=>void dictate()}>Speak in English</button></details>
 {kind==='grievance'&&<label>What specific resolution are you requesting?<textarea value={input.remedy} maxLength={1200} rows={3} onChange={e=>change('remedy',e.target.value)} placeholder="Explain the pending step and tell me which correction or evidence is needed."/></label>}
 <button className="case-primary" disabled={!current} onClick={build}>Prepare my action pack</button></>}
 {error&&<p role="alert">{error}</p>}
 {plan&&!plan.blocked&&current&&<section ref={result} tabIndex={-1} className="case-result" aria-label="Your prepared action pack"><p className="case-kicker">Prepared · Not submitted</p><h3>{plan.title}</h3><h4>Do this next</h4><p>{plan.next}</p><details><summary>Why this action?</summary><p>{plan.why}</p></details><h4>Keep this evidence privately</h4><ul>{plan.evidence.map(x=><li key={x}>{x}</li>)}</ul><h4>Your draft</h4><p>Only your selected status and supplied facts are included. Correct them above if anything is inaccurate; changing an answer cancels this review.</p><pre>{plan.draft}</pre><button disabled={busy} onClick={()=>void speak(plan.next+'. '+plan.draft)}>Listen to next step and draft in English</button><label className="case-review"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/> I have reviewed this draft. It accurately reflects what I know; it is not an official decision.</label><div className="case-actions"><button disabled={!reviewed} onClick={()=>download()}>Download action pack</button>{reviewed&&!offline?<a className="case-primary" href={plan.route} target="_blank" rel="noopener noreferrer">Continue on official service ↗</a>:<button disabled>Review draft / reconnect before official handoff</button>}</div><p>You sign in and submit on the official service. Keep its acknowledgement there; do not paste it here.</p><h4>Follow up</h4><p>{plan.followup}</p><label>Your own follow-up date—not a government deadline<input type="date" value={date} onChange={e=>{setDate(e.target.value);setNotice('')}}/></label><button disabled={!reviewed||!date} onClick={()=>download(true)}>Download calendar follow-up</button><p>No email, push alert or background status check is scheduled by this page.</p><label>What happened next? Your report only<select value={outcome} onChange={e=>setOutcome(e.target.value)}><option value="prepared">I have only prepared the pack</option><option value="submitted">I completed the official step myself</option><option value="waiting">I am waiting for an official response</option><option value="resolved">I consider the issue resolved</option></select></label><p role="status">{outcome==='prepared'?'No external action reported.':'Recorded in this session only. Saathi has not verified this outcome.'}</p><details><summary>What the assistant did</summary><ol>{plan.trace.map(x=><li key={x}>{x}</li>)}</ol></details></section>}
 {notice&&<p role="status">{notice}</p>}
 <footer><p>National guidance · Reviewed {caseReviewed} · Review due {caseReviewDue.slice(0,10)}. State/UT implementation and the individual outcome require official confirmation.</p>{!offline?<a href={kind==='farm'?caseSources.pib:caseSources.faq} target="_blank" rel="noopener noreferrer">Read the official source ↗</a>:<p>Offline: official links are unavailable. Your cached guidance may be outdated.</p>}<button onClick={()=>{speech.current?.stop();setInput({kind,region:'',issue:kind==='farm'?'unknown':'delay',summary:'',remedy:''});setPlan(null);setReviewed(false);setConsent(false);setDate('');setOutcome('prepared');setNotice('');setError('')}}>Clear this case</button>{busy&&<button onClick={()=>speech.current?.stop()}>Stop voice</button>}</footer>
 <button onClick={()=>setOther(!other)} aria-expanded={other}>Other service guidance</button>{other&&children}
 </section>
}
