import React,{useEffect,useState} from 'react';
import {Bell,ArrowRight} from 'lucide-react';
import type {DirectoryLanguage} from '../lib/service-directory';
import './alert-preview.css';
const labels={en:['Research alerts','Sources, risks and a useful next step','Open alert centre','Checking published alerts…','Updates unavailable. Open the alert centre to retry.','No current reviewed alerts.','Details in English · public email subscriptions and phone push unavailable'],hi:['शोध सूचनाएँ','स्रोत, जोखिम और अगला कदम','सूचना केन्द्र खोलें','सूचनाएँ देख रहे हैं…','सूचनाएँ उपलब्ध नहीं। केन्द्र खोलकर फिर कोशिश करें।','अभी कोई ताज़ा सूचना नहीं।','विवरण अंग्रेज़ी में · सार्वजनिक ईमेल सदस्यता और फ़ोन पुश उपलब्ध नहीं हैं'],te:['పరిశోధన అలర్ట్‌లు','మూలాలు, ప్రమాదాలు, తదుపరి చర్య','అలర్ట్ కేంద్రం తెరవండి','అలర్ట్‌లు చూస్తున్నాం…','అలర్ట్‌లు అందుబాటులో లేవు. కేంద్రంలో మళ్లీ ప్రయత్నించండి.','ప్రస్తుతం తాజా అలర్ట్‌లు లేవు.','వివరాలు ఆంగ్లంలో · పబ్లిక్ ఇమెయిల్ చందా, ఫోన్ పుష్ అందుబాటులో లేవు']};
export default function AlertPreview({language}:{language:DirectoryLanguage}){
 const c=labels[language], [state,setState]=useState<{phase:'loading'|'ready'|'error';title?:string;count?:number}>({phase:'loading'});
 useEffect(()=>{let active=true;let controller:AbortController|undefined;let busy=false;
  async function refresh(){if(document.hidden||busy)return;if(!navigator.onLine){if(active)setState({phase:'error'});return}busy=true;controller=new AbortController();const timer=setTimeout(()=>controller?.abort(),8000);try{const r=await fetch('/ruralos/alerts/feed.json',{cache:'no-store',signal:controller.signal});if(!r.ok)throw Error();const data=await r.json();if(!Array.isArray(data.alerts))throw Error();const current=data.alerts.filter((a:any)=>a&&['Research lead','Fare snapshot'].includes(a.status)&&typeof a.title==='string'&&Date.parse(a.reviewBy)>Date.now());if(active)setState({phase:'ready',title:current[0]?.title,count:current.length})}catch{if(active)setState({phase:'error'})}finally{clearTimeout(timer);busy=false}}
  void refresh();const interval=setInterval(()=>void refresh(),60000);const resume=()=>void refresh();document.addEventListener('visibilitychange',resume);window.addEventListener('online',resume);return()=>{active=false;controller?.abort();clearInterval(interval);document.removeEventListener('visibilitychange',resume);window.removeEventListener('online',resume)};
 },[]);
 return <section className="saathi-alert-preview" aria-label={c[0]}><div><p className="directory-eyebrow"><Bell size={17}/>{c[0]}{state.count?` · ${state.count}`:''}</p><h2>{state.phase==='ready'&&state.title?<span lang="en">{state.title}</span>:c[1]}</h2><p role="status">{state.phase==='loading'?c[3]:state.phase==='error'?c[4]:state.count?'':c[5]}</p><small>{c[6]}</small></div><a className="directory-listen" href="/ruralos/alerts/">{c[2]}<ArrowRight size={18}/></a></section>
}
