import React,{useEffect,useState} from 'react';
import {L,goals,forGoal,fresh,reviewed,reviewBy,type Lang} from '../lib/enterprise';
import './enterprise-guide.css';
import {companionLink} from '../lib/home-experience';
export const enterpriseCopy={
 title:L('Start with the right kind of support','सही तरह की सहायता से शुरुआत करें','సరైన సహాయంతో ప్రారంభించండి'),
 intro:L('Central-government programmes for India. Choose your purpose; these are routes to investigate, not an eligibility decision or a loan offer.','भारत की केंद्र सरकार के कार्यक्रम। अपना उद्देश्य चुनें; ये जाँचने के रास्ते हैं, पात्रता का निर्णय या ऋण प्रस्ताव नहीं।','భారత కేంద్ర ప్రభుత్వ కార్యక్రమాలు. మీ ఉద్దేశం ఎంచుకోండి; ఇవి పరిశీలించే మార్గాలు, అర్హత నిర్ణయం లేదా రుణ ఆఫర్ కాదు.'),
 all:L('See all 7 programmes','सभी 7 कार्यक्रम देखें','మొత్తం 7 కార్యక్రమాలు చూడండి'),
 fit:L('Who should explore this?','किसके लिए उपयोगी हो सकता है?','ఎవరు పరిశీలించవచ్చు?'),
 next:L('Your first action','आपका पहला कदम','మీ మొదటి అడుగు'),
 caution:L('Before you commit','निर्णय लेने से पहले','నిర్ణయం ముందు'),
 open:L('Open official programme','आधिकारिक कार्यक्रम खोलें','అధికారిక కార్యక్రమం తెరవండి'),
 evidence:L('Source and review date','स्रोत और समीक्षा तारीख','మూలం, సమీక్ష తేదీ'),
 listen:L('Listen to this programme','इस कार्यक्रम को सुनें','ఈ కార్యక్రమం వినండి'),
 stop:L('Stop audio','आवाज़ रोकें','ఆడియో ఆపండి'),
 stale:L('Source review is due. Old amounts and programme details are hidden. Check the official programme for current rules.','स्रोत की समीक्षा बाकी है। पुरानी राशि और विवरण छिपाए गए हैं। वर्तमान नियम आधिकारिक कार्यक्रम पर देखें।','మూలం సమీక్ష అవసరం. పాత మొత్తాలు, వివరాలు దాచబడ్డాయి. ప్రస్తుత నియమాలు అధికారిక కార్యక్రమంలో చూడండి.'),
 offline:L('Offline: saved guidance may be outdated. Reconnect before opening official services.','ऑफ़लाइन: सहेजी जानकारी पुरानी हो सकती है। आधिकारिक सेवा के लिए दोबारा जुड़ें।','ఆఫ్‌లైన్: సేవ్ చేసిన సమాచారం పాతది కావచ్చు. అధికారిక సేవల కోసం మళ్లీ కనెక్ట్ అవ్వండి.'),
 prepare:L('Before a bank or office visit','बैंक या कार्यालय जाने से पहले','బ్యాంకు లేదా కార్యాలయానికి వెళ్లే ముందు'),
 help:L('Application stuck? Keep the acknowledgement, ask for the exact missing item or written reason, then use the lender or department’s official grievance channel. A second application may not fix the first one.','आवेदन रुका है? पावती रखें, अधूरी चीज़ या लिखित कारण पूछें, फिर बैंक/विभाग की आधिकारिक शिकायत सेवा लें। दूसरा आवेदन पहले की समस्या नहीं सुलझाता।','దరఖాస్తు ఆగిందా? రసీదు ఉంచండి, మిగిలిన అంశం లేదా రాతపూర్వక కారణం అడగండి; తరువాత బ్యాంకు/శాఖ అధికారిక ఫిర్యాదు మార్గం వాడండి. రెండో దరఖాస్తు మొదటిదాన్ని పరిష్కరించకపోవచ్చు.'),
 privacy:L('Checklist stays in this page session only. No identity documents, account details, OTPs or applications are collected. Hindi/Telugu are review previews.','जाँच सूची केवल इस पेज के सत्र में रहती है। पहचान दस्तावेज़, खाता, OTP या आवेदन नहीं लिए जाते। हिन्दी/तेलुगु समीक्षा पूर्वावलोकन हैं।','జాబితా ఈ పేజీ సెషన్‌లో మాత్రమే ఉంటుంది. గుర్తింపు పత్రాలు, ఖాతా వివరాలు, OTPలు లేదా దరఖాస్తులు సేకరించము. హిందీ/తెలుగు సమీక్ష ముందస్తు రూపాలు.'),
};
export const preparation=[
 L('One-page plan: product/service, customers, location and how you will sell.','एक पन्ने की योजना: उत्पाद/सेवा, ग्राहक, स्थान और बेचने का तरीका।','ఒక పేజీ ప్రణాళిక: ఉత్పత్తి/సేవ, కస్టమర్లు, స్థలం, అమ్మే విధానం.'),
 L('Separate equipment costs, working capital, own savings and the amount requested; collect quotations.','मशीन लागत, कामकाजी पूँजी, अपनी बचत और माँगी राशि अलग लिखें; भाव-पत्र लें।','పరికరాల ఖర్చు, నిర్వహణ మూలధనం, సొంత పొదుపు, కోరే మొత్తం వేరుగా రాసి ధరల పత్రాలు పొందండి.'),
 L('Estimate monthly sales and expenses conservatively; check whether repayments still fit in a weak month.','मासिक बिक्री और खर्च सावधानी से आँकें; कम बिक्री के महीने में भी भुगतान संभव है या नहीं देखें।','నెలవారీ అమ్మకాలు, ఖర్చులను జాగ్రత్తగా అంచనా వేయండి; అమ్మకాలు తగ్గిన నెలలోనూ వాయిదా చెల్లించగలరా చూడండి.'),
 L('Ask for the exact document list, annual interest/APR where applicable, all fees, EMI, total repayment and collateral in writing.','पूरी दस्तावेज़ सूची, वार्षिक ब्याज/लागू APR, सभी शुल्क, EMI, कुल भुगतान और जमानत लिखित में लें।','పూర్తి పత్రాల జాబితా, వార్షిక వడ్డీ/వర్తించే APR, అన్ని రుసుములు, EMI, మొత్తం చెల్లింపు, తాకట్టు రాతపూర్వకంగా అడగండి.'),
 L('Confirm current intake, relevant licences and business registration. Never share a banking PIN or OTP with an agent.','वर्तमान आवेदन, जरूरी लाइसेंस और व्यवसाय पंजीकरण पक्के करें। बैंक PIN या OTP एजेंट को न दें।','ప్రస్తుత దరఖాస్తుల స్వీకరణ, అవసరమైన లైసెన్సులు, వ్యాపార నమోదు నిర్ధారించండి. బ్యాంకు PIN లేదా OTP ఏజెంట్‌కు ఇవ్వవద్దు.')
];
export function ProgrammeCards({language,goal='all',offline=false,now=Date.now(),onSpeak=()=>{},onStop=()=>{}}:{language:Lang;goal?:string;offline?:boolean;now?:number;onSpeak?:(s:string)=>void;onStop?:()=>void}){
 const c=enterpriseCopy,current=fresh(now);
 return <div className="enterprise-cards">{forGoal(goal).map(p=><article key={p.id} id={'programme-'+p.id}><span className="enterprise-type">{p.type[language]}</span><h3>{p.name}</h3>{current?<><p>{p.benefit[language]}</p><h4>{c.fit[language]}</h4><p>{p.fit[language]}</p><div className="enterprise-next"><h4>{c.next[language]}</h4><p>{p.next[language]}</p></div><h4>{c.caution[language]}</h4><p>{p.caution[language]}</p><button onClick={()=>onSpeak([p.name,p.type[language],p.benefit[language],p.fit[language],p.next[language],p.caution[language]].join('. '))}>{c.listen[language]}</button><button onClick={onStop}>{c.stop[language]}</button></>:<p role="status">{c.stale[language]}</p>}{!offline&&<a href={p.url} target="_blank" rel="noopener noreferrer">{c.open[language]} ↗</a>}<details><summary>{c.evidence[language]}</summary><p>{p.source} · {["Reviewed","समीक्षा","సమీక్ష"][language==='en'?0:language==='hi'?1:2]}: {reviewed} UTC · {["Review due","अगली समीक्षा","తదుపరి సమీక్ష"][language==='en'?0:language==='hi'?1:2]}: {reviewBy.slice(0,10)} UTC</p>{!offline&&<a href={p.evidence??p.url} target="_blank" rel="noopener noreferrer">{p.source} ↗</a>}</details></article>)}</div>
}
export default function EnterpriseGuide({language,offline,onSpeak,onStop}:{language:Lang;offline:boolean;onSpeak:(s:string)=>void;onStop:()=>void}){
 const[goal,setGoal]=useState('all'),[now,setNow]=useState(Date.now),[checks,setChecks]=useState<number[]>([]);
 useEffect(()=>{const refresh=()=>setNow(Date.now());const timer=setInterval(refresh,60000);document.addEventListener('visibilitychange',refresh);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',refresh);onStop()}},[]);
 const c=enterpriseCopy;return <section className="enterprise-guide"><p className="directory-eyebrow">India · Central programmes</p><h2>{c.title[language]}</h2><p>{c.intro[language]}</p>{offline&&<p role="status">{c.offline[language]}</p>}<div className="enterprise-filters"><button aria-pressed={goal==='all'} onClick={()=>{onStop();setGoal('all')}}>{c.all[language]}</button>{goals.map(g=><button key={g.id} aria-pressed={goal===g.id} onClick={()=>{onStop();setGoal(g.id)}}>{g.label[language]}</button>)}</div><ProgrammeCards language={language} goal={goal} offline={offline} now={now} onSpeak={onSpeak} onStop={onStop}/><section className="enterprise-preparation"><h2>{c.prepare[language]}</h2><p>{c.privacy[language]}</p>{preparation.map((item,i)=><label key={i}><input type="checkbox" checked={checks.includes(i)} onChange={()=>setChecks(old=>old.includes(i)?old.filter(x=>x!==i):[...old,i])}/>{item[language]}</label>)}<p>{c.help[language]}</p>{!offline&&<p><a href={companionLink("Reminders")}>{L("Save a reminder in family tools","परिवार साधन में याद दिलाना सहेजें","కుటుంబ సాధనాల్లో రిమైండర్ సేవ్ చేయండి")[language]}</a> <a href={companionLink("Help")}>{L("Open help options","सहायता विकल्प खोलें","సహాయ ఎంపికలు తెరవండి")[language]}</a></p>}<button onClick={()=>onSpeak(preparation.map(x=>x[language]).join('. '))}>{c.listen[language]}</button><button onClick={onStop}>{c.stop[language]}</button></section></section>
}
