'use client';
import {useEffect,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Mic,Volume2,Pause,Play} from 'lucide-react';
import {Language,text,locales,regionText} from '@/lib/languages';
import {regionalGuidance} from '@/lib/regional-guidance';
import {Flow,freshFlow,flowPrompt,flowChoices,flowLink,turn} from '@/lib/guided-flow';
import {createSpeechSession,SpeechSession} from '@/lib/speech-client';
import {indiaToday} from '@/lib/voice-engine';
export default function GuidedVoice({open,close,language,region,onRegion,initialService,signedIn,onSave}:{open:boolean;close:()=>void;language:Language;region:string;onRegion:(s:string)=>void;initialService?:string;signedIn:boolean;onSave:(title:string,due:string,id:string)=>Promise<boolean>}){
 const[f,setF]=useState<Flow>(freshFlow(region));const[phase,setPhase]=useState('ready');const[error,setError]=useState(false);const[heard,setHeard]=useState('');const[started,setStarted]=useState(false);const[active,setActive]=useState(false);const[working,setWorking]=useState(false);const[typed,setTyped]=useState('');const current=useRef(f);const speech=useRef<SpeechSession|null>(null);const token=useRef(0);const running=useRef(false);const alive=useRef(true);const saving=useRef(false);const saveId=useRef('');
 const tr=(k:string)=>text(k,language);function update(n:Flow){current.current=n;setF(n);if(n.region!==region)onRegion(n.region)}
 function stop(){token.current++;running.current=false;speech.current?.stop();if(alive.current)setActive(false)}
 useEffect(()=>{alive.current=true;speech.current=createSpeechSession(p=>{if(alive.current)setPhase(p)},locales[language]);const hidden=()=>{if(document.hidden)stop()};document.addEventListener('visibilitychange',hidden);return()=>{alive.current=false;stop();document.removeEventListener('visibilitychange',hidden)}},[language]);
 useEffect(()=>{stop();if(open){const n=initialService?{...freshFlow(region),stage:'confirm' as const,service:initialService}:freshFlow(region);current.current=n;setF(n);setStarted(false);setHeard('');setError(false);saveId.current='';setTyped('')}},[open,initialService]);
 async function cycle(n:Flow,t:number){if(!running.current||t!==token.current)return;try{await speech.current!.speak(flowPrompt(n,language),.83);if(!running.current||t!==token.current)return;if(n.stage==='emergency'||n.paused){stop();return}const reply=await speech.current!.listen();if(t===token.current)await answer(reply,t)}catch(e:any){if(t!==token.current||!alive.current)return;setError(true);stop()}}
 async function answer(raw:string,t:number){if(saving.current||t!==token.current)return;setHeard(raw);setError(false);const result=turn(current.current,raw);update(result.flow);if(result.effect==='stop'){stop();return}if(result.effect==='save'){if(!signedIn){const n={...result.flow,message:'signin' as const};update(n);await speech.current!.speak(flowPrompt(n,language),.83);stop();return}saving.current=true;setWorking(true);saveId.current||=crypto.randomUUID();let ok=false;try{ok=await onSave(result.flow.title!,result.flow.due!,saveId.current)}catch{}finally{saving.current=false;if(alive.current)setWorking(false)}if(t!==token.current||!alive.current)return;const n={...result.flow,stage:ok?'done' as const:'save' as const,message:ok?'saved' as const:'save_error' as const};if(ok)saveId.current='';update(n);await cycle(n,t);return}if(['topic','title'].includes(result.flow.stage))saveId.current='';await cycle(result.flow,t)}
 function begin(listenOnly=false){stop();setStarted(true);setError(false);running.current=true;setActive(true);const t=token.current;const n={...current.current,paused:false};update(n);if(!listenOnly)cycle(n,t);else speech.current!.listen().then(raw=>answer(raw,t)).catch(()=>{if(t===token.current){setError(true);stop()}})}
 function tap(cmd:string){stop();setStarted(true);running.current=true;setActive(true);answer(cmd,token.current).catch(()=>{setError(true);stop()})}
 const link=flowLink(f);
 return <Dialog open={open} onOpenChange={v=>{if(!v){stop();close()}}}><DialogContent className="dialog-body voice-dialog sm:max-w-xl" lang={language}><DialogTitle>{tr('speak')}</DialogTitle><DialogDescription>{tr('consentVoice')}</DialogDescription><div className="voice-session-status" role="status"><span className={'voice-orb '+phase}><Mic size={32}/></span>{tr(phase==='listening'?'listening':phase==='speaking'?'speaking':'voiceOff')}</div><div className="spoken-prompt" aria-live="polite">{flowPrompt(f,language)}</div>{heard&&<p>{tr('heard')}: {heard}</p>}{error&&<p className="error" role="alert">{tr('voiceError')}</p>}{!started?<button className="primary" onClick={()=>begin()}><Play size={22}/>{tr('start')}</button>:<div className="row"><button className="primary" disabled={working} onClick={()=>begin(true)}><Mic size={20}/>{tr('reply')}</button><button className="outline" disabled={working} onClick={()=>begin()}><Volume2 size={20}/>{tr('repeat')}</button><button className="outline" onClick={stop}><Pause size={20}/>{tr('stop')}</button></div>}{started&&<div className="row voice-choices">{flowChoices(f).map(k=><button key={k} className="outline" disabled={working} onClick={()=>tap(k==='home'?'start over':k)}>{tr(k==='reminder'?'reminders':k)}</button>)}</div>}{started&&f.stage==='region'&&<Select value={f.region} onValueChange={v=>tap(v)}><SelectTrigger aria-label={tr('region')} className="w-full min-h-12"><SelectValue/></SelectTrigger><SelectContent>{regionalGuidance.map(r=><SelectItem key={r.name} value={r.name}>{regionText(r.name,language)}</SelectItem>)}</SelectContent></Select>}{started&&['age','date','title'].includes(f.stage)&&<form className="row" onSubmit={e=>{e.preventDefault();tap(typed);setTyped('')}}><label className="field">{tr(f.stage==='age'?'age':f.stage==='date'?'due':'title')}<input required type={f.stage==='date'?'date':f.stage==='age'?'number':'text'} min={f.stage==='date'?indiaToday():f.stage==='age'?0:undefined} max={f.stage==='age'?120:undefined} maxLength={120} value={typed} onChange={e=>setTyped(e.target.value)}/></label><button className="outline" disabled={working}>{tr('next')}</button></form>}{f.stage==='save'&&<p className="source">{tr('reminderNote')}</p>}{!signedIn&&f.message==='signin'&&<a href={'/signin-with-chatgpt?return_to='+encodeURIComponent('/ruralos/?language='+language)} target="_top" className="primary">{tr('signin')}</a>}{link&&<a href={link} target={link.startsWith('tel:')?undefined:'_blank'} rel="noreferrer" onClick={stop} className="primary">{tr(f.stage==='emergency'?'emergency':'source')} ↗</a>}{started&&<button className="text-button" disabled={working} onClick={()=>tap('start over')}>{tr('home')}</button>}</DialogContent></Dialog>
}
