import React,{useRef,useState,useEffect} from 'react';
import {L,type Lang} from '../lib/enterprise';
import './home-video.css';
export const tourLines=[
 L('Choose your language. Speak your problem or tap a service. Microphone access is optional.','अपनी भाषा चुनें। समस्या बोलें या सेवा चुनें। माइक्रोफ़ोन वैकल्पिक है।','మీ భాష ఎంచుకోండి. సమస్య చెప్పండి లేదా సేవ ఎంచుకోండి. మైక్రోఫోన్ ఐచ్ఛికం.'),
 L('Answer only the questions needed for guidance. Review and correct your answers. Never enter an OTP or banking PIN here.','ज़रूरी सवालों के जवाब दें। विवरण जाँचें और सुधारें। यहाँ OTP या बैंक PIN न दें।','అవసరమైన ప్రశ్నలకు జవాబివ్వండి. వివరాలు చూసి సవరించండి. ఇక్కడ OTP లేదా బ్యాంకు PIN ఇవ్వవద్దు.'),
 L('Read or listen to the next step. Check what to prepare, the source, region and review date. Guidance is not approval.','अगला कदम पढ़ें या सुनें। तैयारी, स्रोत, क्षेत्र और समीक्षा तारीख देखें। मार्गदर्शन मंज़ूरी नहीं।','తదుపరి అడుగు చదవండి లేదా వినండి. తయారీ, మూలం, ప్రాంతం, సమీక్ష తేదీ చూడండి. మార్గదర్శనం ఆమోదం కాదు.'),
 L('Continue on the official service when ready. Applications and payments happen there. Keep its acknowledgement. Saathi does not book or submit for you.','तैयार होने पर आधिकारिक सेवा खोलें। आवेदन और भुगतान वहीं होते हैं। पावती रखें। साथी आपकी ओर से बुकिंग या आवेदन नहीं करता।','సిద్ధమైనప్పుడు అధికారిక సేవ తెరవండి. దరఖాస్తులు, చెల్లింపులు అక్కడే. రసీదు ఉంచండి. సాథీ మీ తరఫున బుకింగ్ లేదా దరఖాస్తు చేయదు.')
];
export default function HomeVideo({language,offline,onSpeak,onStop,onOpen}:{language:Lang;offline:boolean;onSpeak:(s:string)=>void;onStop:()=>void;onOpen:(id:string)=>void}){
 const video=useRef<HTMLVideoElement>(null),[failed,setFailed]=useState(false);
 useEffect(()=>{setFailed(false);return()=>{video.current?.pause();onStop()}},[language]);
 useEffect(()=>{const hidden=()=>{if(document.hidden)video.current?.pause()};document.addEventListener('visibilitychange',hidden);return()=>document.removeEventListener('visibilitychange',hidden)},[]);
 const words={title:L('New here? See how Saathi helps.','पहली बार? देखें साथी कैसे मदद करता है।','మొదటిసారా? సాథీ సహాయం ఎలా చేస్తుందో చూడండి.'),sub:L('28-second illustrated guide · English visuals, captions in your chosen language. No autoplay or background download.','28 सेकंड का चित्रित मार्गदर्शन · अंग्रेज़ी दृश्य, चुनी भाषा में कैप्शन। अपने आप नहीं चलता।','28 సెకన్ల చిత్ర మార్గదర్శనం · ఆంగ్ల దృశ్యాలు, ఎంచుకున్న భాషలో క్యాప్షన్లు. స్వయంగా ప్లే కాదు.'),listen:L('Listen to the guide','मार्गदर्शन सुनें','మార్గదర్శనం వినండి'),stop:L('Stop audio','आवाज़ रोकें','ఆడియో ఆపండి'),text:L('Read the steps','कदम पढ़ें','దశలు చదవండి'),fallback:L('Video is unavailable. Use the spoken guide or the steps below.','वीडियो उपलब्ध नहीं। आवाज़ या नीचे के कदम इस्तेमाल करें।','వీడియో అందుబాటులో లేదు. వాయిస్ లేదా కింది దశలు వాడండి.'),try:L('Try a service now','अब सेवा आज़माएँ','ఇప్పుడు సేవ ప్రయత్నించండి')};
 return <section className="home-video" aria-labelledby="home-video-title"><div><p className="directory-eyebrow">SAATHI · HOW IT WORKS</p><h2 id="home-video-title">{words.title[language]}</h2><p>{words.sub[language]}</p><button className="directory-listen" onClick={()=>{video.current?.pause();onSpeak(tourLines.map(l=>l[language]).join(' '))}}>{words.listen[language]}</button><button className="directory-listen" onClick={onStop}>{words.stop[language]}</button><details><summary>{words.text[language]}</summary><ol>{tourLines.map((line,i)=><li key={i}>{line[language]}</li>)}</ol></details></div><div>{offline||failed?<p role="status">{words.fallback[language]}</p>:<video key={language} ref={video} controls playsInline preload="none" poster="/ruralos/media/saathi-tour-v1.jpg" aria-label={words.title[language]} onPlay={onStop} onError={()=>setFailed(true)}><source src="/ruralos/media/saathi-tour-v1.mp4" type="video/mp4"/><track kind="captions" src={'/ruralos/media/saathi-tour-v1-'+language+'.vtt'} srcLang={language} label={{en:'English',hi:'हिन्दी',te:'తెలుగు'}[language]} default/>{words.fallback[language]}</video>}<p className="home-video-try">{words.try[language]}</p><div className="home-video-links">{[['business',L('Business support','व्यवसाय सहायता','వ్యాపార సహాయం')],['schemes',L('Family benefits','परिवार की योजनाएँ','కుటుంబ పథకాలు')],['aadhaar',L('Document help','दस्तावेज़ सहायता','పత్రాల సహాయం')]].map(([id,label])=><button key={id as string} onClick={()=>{video.current?.pause();onStop();onOpen(id as string)}}>{(label as ReturnType<typeof L>)[language]} →</button>)}</div></div></section>
}
