import React,{useEffect,useRef,useState} from 'react';
import {scenarioChecked,scenarioReviewBy,scenarioResult,scenarioSources,scenariosFor} from '../lib/service-scenarios';
import {createSpeechSession,type SpeechSession} from '../lib/speech-client';
import type {DirectoryLanguage} from '../lib/service-directory';
import './scenario-help.css';
export const scenarioCopy={
 en:{title:'Help for your situation',choose:'Which situation matches yours?',unknown:'Something else / not sure',fact:'What the official information says',next:'Your next step',prepare:'Keep ready privately',followup:'If this does not resolve it',source:'Evidence and scope',listen:'Listen to this answer',stop:'Stop audio',error:'Audio is unavailable. You can still read this answer.',note:'India · national guidance. Your state must confirm local rules, documents and approval. This is not a live account check.',preview:'Hindi and Telugu translations are review previews.',fallback:'Choose the exact situation to see a specific answer. If none fits, use the official service and ask for the exact scheme or status message. Do not share identity numbers here.',stale:'This answer needs a source review. Do not rely on the old rules or amounts; check the current official instructions.',region:'Choose a listed Indian State or Union Territory before using this guidance.',offline:'Offline: this is cached guidance, not a current status check. Reconnect before opening the official service.',open:'Open the relevant official service',checked:'Source reviewed',due:'Review due',general:'General preparation checklist',scope:'Local result, required documents, fees and time limits remain unverified unless stated above.'},
 hi:{title:'आपकी स्थिति के लिए मदद',choose:'आपकी स्थिति कौन सी है?',unknown:'कुछ और / पता नहीं',fact:'आधिकारिक जानकारी क्या बताती है',next:'आपका अगला कदम',prepare:'अपने पास तैयार रखें',followup:'इससे हल न हो तो',source:'स्रोत और लागू सीमा',listen:'यह जवाब सुनें',stop:'आवाज़ रोकें',error:'आवाज़ उपलब्ध नहीं। जवाब पढ़ सकते हैं।',note:'भारत · राष्ट्रीय मार्गदर्शन। स्थानीय नियम, दस्तावेज़ और मंज़ूरी राज्य से पक्के करें। यह लाइव खाता जाँच नहीं है।',preview:'हिन्दी और तेलुगु अनुवाद समीक्षा पूर्वावलोकन हैं।',fallback:'सही स्थिति चुनकर विशेष जवाब देखें। कोई न मिले तो आधिकारिक सेवा से योजना या स्थिति का सही संदेश पूछें। यहाँ पहचान संख्या न दें।',stale:'इस जवाब के स्रोत की समीक्षा ज़रूरी है। पुराने नियम या राशि पर भरोसा न करें; वर्तमान आधिकारिक निर्देश देखें।',region:'इस मार्गदर्शन से पहले सूची में दिया भारतीय राज्य या UT चुनें।',offline:'ऑफलाइन: यह सहेजा मार्गदर्शन है, वर्तमान स्थिति की जाँच नहीं। आधिकारिक सेवा खोलने से पहले इंटरनेट जोड़ें।',open:'संबंधित आधिकारिक सेवा खोलें',checked:'स्रोत की समीक्षा',due:'अगली समीक्षा',general:'सामान्य तैयारी सूची',scope:'ऊपर स्पष्ट न हो तो स्थानीय नतीजा, आवश्यक दस्तावेज़, शुल्क और समय सीमा अभी सत्यापित नहीं हैं।'},
 te:{title:'మీ పరిస్థితికి సహాయం',choose:'మీ పరిస్థితి ఏది?',unknown:'వేరేది / తెలియదు',fact:'అధికారిక సమాచారం చెప్పేది',next:'మీ తదుపరి పని',prepare:'మీ వద్ద సిద్ధంగా ఉంచండి',followup:'దీనితో పరిష్కారం కాకపోతే',source:'మూలం మరియు వర్తించే పరిధి',listen:'ఈ సమాధానం వినండి',stop:'ఆడియో ఆపండి',error:'ఆడియో అందుబాటులో లేదు. సమాధానం చదవవచ్చు.',note:'భారతదేశం · జాతీయ మార్గదర్శనం. స్థానిక నియమాలు, పత్రాలు, ఆమోదాన్ని రాష్ట్రంతో నిర్ధారించాలి. ఇది ప్రత్యక్ష ఖాతా తనిఖీ కాదు.',preview:'హిందీ, తెలుగు అనువాదాలు సమీక్ష ముందస్తు రూపాలు.',fallback:'నిర్దిష్ట సమాధానం కోసం సరైన పరిస్థితి ఎంచుకోండి. ఏదీ సరిపోకపోతే అధికారిక సేవలో పథకం లేదా స్థితి సందేశం ఖచ్చితంగా తెలుసుకోండి. గుర్తింపు సంఖ్యలు ఇక్కడ ఇవ్వవద్దు.',stale:'ఈ సమాధానానికి మూల సమీక్ష అవసరం. పాత నియమాలు లేదా మొత్తాలపై ఆధారపడవద్దు; ప్రస్తుత అధికారిక సూచనలు చూడండి.',region:'ఈ మార్గదర్శనం కోసం జాబితాలో భారత రాష్ట్రం లేదా UT ఎంచుకోండి.',offline:'ఆఫ్‌లైన్: ఇది భద్రపరచిన మార్గదర్శనం; ప్రస్తుత స్థితి తనిఖీ కాదు. అధికారిక సేవకు ఇంటర్నెట్ కలపండి.',open:'సంబంధిత అధికారిక సేవ తెరవండి',checked:'మూల సమీక్ష తేదీ',due:'తదుపరి సమీక్ష',general:'సాధారణ తయారీ జాబితా',scope:'పైన స్పష్టంగా పేర్కొనకపోతే స్థానిక ఫలితం, అవసరమైన పత్రాలు, రుసుము, గడువు ఇంకా ధ్రువీకరించలేదు.'}
};
export function ScenarioAnswer({serviceId,scenarioId,region,language,offline=false,now=Date.now()}:{serviceId:string;scenarioId:string;region:string;language:DirectoryLanguage;offline?:boolean;now?:number}){
 const result=scenarioResult(serviceId,scenarioId,region,now),s=result.scenario,c=scenarioCopy[language];
 if(!s)return <p role="status">{result.status==='stale'?c.stale:result.status==='region'?c.region:c.fallback}</p>;
 const source=scenarioSources[s.source];
 return <div className="scenario-answer">
  <h4>{s.title[language]}</h4><p className="scenario-scope">{c.note} · {region}</p>
  <h5>{c.fact}</h5><p>{s.fact[language]}</p>
  <div className="scenario-next"><h5>{c.next}</h5><p>{s.next[language]}</p>{offline?<p role="status">{c.offline}</p>:<a className="primary" href={s.url} target="_blank" rel="noreferrer">{c.open} ↗</a>}</div>
  <h5>{c.prepare}</h5><p>{s.prepare[language]}</p><h5>{c.followup}</h5><p>{s.followup[language]}</p>
  <p className="scenario-scope">{c.scope}</p>
  <details><summary>{c.source}</summary><p>{source.name} · <span lang="en">{source.published}</span></p><p>{c.checked}: {scenarioChecked} · {c.due}: {scenarioReviewBy.slice(0,10)}</p>{!offline&&<a href={source.url} target="_blank" rel="noreferrer">{source.name} ↗</a>}</details>
 </div>;
}
export default function ScenarioHelp({serviceId,region,language,offline,stopOtherAudio}:{serviceId:string;region:string;language:DirectoryLanguage;offline:boolean;stopOtherAudio:()=>void}){
 const [selected,setSelected]=useState(''),[now,setNow]=useState(Date.now),[error,setError]=useState('');
 const c=scenarioCopy[language],speech=useRef<SpeechSession|null>(null),answer=useRef<HTMLDivElement>(null),focus=useRef(false);
 useEffect(()=>{speech.current=createSpeechSession(()=>{},{en:'en-IN',hi:'hi-IN',te:'te-IN'}[language]);const refresh=()=>{setNow(Date.now());if(document.hidden)speech.current?.stop()};const timer=setInterval(refresh,60000);document.addEventListener('visibilitychange',refresh);return()=>{clearInterval(timer);speech.current?.stop();document.removeEventListener('visibilitychange',refresh)}},[language]);
 useEffect(()=>{if(focus.current){answer.current?.focus();focus.current=false}},[selected]);
 async function listen(){stopOtherAudio();const current=scenarioResult(serviceId,selected,region,Date.now());const s=current.scenario;try{setError('');await speech.current?.speak(s?[s.title[language],c.note,c.fact,s.fact[language],c.next,s.next[language],c.prepare,s.prepare[language],c.followup,s.followup[language],c.scope].join('. '):current.status==='stale'?c.stale:current.status==='region'?c.region:c.fallback,.9)}catch{setError(c.error)}}
 return <section className="scenario-help" aria-label={c.title}><h3>{c.title}</h3>{language!=='en'&&<p className="scenario-scope">{c.preview}</p>}<fieldset><legend>{c.choose}</legend><div className="scenario-choices">{[...scenariosFor(serviceId).map(s=>({id:s.id,title:s.title[language]})),{id:'',title:c.unknown}].map(s=><button type="button" key={s.id} aria-pressed={selected===s.id} onClick={()=>{speech.current?.stop();stopOtherAudio();focus.current=selected!==s.id;setSelected(s.id);setNow(Date.now());setError('')}}>{s.title}</button>)}</div></fieldset><div ref={answer} tabIndex={-1} className="scenario-result"><ScenarioAnswer serviceId={serviceId} scenarioId={selected} region={region} language={language} offline={offline} now={now}/></div><div className="row"><button type="button" className="outline" onClick={()=>void listen()}>{c.listen}</button><button type="button" className="outline" onClick={()=>speech.current?.stop()}>{c.stop}</button></div>{error&&<p role="alert">{error}</p>}</section>;
}
