import React,{lazy,Suspense,useEffect,useRef,useState} from 'react';
import {Sprout,Mic,Search,ArrowRight,ArrowLeft,HeartHandshake,FileCheck2,Bell,Users,ShieldCheck,Volume2,Plane,Stethoscope,Wheat,BriefcaseBusiness,House,GraduationCap,Wallet,ShoppingBasket,LifeBuoy,Radio,LockKeyhole} from 'lucide-react';
import {directory,categories,findServices,serviceTitle,serviceFromQuery,type DirectoryLanguage} from '../lib/service-directory';
import {createSpeechSession,type SpeechSession} from '../lib/speech-client';
import './service-home.css';
const TaskAssistant=lazy(()=>import('./task-assistant'));
const FamilyApp=lazy(()=>import('./app-shell'));
const LiveHub=lazy(()=>import('./live-hub'));
const categoryIcons:Record<string,typeof House>={'Benefits':HeartHandshake,'Documents':FileCheck2,'Health':Stethoscope,'Farming':Wheat,'Work':BriefcaseBusiness,'Property':House,'Education':GraduationCap,'Money':Wallet,'Daily essentials':ShoppingBasket,'Help':LifeBuoy,'Travel':Plane};
const words={en:{welcome:'Hello. What help do you need today?',intro:'Find the right service. Understand your next step.',speak:'Speak your problem',search:'Find a service',hint:'Try pension, Aadhaar, land or train tickets',all:'All services',home:'Home',next:'Choose a service to begin',guide:'Guided steps',count:'services to explore',preview:'English available · Hindi and Telugu are review previews',popular:'Everyday essentials',listen:'Listen',empty:'No matching service. Try a shorter word or choose All services.',clear:'Clear search',disclaimer:'Free guidance. Applications, approvals and payments happen with the official provider.'},hi:{welcome:'नमस्ते। आज आपको किस मदद की ज़रूरत है?',intro:'सही सेवा चुनें। अपना अगला कदम जानें।',speak:'अपनी समस्या बोलें',search:'सेवा खोजें',hint:'पेंशन, आधार, जमीन या रेल टिकट',all:'सभी सेवाएँ',home:'होम',next:'शुरू करने के लिए सेवा चुनें',guide:'कदम जानें',count:'सेवाएँ देखें',preview:'हिन्दी और तेलुगु: समीक्षा पूर्वावलोकन',popular:'रोज़मर्रा की ज़रूरतें',listen:'सुनें',empty:'सेवा नहीं मिली। छोटा शब्द आज़माएँ या सभी सेवाएँ चुनें।',clear:'खोज साफ़ करें',disclaimer:'मार्गदर्शन मुफ़्त है। आवेदन, मंज़ूरी और भुगतान आधिकारिक सेवा पर होते हैं।'},te:{welcome:'నమస్తే. ఈ రోజు మీకు ఏ సహాయం కావాలి?',intro:'సరైన సేవను ఎంచుకోండి. మీ తదుపరి అడుగు తెలుసుకోండి.',speak:'మీ సమస్య చెప్పండి',search:'సేవను వెతకండి',hint:'పెన్షన్, ఆధార్, భూమి లేదా రైలు టికెట్లు',all:'అన్ని సేవలు',home:'హోమ్',next:'ప్రారంభించడానికి ఒక సేవను ఎంచుకోండి',guide:'దశలు తెలుసుకోండి',count:'సేవలను చూడండి',preview:'హిందీ, తెలుగు: సమీక్ష కోసం ముందస్తు రూపం',popular:'రోజువారీ అవసరాలు',listen:'వినండి',empty:'సేవ దొరకలేదు. చిన్న పదంతో వెతకండి లేదా అన్ని సేవలు ఎంచుకోండి.',clear:'శోధన తొలగించండి',disclaimer:'మార్గదర్శనం ఉచితం. దరఖాస్తులు, ఆమోదాలు, చెల్లింపులు అధికారిక సేవలో జరుగుతాయి.'}};
const categoryNames:Record<string,[string,string]>={'All':['सभी','అన్నీ'],'Benefits':['योजनाएँ','పథకాలు'],'Documents':['दस्तावेज़','పత్రాలు'],'Health':['स्वास्थ्य','ఆరోగ్యం'],'Farming':['खेती','వ్యవసాయం'],'Work':['रोज़गार','ఉపాధి'],'Property':['संपत्ति','ఆస్తి'],'Education':['पढ़ाई','విద్య'],'Money':['पैसे','డబ్బు'],'Daily essentials':['दैनिक ज़रूरतें','రోజువారీ అవసరాలు'],'Help':['सहायता','సహాయం'],'Travel':['यात्रा','ప్రయాణం']};
function initialLanguage():DirectoryLanguage{const v=new URLSearchParams(location.search).get('language');return v==='hi'||v==='te'?v:'en'}
export default function ServiceHome(){
 const[language,setLanguage]=useState<DirectoryLanguage>(initialLanguage),[query,setQuery]=useState(''),[category,setCategory]=useState('All'),[selected,setSelected]=useState<string|null>(()=>serviceFromQuery(location.search)),[mode,setMode]=useState(()=>new URLSearchParams(location.search).has('view')?'family':'home'),[error,setError]=useState(''),[phase,setPhase]=useState('ready'),[offline,setOffline]=useState(!navigator.onLine),[voiceConsent,setVoiceConsent]=useState(false);
 const speech=useRef<SpeechSession|null>(null),searchInput=useRef<HTMLInputElement>(null),heading=useRef<HTMLHeadingElement>(null);const t=words[language];
 useEffect(()=>{document.documentElement.lang=language;speech.current=createSpeechSession(setPhase,{en:'en-IN',hi:'hi-IN',te:'te-IN'}[language]);return()=>speech.current?.stop()},[language]);
 useEffect(()=>{const net=()=>setOffline(!navigator.onLine);const back=()=>{setSelected(serviceFromQuery(location.search));setMode(new URLSearchParams(location.search).has('view')?'family':'home');setLanguage(initialLanguage());speech.current?.stop()};const hidden=()=>{if(document.hidden)speech.current?.stop()};window.addEventListener('online',net);window.addEventListener('offline',net);window.addEventListener('popstate',back);document.addEventListener('visibilitychange',hidden);return()=>{window.removeEventListener('online',net);window.removeEventListener('offline',net);window.removeEventListener('popstate',back);document.removeEventListener('visibilitychange',hidden)}},[]);
 function navigate(id:string|null,nextMode='home'){speech.current?.stop();setError('');setSelected(id);setMode(nextMode);const params=new URLSearchParams();if(language!=='en')params.set('language',language);if(id)params.set('service',id);if(nextMode==='family')params.set('view','Home');history.pushState(null,'','/ruralos/'+(params.size?'?'+params:''));window.scrollTo({top:0,behavior:'instant'});setTimeout(()=>heading.current?.focus(),0)}
 function changeLanguage(l:DirectoryLanguage){setLanguage(l);setError('');const p=new URLSearchParams(location.search);p.set('language',l);history.replaceState(null,'','/ruralos/?'+p)}
 async function speak(text:string){try{setError('');await speech.current?.speak(text,.9)}catch(e){setError((e as Error).message)}}
 async function listen(){try{setError('');const heard=await speech.current!.listen();setQuery(heard);setCategory('All');searchInput.current?.focus()}catch(e){setError((e as Error).message)}}
 const results=findServices(query,category,language);const isHome=mode==='home'&&!selected;
 return <div className="rural-directory"><a className="directory-skip" href="#directory-main">Skip to services</a><header className="directory-header"><button className="directory-brand" onClick={()=>navigate(null)} aria-label="Saathi home"><span><Sprout size={26}/></span><strong>Saathi<small>Rural Family Action OS</small></strong></button><div className="directory-header-actions"><label><span className="sr-only">Language</span><select value={language} onChange={e=>changeLanguage(e.target.value as DirectoryLanguage)}><option value="en">English</option><option value="hi">हिन्दी · Preview</option><option value="te">తెలుగు · Preview</option></select></label><a href="tel:112" className="directory-emergency">112 · Emergency</a></div></header>
 <nav className="directory-nav" aria-label="Main navigation"><button aria-current={isHome?'page':undefined} onClick={()=>navigate(null)}><House size={18}/>{t.home}</button><button aria-current={mode==='family'?'page':undefined} onClick={()=>navigate(null,'family')}><Users size={18}/>Family tools</button><button aria-current={mode==='live'?'page':undefined} onClick={()=>navigate(null,'live')}><Radio size={18}/>Live information</button><a href="/ruralos/tracking"><LockKeyhole size={17}/>Private tracking</a><a href="/ruralos/install/">Install app</a></nav>
 {offline&&<div className="directory-alert" role="status">Offline · Cached guidance may be outdated. Reconnect to check official services and live information.</div>}
 <main id="directory-main" className="directory-main">{isHome?<><section className="directory-welcome"><div><p className="directory-eyebrow">FOR YOUR FAMILY · ACROSS INDIA</p><h1 ref={heading} tabIndex={-1}>{t.welcome}</h1><p>{t.intro}</p><div className="directory-voice-actions"><button className="directory-speak" disabled={!voiceConsent||phase!=='ready'} onClick={()=>void listen()}><Mic size={25}/>{phase==='listening'?'Listening…':t.speak}</button><button className="directory-listen" onClick={()=>void speak(t.welcome+' '+t.intro)}><Volume2 size={20}/>{t.listen}</button>{phase!=='ready'&&<button className="directory-listen" onClick={()=>speech.current?.stop()}>Stop</button>}</div><label className="directory-consent"><input type="checkbox" checked={voiceConsent} onChange={e=>{setVoiceConsent(e.target.checked);if(!e.target.checked)speech.current?.stop()}}/>Allow voice search. My browser or device may process audio online. Do not speak IDs, PINs or OTPs.</label><p className="directory-caption">{t.preview}</p></div><aside className="directory-note"><ShieldCheck size={28}/><h2>Know what happens next</h2><p>Choose a service → answer simple questions → review your steps → continue with the official provider.</p><p>Browsing is free. No account needed.</p><span>{directory.length} {t.count}</span></aside></section>
 {error&&<p role="alert" className="directory-alert">{error}</p>}
 <section aria-labelledby="everyday-title"><div className="directory-section-heading"><h2 id="everyday-title">{t.popular}</h2><span>One tap to begin</span></div><div className="directory-essentials">{[['schemes',HeartHandshake,'Find family benefits'],['documents',FileCheck2,'Get document help']].map(([id,Icon,label])=>{const I=Icon as typeof House;return <button key={String(id)} onClick={()=>navigate(String(id))}><I size={27}/><span>{language==='en'?String(label):serviceTitle(String(id),language)}</span><ArrowRight size={20}/></button>})}<a href="https://rural-family-action-os.vjyrcks.chatgpt.site/?view=Reminders"><Bell size={27}/><span>My reminders<small>Secure sign-in to save</small></span><ArrowRight size={20}/></a><a href="https://rural-family-action-os.vjyrcks.chatgpt.site/?view=Help"><Users size={27}/><span>Ask for help<small>Saved request · no staffed callback yet</small></span><ArrowRight size={20}/></a></div></section>
 <section className="directory-catalog" aria-labelledby="catalog-title"><div className="directory-section-heading"><h2 id="catalog-title">{t.all}</h2><span aria-live="polite">{results.length} / {directory.length}</span></div><label className="directory-search"><Search size={23}/><span className="sr-only">{t.search}</span><input ref={searchInput} value={query} maxLength={250} onChange={e=>setQuery(e.target.value)} placeholder={t.hint}/>{query&&<button onClick={()=>setQuery('')} aria-label={t.clear}>×</button>}</label><div className="directory-categories" aria-label="Service categories">{categories.map(c=><button key={c} aria-pressed={category===c} onClick={()=>setCategory(c)}>{language==='en'?c:categoryNames[c]?.[language==='hi'?0:1]??c}</button>)}</div><p className="directory-caption">{t.disclaimer}</p><div className="directory-cards">{results.map(s=>{const Icon=categoryIcons[s.category]??LifeBuoy;return <a className="directory-card" key={s.id} href={'/ruralos/?service='+s.id+'&language='+language} onClick={e=>{if(e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;e.preventDefault();navigate(s.id)}}><span className="directory-card-icon"><Icon size={24}/></span><span className="directory-card-copy"><strong>{serviceTitle(s.id,language)}</strong><small>{language==='en'?s.description:t.guide}</small><em>{t.guide} · {language==='en'?s.category:categoryNames[s.category]?.[language==='hi'?0:1]}</em></span><ArrowRight size={20}/></a>})}</div>{!results.length&&<p role="status" className="directory-alert">{t.empty}<button onClick={()=>{setCategory('All');setQuery('')}}>{t.clear}</button></p>}</section></>:<><button className="directory-back" onClick={()=>navigate(null)}><ArrowLeft size={20}/>{t.home} · {t.all}</button><h1 className="directory-work-title" tabIndex={-1} ref={heading}>{selected?serviceTitle(selected,language):mode==='live'?'Live information':'Family tools'}</h1><Suspense fallback={<p role="status">Opening your service…</p>}>{selected?<TaskAssistant key={selected+language} initialService={selected} initialLanguage={language}/>:mode==='live'?<LiveHub initiallyOpen/>:<FamilyApp/>}</Suspense></>}
 </main><footer className="directory-footer"><span><Sprout size={20}/>One family. One next step.</span><div><a href="/ruralos/integrations/">What is connected?</a><a href="https://rural-family-action-os.vjyrcks.chatgpt.site/privacy">Privacy</a><a href="https://rural-family-action-os.vjyrcks.chatgpt.site/support">Support</a></div><p>Independent early-access guidance · Not a government portal · Emergency calls go directly to the number; Saathi does not dispatch help.</p></footer></div>
}
