import React,{useEffect,useRef,useState} from 'react';
import {playbooks,preparationFor,preparationProgress,preparationStages,type PreparationStage} from '../lib/service-playbooks';
import {createSpeechSession,type SpeechSession} from '../lib/speech-client';
import type {DirectoryLanguage} from '../lib/service-directory';
import './service-preparation.css';
import AadhaarMobileHelp from './aadhaar-mobile-help';
export const preparationCopy={
 en:{title:'Your practical plan',choose:'Choose the closest task',stage:'Where are you with this task?',stages:['Not started','Already in progress','Stuck or declined','Completed with the provider'],next:'Do this next',items:'Get these points ready',checked:'checked by you',ask:'Questions to ask the official service',avoid:'Avoid a wasted visit',pending:'Check the existing reference and the exact pending step first. Ask who must act next and how to follow up. Do not create a duplicate just because a reply is delayed.',blocked:'Keep the written reason or error privately. Ask which requirement can be corrected and whether a review route or deadline applies. Do not assume a rejection is final or that a second application will fix it.',done:'Keep the official confirmation and receipts privately. Check whether a separate follow-up is still required. Only the provider can confirm completion.',ready:'Preparation checked. Confirm current requirements with the official service before proceeding.',note:'This is a preparation aid, not an official required-document list or an eligibility decision. Ticks are your own notes, not live status. They clear when you leave or restart.',preview:'Detailed preparation is currently in English. Hindi and Telugu controls are previews; use the existing translated steps below or ask someone you trust to help read the details.',listen:'Listen to this plan in English',stop:'Stop audio',error:'Audio could not play. The plan remains available to read.',missing:'First unchecked point',context:'Plan for',unknown:'Your written request has not been interpreted automatically. Choose the closest task to tailor the plan.',reset:'Clear preparation ticks'},
 hi:{title:'आपकी काम की योजना',choose:'सबसे नज़दीकी काम चुनें',stage:'यह काम अभी कहाँ तक पहुँचा है?',stages:['शुरू नहीं किया','काम चल रहा है','रुक गया या मना हुआ','प्रदाता ने पूरा किया'],next:'अब यह करें',items:'ये बातें तैयार रखें',checked:'आपने जाँचा',ask:'आधिकारिक सेवा से ये सवाल पूछें',avoid:'बेकार चक्कर से बचें',pending:'पहले पुराने संदर्भ से पता करें कि कौन सा कदम बाकी है। पूछें कि अब किसे कार्रवाई करनी है और कैसे आगे पता करें। केवल देरी होने पर दूसरा आवेदन न करें।',blocked:'लिखित कारण या त्रुटि अपने पास सुरक्षित रखें। पूछें कि क्या सुधारना है और क्या समीक्षा का रास्ता या समय सीमा है।',done:'आधिकारिक पुष्टि और रसीद सुरक्षित रखें। पूछें कि कोई अलग अगला काम बाकी तो नहीं है। पूरा होने की पुष्टि केवल प्रदाता कर सकता है।',ready:'तैयारी जाँच ली गई। आगे बढ़ने से पहले आधिकारिक सेवा से वर्तमान ज़रूरतें पक्की करें।',note:'यह तैयारी में मदद है, आधिकारिक दस्तावेज़ सूची या पात्रता निर्णय नहीं। टिक आपके नोट हैं, लाइव स्थिति नहीं। बाहर जाने या दोबारा शुरू करने पर मिट जाते हैं।',preview:'विस्तृत तैयारी अभी अंग्रेज़ी में है। हिन्दी और तेलुगु नियंत्रण पूर्वावलोकन हैं। नीचे अनूदित कदम देखें या भरोसेमंद व्यक्ति से विवरण पढ़ने में मदद लें।',listen:'विस्तृत योजना अंग्रेज़ी में सुनें',stop:'आवाज़ रोकें',error:'आवाज़ नहीं चली। योजना पढ़ने के लिए उपलब्ध है।',missing:'पहली बिना जाँची बात',context:'योजना',unknown:'आपकी लिखी बात का अपने आप अर्थ नहीं निकाला गया। योजना के लिए सबसे नज़दीकी काम चुनें।',reset:'तैयारी के टिक साफ़ करें'},
 te:{title:'మీ పని ప్రణాళిక',choose:'దగ్గరగా ఉన్న పనిని ఎంచుకోండి',stage:'ఈ పని ఎంతవరకు వచ్చింది?',stages:['ఇంకా ప్రారంభించలేదు','పని జరుగుతోంది','ఆగింది లేదా తిరస్కరించారు','ప్రదాత పూర్తి చేశారు'],next:'తర్వాత ఇలా చేయండి',items:'ఈ విషయాలు సిద్ధం చేసుకోండి',checked:'మీరు తనిఖీ చేసినవి',ask:'అధికారిక సేవను అడగాల్సిన ప్రశ్నలు',avoid:'అనవసర ప్రయాణాన్ని నివారించండి',pending:'ముందు పాత రిఫరెన్స్‌తో ఏ దశ పెండింగ్‌లో ఉందో చూడండి. తర్వాత ఎవరు చర్య తీసుకోవాలి, ఎలా తెలుసుకోవాలి అని అడగండి. ఆలస్యం వల్ల మాత్రమే మరో దరఖాస్తు చేయవద్దు.',blocked:'లిఖిత కారణం లేదా లోపాన్ని మీ వద్ద భద్రంగా ఉంచుకోండి. ఏది సరిచేయాలి, సమీక్ష మార్గం లేదా గడువు ఉందా అని అడగండి.',done:'అధికారిక నిర్ధారణ, రసీదులు భద్రంగా ఉంచుకోండి. వేరే తదుపరి పని ఉందా చూడండి. పూర్తయిందని ప్రదాత మాత్రమే నిర్ధారించగలరు.',ready:'తయారీ తనిఖీ పూర్తయింది. ముందుకు వెళ్లే ముందు అధికారిక సేవతో ప్రస్తుత అవసరాలు నిర్ధారించండి.',note:'ఇది తయారీ సహాయం మాత్రమే; అధికారిక పత్రాల జాబితా లేదా అర్హత నిర్ణయం కాదు. టిక్‌లు మీ నోట్స్, లైవ్ స్థితి కాదు. బయటకు వెళ్లినా మళ్లీ మొదలుపెట్టినా తొలగుతాయి.',preview:'వివరమైన తయారీ ప్రస్తుతం ఆంగ్లంలో ఉంది. హిందీ, తెలుగు నియంత్రణలు ముందస్తు రూపాలు. కింద అనువదించిన దశలు చూడండి లేదా నమ్మకమైన వ్యక్తి చదివేందుకు సహాయం కోరండి.',listen:'వివరమైన ప్రణాళిక ఆంగ్లంలో వినండి',stop:'ఆడియో ఆపండి',error:'ఆడియో ప్లే కాలేదు. ప్రణాళిక చదవవచ్చు.',missing:'మొదటి తనిఖీ చేయని విషయం',context:'ప్రణాళిక',unknown:'మీరు రాసిన అభ్యర్థనను స్వయంచాలకంగా అర్థం చేసుకోలేదు. ప్రణాళిక కోసం దగ్గరగా ఉన్న పనిని ఎంచుకోండి.',reset:'తయారీ టిక్‌లను తొలగించండి'}
};
export default function ServicePreparation({serviceId,goal,region,language,stopOtherAudio}:{serviceId:string;goal:string;region:string;language:DirectoryLanguage;stopOtherAudio:()=>void}){
 const initial=preparationFor(serviceId,goal),p=playbooks[serviceId],c=preparationCopy[language];
 const [choice,setChoice]=useState<number|null>(initial.index),[stage,setStage]=useState<PreparationStage>('start'),[checked,setChecked]=useState<number[]>([]),[error,setError]=useState(''),[speaking,setSpeaking]=useState(false);
 const speech=useRef<SpeechSession|null>(null);
 useEffect(()=>{speech.current=createSpeechSession(phase=>setSpeaking(phase==='speaking'),'en-IN');const stop=()=>{if(document.hidden)speech.current?.stop()};document.addEventListener('visibilitychange',stop);return()=>{speech.current?.stop();document.removeEventListener('visibilitychange',stop)}},[]);
 const progress=preparationProgress(p.prepare,checked),action=choice===null?null:p.actions[choice];
 const guidance=stage==='pending'?c.pending:stage==='blocked'?c.blocked:stage==='done'?c.done:null;
 async function listen(){stopOtherAudio();const spokenNext=stage==='start'?action:preparationCopy.en[stage];try{setError('');await speech.current?.speak([spokenNext,...p.prepare,...p.ask,p.trap].filter(Boolean).join('. '),.9)}catch{setError(c.error)}}
 return <section className="service-preparation" aria-label={c.title}>
  <p className="prep-kicker">{c.context} · {region}</p><h3>{c.title}</h3>
  {language!=='en'&&<p className="prep-note">{c.preview}</p>}
  {choice===null&&<p>{c.unknown}</p>}
  <fieldset><legend>{c.choose}</legend><div className="prep-options">{p.goals.map((g,i)=><button lang="en" type="button" aria-pressed={choice===i} key={g} onClick={()=>{speech.current?.stop();setChoice(i);setChecked([]);setError('')}}>{g}</button>)}</div></fieldset>
  <label>{c.stage}<select value={stage} onChange={e=>{speech.current?.stop();setStage(e.target.value as PreparationStage);setError('')}}>{preparationStages.map((s,i)=><option key={s} value={s}>{c.stages[i]}</option>)}</select></label>
  {serviceId==='aadhaar'&&stage==='start'&&<AadhaarMobileHelp language={language} stopOtherAudio={()=>{speech.current?.stop();stopOtherAudio()}}/>}
  <div className="prep-next" aria-live="polite"><h4>{c.next}</h4>{guidance&&<p>{guidance}</p>}{stage==='start'&&action&&<p lang="en">{action}</p>}{stage==='start'&&action&&<p><strong>{progress.next?c.missing:c.ready}</strong>{progress.next&&<span lang="en">: {progress.next}</span>}</p>}</div>
  <div className="prep-columns"><fieldset><legend>{c.items}</legend><p role="status">{progress.complete} / {progress.total} · {c.checked}</p>{p.prepare.map((item,i)=><label className="prep-item" key={item}><input type="checkbox" checked={checked.includes(i)} onChange={e=>setChecked(old=>e.target.checked?[...old,i]:old.filter(x=>x!==i))}/><span lang="en">{item}</span></label>)}<button type="button" className="outline" onClick={()=>setChecked([])}>{c.reset}</button></fieldset><section><h4>{c.ask}</h4><ol lang="en">{p.ask.map(q=><li key={q}>{q}</li>)}</ol><h4>{c.avoid}</h4><p lang="en">{p.trap}</p></section></div>
  <p className="prep-note">{c.note}</p><div className="row"><button type="button" className="outline" disabled={speaking} onClick={()=>void listen()}>{c.listen}</button>{speaking&&<button type="button" className="outline" onClick={()=>speech.current?.stop()}>{c.stop}</button>}</div>{error&&<p role="alert">{error}</p>}
 </section>
}
