import React,{lazy,Suspense,useEffect,useRef,useState} from 'react';
import {Sprout,Mic,Search,ArrowRight,ArrowLeft,HeartHandshake,FileCheck2,Bell,Users,ShieldCheck,Volume2,Plane,Stethoscope,Wheat,BriefcaseBusiness,House,GraduationCap,Wallet,ShoppingBasket,LifeBuoy,Radio,LockKeyhole,BookOpen,MapPin,MessageCircle,Check} from 'lucide-react';
import {directory,categories,findServices,resolveSpokenService,serviceTitle,serviceFromQuery,type DirectoryLanguage} from '../lib/service-directory';
import {createSpeechSession,type SpeechSession} from '../lib/speech-client';
import {homeCopy,homeMode,tutorialSteps,familyShortcuts,companionLink,languageIndex} from '../lib/home-experience';
import {voiceCaptureError} from '../lib/voice-safety';
import './service-home.css';
import HomeVideo from './home-video';
import HomeLaunch from './home-launch';
import {HomeDesk,HomeStarts,HomeSteps} from './home-desk';
import {deskCopy} from '../lib/home-desk';
import AlertPreview from './alert-preview';
import './home-desk.css';
import {homeCategories,launchCopy} from '../lib/home-launch';
const EnterpriseGuide=lazy(()=>import('./enterprise-guide'));
const TaskAssistant=lazy(()=>import('./task-assistant'));
const TravelPlanner=lazy(()=>import('./travel-planner'));
const FamilyApp=lazy(()=>import('./app-shell'));
const LiveHub=lazy(()=>import('./live-hub'));
const HowToGuide=lazy(()=>import('./how-to-guide'));
const categoryIcons:Record<string,typeof House>={'Benefits':HeartHandshake,'Documents':FileCheck2,'Health':Stethoscope,'Farming':Wheat,'Work':BriefcaseBusiness,'Property':House,'Education':GraduationCap,'Money':Wallet,'Daily essentials':ShoppingBasket,'Help':LifeBuoy,'Travel':Plane};
const words={en:{welcome:'Hello. What help do you need today?',intro:'Find the right service. Understand your next step.',speak:'Speak your problem',search:'Find a service',hint:'Try pension, Aadhaar, land or train tickets',all:'All services',home:'Home',next:'Choose a service to begin',guide:'Guided steps',count:'services to explore',preview:'English available · Hindi and Telugu are review previews',popular:'Everyday essentials',listen:'Listen',heard:'I heard:',choose:'Choose the service you meant below.',empty:'No matching service. Try a shorter word or choose All services.',clear:'Clear search',disclaimer:'Free guidance. Applications, approvals and payments happen with the official provider.'},hi:{welcome:'नमस्ते। आज आपको किस मदद की ज़रूरत है?',intro:'सही सेवा चुनें। अपना अगला कदम जानें।',speak:'अपनी समस्या बोलें',search:'सेवा खोजें',hint:'पेंशन, आधार, जमीन या रेल टिकट',all:'सभी सेवाएँ',home:'होम',next:'शुरू करने के लिए सेवा चुनें',guide:'कदम जानें',count:'सेवाएँ देखें',preview:'हिन्दी और तेलुगु: समीक्षा पूर्वावलोकन',popular:'रोज़मर्रा की ज़रूरतें',listen:'सुनें',heard:'हमने सुना:',choose:'नीचे सही सेवा चुनें।',empty:'सेवा नहीं मिली। छोटा शब्द आज़माएँ या सभी सेवाएँ चुनें।',clear:'खोज साफ़ करें',disclaimer:'मार्गदर्शन मुफ़्त है। आवेदन, मंज़ूरी और भुगतान आधिकारिक सेवा पर होते हैं।'},te:{welcome:'నమస్తే. ఈ రోజు మీకు ఏ సహాయం కావాలి?',intro:'సరైన సేవను ఎంచుకోండి. మీ తదుపరి అడుగు తెలుసుకోండి.',speak:'మీ సమస్య చెప్పండి',search:'సేవను వెతకండి',hint:'పెన్షన్, ఆధార్, భూమి లేదా రైలు టికెట్లు',all:'అన్ని సేవలు',home:'హోమ్',next:'ప్రారంభించడానికి ఒక సేవను ఎంచుకోండి',guide:'దశలు తెలుసుకోండి',count:'సేవలను చూడండి',preview:'హిందీ, తెలుగు: సమీక్ష కోసం ముందస్తు రూపం',popular:'రోజువారీ అవసరాలు',listen:'వినండి',heard:'మేము విన్నది:',choose:'కింద మీరు ఉద్దేశించిన సేవను ఎంచుకోండి.',empty:'సేవ దొరకలేదు. చిన్న పదంతో వెతకండి లేదా అన్ని సేవలు ఎంచుకోండి.',clear:'శోధన తొలగించండి',disclaimer:'మార్గదర్శనం ఉచితం. దరఖాస్తులు, ఆమోదాలు, చెల్లింపులు అధికారిక సేవలో జరుగుతాయి.'}};
const categoryNames:Record<string,[string,string]>={'All':['सभी','అన్నీ'],'Benefits':['योजनाएँ','పథకాలు'],'Documents':['दस्तावेज़','పత్రాలు'],'Health':['स्वास्थ्य','ఆరోగ్యం'],'Farming':['खेती','వ్యవసాయం'],'Work':['रोज़गार','ఉపాధి'],'Property':['संपत्ति','ఆస్తి'],'Education':['पढ़ाई','విద్య'],'Money':['पैसे','డబ్బు'],'Daily essentials':['दैनिक ज़रूरतें','రోజువారీ అవసరాలు'],'Help':['सहायता','సహాయం'],'Travel':['यात्रा','ప్రయాణం']};
function initialLanguage():DirectoryLanguage{const v=new URLSearchParams(location.search).get('language');return v==='hi'||v==='te'?v:'en'}
export default function ServiceHome(){
 const[language,setLanguage]=useState<DirectoryLanguage>(initialLanguage),[query,setQuery]=useState(''),[category,setCategory]=useState('All'),[selected,setSelected]=useState<string|null>(()=>serviceFromQuery(location.search)),[mode,setMode]=useState(()=>homeMode(location.search)),[error,setError]=useState(''),[phase,setPhase]=useState('ready'),[offline,setOffline]=useState(!navigator.onLine),[voiceConsent,setVoiceConsent]=useState(false),[voiceOpen,setVoiceOpen]=useState(false),[voiceSummary,setVoiceSummary]=useState('');
 const speech=useRef<SpeechSession|null>(null),searchInput=useRef<HTMLInputElement>(null),heading=useRef<HTMLHeadingElement>(null),consentInput=useRef<HTMLInputElement>(null),voiceButton=useRef<HTMLButtonElement>(null);const t=words[language],c=homeCopy[language],d=deskCopy[language],li=languageIndex(language);
 useEffect(()=>{document.documentElement.lang=language;speech.current=createSpeechSession(setPhase,{en:'en-IN',hi:'hi-IN',te:'te-IN'}[language]);return()=>speech.current?.stop()},[language]);
 useEffect(()=>{const net=()=>setOffline(!navigator.onLine);const back=()=>{setSelected(serviceFromQuery(location.search));setMode(homeMode(location.search));setLanguage(initialLanguage());setVoiceOpen(false);speech.current?.stop()};const hidden=()=>{if(document.hidden)speech.current?.stop()};window.addEventListener('online',net);window.addEventListener('offline',net);window.addEventListener('popstate',back);document.addEventListener('visibilitychange',hidden);return()=>{window.removeEventListener('online',net);window.removeEventListener('offline',net);window.removeEventListener('popstate',back);document.removeEventListener('visibilitychange',hidden)}},[]);
 useEffect(()=>{if(voiceOpen)consentInput.current?.focus()},[voiceOpen]);
 function navigate(id:string|null,nextMode:ReturnType<typeof homeMode>='home'){speech.current?.stop();setError('');setSelected(id);setMode(nextMode);setVoiceOpen(false);const params=new URLSearchParams();if(language!=='en')params.set('language',language);if(id)params.set('service',id);if(nextMode==='family')params.set('view','Home');else if(nextMode!=='home')params.set('section',nextMode);history.pushState(null,'','/ruralos/'+(params.size?'?'+params:''));window.scrollTo({top:0,behavior:'instant'});setTimeout(()=>heading.current?.focus(),0)}
 function changeLanguage(l:DirectoryLanguage){setLanguage(l);setError('');const p=new URLSearchParams(location.search);p.set('language',l);history.replaceState(null,'','/ruralos/?'+p)}
 async function speak(text:string){try{setError('');await speech.current?.speak(text,.9)}catch(e){setError((e as Error).message)}}
 async function listen(){if(!voiceConsent){setVoiceOpen(true);return}if(phase!=='ready')return;try{setError('');const heard=(await speech.current!.listen()).slice(0,250).trim();if(!heard)return;const match=resolveSpokenService(heard,language);setQuery(heard);setCategory('All');if(match){navigate(match);return}setVoiceSummary(t.heard+' “'+heard+'” '+t.choose);setVoiceOpen(false);setTimeout(()=>{document.getElementById('catalog-title')?.scrollIntoView({block:'start'});searchInput.current?.focus({preventScroll:true})},0)}catch(e){setError(voiceCaptureError(li,e))}}
 function searchFromTop(value:string){setCategory('All');setQuery(value.slice(0,250));setVoiceSummary('');document.getElementById('catalog-title')?.scrollIntoView({block:'start'});searchInput.current?.focus({preventScroll:true})}
 function browse(cat='All'){setCategory(cat);setQuery('');document.getElementById('catalog-title')?.scrollIntoView({block:'start'});searchInput.current?.focus({preventScroll:true})}
 const results=findServices(query,category,language);const isHome=mode==='home'&&!selected;
 return <div className="rural-directory"><a className="directory-skip" href="#directory-main">Skip to services</a><header className="directory-header"><button className="directory-brand" onClick={()=>navigate(null)} aria-label="Saathi home"><span><Sprout size={26}/></span><strong>Saathi<small>Rural Family Action OS</small></strong></button><div className="directory-header-actions"><label><span className="sr-only">Language</span><select value={language} onChange={e=>changeLanguage(e.target.value as DirectoryLanguage)}><option value="en">English</option><option value="hi">हिन्दी · Preview</option><option value="te">తెలుగు · Preview</option></select></label><a href="tel:112" className="directory-emergency">112 · Emergency</a></div></header>
 <nav className="directory-nav" aria-label="Main navigation">{isHome&&<button onClick={()=>browse()}><Search size={18}/>{t.all}</button>}<button aria-current={isHome?'page':undefined} onClick={()=>navigate(null)}><House size={18}/>{t.home}</button><button aria-current={mode==='guide'?'page':undefined} onClick={()=>navigate(null,'guide')}><BookOpen size={18}/>{c.how}</button><button aria-current={mode==='family'?'page':undefined} onClick={()=>navigate(null,'family')}><Users size={18}/>{d.family}</button><button aria-current={mode==='live'?'page':undefined} onClick={()=>navigate(null,'live')}><Radio size={18}/>{d.live}</button><a href="/ruralos/alerts/"><Bell size={18}/>{["Alerts","सूचनाएँ","అలర్ట్‌లు"][li]}</a><a href="/ruralos/install/">{['Install app','ऐप इंस्टॉल करें','యాప్ ఇన్‌స్టాల్'][li]}</a></nav>
 {offline&&<div className="directory-alert" role="status">Offline · Cached guidance may be outdated. Reconnect to check official services and live information.</div>}
 <main id="directory-main" className="directory-main">{isHome?<><HomeDesk language={language} heading={heading} voice={<div className="directory-voice-actions"><button ref={voiceButton} className="directory-speak" disabled={phase!=='ready'} aria-expanded={voiceOpen} aria-controls="voice-search-consent" onClick={()=>void listen()}><Mic size={25}/>{phase==='listening'?c.listening:t.speak}<ArrowRight size={19}/></button><button className="directory-listen" onClick={()=>void speak(c.hello+' '+c.intro)}><Volume2 size={20}/>{t.listen}</button>{phase!=='ready'&&<button className="directory-listen" onClick={()=>speech.current?.stop()}>{c.stop}</button>}</div>} search={<HomeLaunch key={language} language={language} onOpen={id=>navigate(id)} onBrowse={searchFromTop}/>}/>
 {voiceOpen&&<section id="voice-search-consent" className="saathi-voice-panel" aria-label={c.voice}><div><h2>{c.voice}</h2><p>{c.voiceInfo}</p><label className="directory-consent"><input ref={consentInput} type="checkbox" checked={voiceConsent} onChange={e=>{setVoiceConsent(e.target.checked);if(!e.target.checked)speech.current?.stop()}}/>{c.voiceAgree}</label></div><div><button className="directory-speak" disabled={!voiceConsent||phase!=='ready'} onClick={()=>void listen()}><Mic size={20}/>{t.speak}</button><button className="directory-listen" onClick={()=>{speech.current?.stop();setVoiceOpen(false);voiceButton.current?.focus()}}>{c.close}</button></div></section>}
 {error&&<p role="alert" className="directory-alert">{error}</p>}
 <HomeVideo language={language} offline={offline} onSpeak={s=>void speak(s)} onStop={()=>speech.current?.stop()} onOpen={id=>navigate(id)}/><section className="enterprise-home"><div><p className="directory-eyebrow">{["START OR GROW","शुरू करें या बढ़ाएँ","ప్రారంభించండి లేదా పెంచండి"][li]}</p><h2>{["Your business idea. A clearer starting point.","आपका व्यवसाय विचार। शुरुआत का सही रास्ता।","మీ వ్యాపార ఆలోచన. ప్రారంభానికి స్పష్టమైన మార్గం."][li]}</h2><p>{["Explore central programmes for loans, subsidies, training and MSME registration.","ऋण, अनुदान, प्रशिक्षण और MSME पंजीकरण के केंद्रीय कार्यक्रम देखें।","రుణాలు, సబ్సిడీలు, శిక్షణ, MSME నమోదు కోసం కేంద్ర కార్యక్రమాలు చూడండి."][li]}</p></div><button className="directory-speak" onClick={()=>navigate("business")}>{["Explore business support","व्यवसाय सहायता देखें","వ్యాపార సహాయం చూడండి"][li]}<ArrowRight size={20}/></button></section><HomeStarts language={language} onOpen={id=>navigate(id)}/>
 <AlertPreview language={language}/>
 <HomeSteps language={language}><Suspense fallback={<p role="status">{c.how}</p>}><HowToGuide embedded language={language} onSpeak={s=>void speak(s)} onStop={()=>speech.current?.stop()} onTry={()=>navigate('aadhaar')}/></Suspense><button className="directory-listen" onClick={()=>navigate(null,'guide')}>{c.faqTitle}<ArrowRight size={18}/></button></HomeSteps>
 <section className="directory-catalog" aria-labelledby="catalog-title"><div className="directory-section-heading"><div><p className="directory-eyebrow">{directory.length} {c.services}</p><h2 id="catalog-title">{d.catalog}</h2><p>{d.catalogIntro}</p></div><span aria-live="polite">{results.length} / {directory.length}</span></div>{voiceSummary&&<p className="directory-alert" role="status">{voiceSummary}</p>}<label className="directory-search"><Search size={23}/><span className="sr-only">{t.search}</span><input ref={searchInput} value={query} maxLength={250} onChange={e=>{setQuery(e.target.value);setVoiceSummary('')}} placeholder={t.hint}/>{query&&<button onClick={()=>{setQuery('');setVoiceSummary('')}} aria-label={t.clear}>×</button>}</label><div className="directory-categories" aria-label="Service categories">{['All',...homeCategories].map(c=><button key={c} aria-pressed={category===c} onClick={()=>setCategory(c)}>{language==='en'?c:categoryNames[c]?.[language==='hi'?0:1]??c}</button>)}</div><p className="directory-caption">{t.disclaimer}</p><div className="directory-cards">{results.map(s=>{const Icon=categoryIcons[s.category]??LifeBuoy;return <a className="directory-card" key={s.id} href={'/ruralos/?service='+s.id+'&language='+language} onClick={e=>{if(e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;e.preventDefault();navigate(s.id)}}><span className="directory-card-icon"><Icon size={24}/></span><span className="directory-card-copy"><strong>{serviceTitle(s.id,language)}</strong><small>{language==='en'?s.description:t.guide}</small><em className={s.source?'service-status service-status-link':'service-status service-status-preparation'}>{s.source?launchCopy[language].official:launchCopy[language].preparation}</em><em>{t.guide} · {language==='en'?s.category:categoryNames[s.category]?.[language==='hi'?0:1]}</em></span><ArrowRight size={20}/></a>})}</div>{!results.length&&<p role="status" className="directory-alert">{t.empty}<button onClick={()=>{setCategory('All');setQuery('');setVoiceSummary('')}}>{t.clear}</button></p>}</section>
 <section className="saathi-toolkit"><div className="directory-section-heading"><div><h2>{c.tools}</h2><p>{c.toolsIntro}</p></div><LockKeyhole size={26}/></div><div className="saathi-tool-grid">{familyShortcuts.map((item,i)=>{const Icon=[Users,HeartHandshake,FileCheck2,Bell,MessageCircle][i];return <a key={item.view} href={companionLink(item.view)}><Icon size={24}/><strong>{item.title[li]}</strong><small>{item.detail[li]}</small><ArrowRight size={18}/></a>})}</div></section>
 <section className="saathi-capabilities"><button onClick={()=>navigate(null,'live')}><Radio size={26}/><h2>{c.live}</h2><p>{c.liveInfo}</p><ArrowRight size={20}/></button><a href="/ruralos/tracking"><LockKeyhole size={26}/><h2>{c.private}</h2><p>{c.privateInfo}</p><ArrowRight size={20}/></a><a href="/ruralos/integrations/"><ShieldCheck size={26}/><h2>{c.status}</h2><p>{c.statusInfo}</p><span>{c.statusLink} →</span></a></section>
 <section className="saathi-improve"><div><MessageCircle size={28}/><h2>{c.learning}</h2><p>{c.learningInfo}</p></div><a className="directory-listen" href={companionLink('Help')}>{c.feedback}<ArrowRight size={18}/></a></section>
 </>:<><button className="directory-back" onClick={()=>navigate(null)}><ArrowLeft size={20}/>{t.home} · {t.all}</button><h1 className="directory-work-title" tabIndex={-1} ref={heading}>{selected?(['flight','rail','cab','holiday'].includes(selected)?['Travel planning','यात्रा की तैयारी','ప్రయాణ ప్రణాళిక'][li]:serviceTitle(selected,language)):mode==='live'?c.live:mode==='guide'?c.how:c.tools}</h1>{error&&<p role="alert" className="directory-alert">{error}</p>}<Suspense fallback={<p role="status">Opening your service…</p>}>{selected?(selected==='business'?<EnterpriseGuide language={language} offline={offline} onSpeak={s=>void speak(s)} onStop={()=>speech.current?.stop()}/>:['flight','rail','cab','holiday'].includes(selected)?<TravelPlanner key={selected} initialMode={selected as 'flight'|'rail'|'cab'|'holiday'} language={language} offline={offline}/>:<TaskAssistant key={selected} initialService={selected} initialLanguage={language} offline={offline} onLanguageChange={changeLanguage}/>):mode==='live'?<LiveHub initiallyOpen/>:mode==='guide'?<HowToGuide language={language} onSpeak={s=>void speak(s)} onStop={()=>speech.current?.stop()} onTry={()=>navigate('aadhaar')}/>:<FamilyApp/>}</Suspense></>}
 </main><footer className="directory-footer"><span><Sprout size={20}/>One family. One next step.</span><div><a href="/ruralos/integrations/">What is connected?</a><a href="https://rural-family-action-os.vjyrcks.chatgpt.site/privacy">Privacy</a><a href="https://rural-family-action-os.vjyrcks.chatgpt.site/support">Support</a></div><p>Independent early-access guidance · Not a government portal · Emergency calls go directly to the number; Saathi does not dispatch help.</p></footer></div>
}
