import React,{useState} from 'react';
import {compareEnteredQuotes,type EnteredQuote} from '../lib/fare-comparison';
import type {TravelDraft,TravelMode} from '../lib/travel-plan';
import type {DirectoryLanguage} from '../lib/service-directory';
import './service-preparation.css';
const copy={
 en:{title:'Compare the real cost of your options',intro:'Enter quotes you obtained from providers. This calculator does not fetch or verify fares. Use INR totals for all travellers, for the same journey.',cap:'Your budget per traveller',capNote:'This is a spending limit, not a fare estimate. Leave room for the other parts of your trip.',option:'Option',fare:'Fare including taxes · whole group (₹)',extras:'Baggage + other mandatory extras (₹)',transfer:'Airport/station/port transfers (₹)',zero:'Enter 0 when a cost does not apply. A blank means unknown.',basis:'I checked the same dates, route, travellers, baggage and cancellation conditions for these quotes.',total:'Total entered cost',person:'Per traveller',missing:'Incomplete: check every cost with the provider.',lower:'Lowest total among comparable options entered',over:'Above your total budget by',within:'Within your entered budget',noLive:'User-entered amounts · not live prices · availability not verified',check:'Before selecting an option',flight:['Use the provider’s month calendar, then confirm exact dates and the total at checkout.','Compare nearby airports only after adding transfers, baggage and overnight costs.','Check connection time, separate-ticket risk and cancellation terms.'],rail:['Compare the exact stations, train, date, class and quota.','Check seat status and cancellation rules; a search result is not a confirmed ticket.','Include travel to the station and any onward connection.'],cab:['Compare the same pickup, drop-off, vehicle capacity and pickup time.','Check tolls, parking, waiting, surge and cancellation charges.','Verify the provider’s driver and vehicle details before boarding.'],holiday:['Separate transport, accommodation, local transfers and activity costs.','Check room occupancy, meal inclusion and refund terms for the same dates.','Confirm each reservation; a plan does not reserve inventory.'],sea:['Check the operator, exact sailing, boarding port and cabin/seat category.','Ask about port fees, meals, baggage and cancellation or weather disruption.','Check arrival time, onward transport and any entry-document requirements.']},
 hi:{title:'यात्रा विकल्पों का पूरा खर्च तुलना करें',intro:'प्रदाता से मिले भाव डालें। यह कैलकुलेटर किराया खोजता या सत्यापित नहीं करता। उसी यात्रा के सभी यात्रियों का कुल खर्च रुपये में डालें।',cap:'प्रति यात्री आपका बजट',capNote:'यह खर्च की सीमा है, किराए का अनुमान नहीं। यात्रा के बाकी खर्चों के लिए भी पैसा रखें।',option:'विकल्प',fare:'कर सहित सभी यात्रियों का किराया (₹)',extras:'सामान और अन्य अनिवार्य खर्च (₹)',transfer:'हवाई अड्डे/स्टेशन/बंदरगाह तक खर्च (₹)',zero:'लागू नहीं हो तो 0 डालें। खाली का अर्थ अज्ञात है।',basis:'मैंने इन भावों की तारीख, रास्ता, यात्री, सामान और रद्द करने की शर्तें समान होने की जाँच की है।',total:'दर्ज कुल खर्च',person:'प्रति यात्री',missing:'अधूरा: हर खर्च प्रदाता से जाँचें।',lower:'दर्ज तुलनीय विकल्पों में सबसे कम कुल खर्च',over:'कुल बजट से इतना अधिक',within:'दर्ज बजट के अंदर',noLive:'आपके दर्ज भाव · लाइव किराया नहीं · उपलब्धता सत्यापित नहीं',check:'विकल्प चुनने से पहले · अंग्रेज़ी विवरण'},
 te:{title:'ప్రయాణ ఎంపికల పూర్తి ఖర్చు పోల్చండి',intro:'ప్రదాతల నుంచి పొందిన ధరలను నమోదు చేయండి. ఈ కాలిక్యులేటర్ ధరలను వెతకదు లేదా ధృవీకరించదు. ఒకే ప్రయాణానికి అందరు ప్రయాణికుల మొత్తం ఖర్చు రూపాయల్లో నమోదు చేయండి.',cap:'ఒక్కో ప్రయాణికుడికి మీ బడ్జెట్',capNote:'ఇది ఖర్చు పరిమితి, టికెట్ ధర అంచనా కాదు. ప్రయాణంలోని ఇతర ఖర్చులకు కూడా డబ్బు ఉంచండి.',option:'ఎంపిక',fare:'పన్నులతో అందరి ప్రయాణ ఖర్చు (₹)',extras:'బ్యాగేజీ మరియు ఇతర తప్పనిసరి ఖర్చులు (₹)',transfer:'విమానాశ్రయం/స్టేషన్/పోర్టు రవాణా (₹)',zero:'వర్తించకపోతే 0 నమోదు చేయండి. ఖాళీ అంటే తెలియదు.',basis:'ఈ ధరలకు తేదీలు, మార్గం, ప్రయాణికులు, బ్యాగేజీ, రద్దు షరతులు ఒకటే అని తనిఖీ చేశాను.',total:'నమోదు చేసిన మొత్తం ఖర్చు',person:'ఒక్కో ప్రయాణికుడికి',missing:'అసంపూర్ణం: ప్రతి ఖర్చును ప్రదాతతో తనిఖీ చేయండి.',lower:'నమోదు చేసిన పోల్చదగిన ఎంపికల్లో తక్కువ మొత్తం',over:'మొత్తం బడ్జెట్ కంటే అధికం',within:'నమోదు చేసిన బడ్జెట్ లోపల',noLive:'మీరు నమోదు చేసిన ధరలు · లైవ్ ధరలు కాదు · లభ్యత ధృవీకరించలేదు',check:'ఎంపికకు ముందు · ఆంగ్ల వివరాలు'}
};
const empty=():EnteredQuote=>({fare:'',extras:'',transfer:''});
export default function TravelComparison({plan,mode,language}:{plan:TravelDraft;mode:TravelMode;language:DirectoryLanguage}){
 const [quotes,setQuotes]=useState([empty(),empty(),empty()]),[same,setSame]=useState(false),c=copy[language];
 const result=compareEnteredQuotes(quotes,Number(plan.travellers),plan.budget,same),money=(paise:number)=>new Intl.NumberFormat(language==='hi'?'hi-IN':language==='te'?'te-IN':'en-IN',{style:'currency',currency:'INR'}).format(paise/100);
 function update(index:number,key:keyof EnteredQuote,value:string){setQuotes(old=>old.map((q,i)=>i===index?{...q,[key]:value}:q));setSame(false)}
 return <section className="service-preparation" aria-label={c.title}><h3>{c.title}</h3><p>{c.intro}</p>{result.budgetPerPerson!==null&&<div className="prep-next"><strong>{c.cap}: {money(result.budgetPerPerson)}</strong><p>{c.capNote}</p></div>}<h4>{c.check}</h4><ol className="quote-checklist" lang="en">{copy.en[mode].map(t=><li key={t}>{t}</li>)}</ol><p>{c.zero}</p><div className="quote-grid">{quotes.map((q,i)=><fieldset key={i}><legend>{c.option} {i+1}</legend>{(['fare','extras','transfer'] as const).map(key=><label key={key}>{c[key]}<input aria-label={`${c.option} ${i+1} · ${c[key]}`} inputMode="decimal" autoComplete="off" maxLength={10} value={q[key]} onChange={e=>update(i,key,e.target.value)}/></label>)}<div aria-live="polite">{result.rows[i]?<><p className="quote-result">{c.total}: {money(result.rows[i]!.total)}</p><p>{c.person}: {money(result.rows[i]!.perPerson)}</p>{result.rows[i]!.overBudget!==null&&<p>{result.rows[i]!.overBudget!>0?c.over+': '+money(result.rows[i]!.overBudget!):c.within}</p>}{result.lowest.includes(i)&&<strong>{c.lower}</strong>}</>:<p>{c.missing}</p>}</div></fieldset>)}</div><label className="quote-confirm"><input type="checkbox" checked={same} onChange={e=>setSame(e.target.checked)}/><span>{c.basis}</span></label><p className="prep-note">{c.noLive}</p></section>
}
