import React,{useEffect,useRef,useState} from 'react';
import {ArrowRight,CalendarDays,Plane,TrainFront,Car,Ship,Palmtree,Radio,Volume2,Mic,ShieldCheck} from 'lucide-react';
import {indiaToday,travelModes,travelHandoffs,validateTravel,travelWindow,type TravelMode,type TravelDraft} from '../lib/travel-plan';
import {travelCopy} from '../lib/travel-copy';
import type {DirectoryLanguage} from '../lib/service-directory';
import {createSpeechSession,type SpeechSession} from '../lib/speech-client';
import TravelComparison from './travel-comparison';
const blank:TravelDraft={origin:'',destination:'',when:'',travellers:'1',budget:''};
const icons=[Plane,TrainFront,Car,Palmtree,Ship];
export default function TravelPlanner({initialMode,language,offline}:{initialMode:TravelMode;language:DirectoryLanguage;offline:boolean}){
 const [mode,setMode]=useState(initialMode),[draft,setDraft]=useState<TravelDraft>({...blank}),[plan,setPlan]=useState<TravelDraft|null>(null),[range,setRange]=useState<{from:string;to:string}|null>(null),[error,setError]=useState(''),[consent,setConsent]=useState(false),[phase,setPhase]=useState('ready'),[voiceField,setVoiceField]=useState<'origin'|'destination'>('origin');
 const c=travelCopy[language],speech=useRef<SpeechSession|null>(null),reviewTitle=useRef<HTMLHeadingElement>(null),fromInput=useRef<HTMLInputElement>(null);
 useEffect(()=>{speech.current=createSpeechSession(setPhase,{en:'en-IN',hi:'hi-IN',te:'te-IN'}[language]);const hidden=()=>{if(document.hidden)speech.current?.stop()};document.addEventListener('visibilitychange',hidden);return()=>{speech.current?.stop();document.removeEventListener('visibilitychange',hidden)}},[language]);
 useEffect(()=>{if(plan)reviewTitle.current?.focus()},[plan]);
 function update(key:keyof TravelDraft,value:string){setDraft(old=>({...old,[key]:value}));setError('')}
 function choose(next:TravelMode){speech.current?.stop();setMode(next);setPlan(null);setDraft(old=>({...old,when:''}));setError('')}
 async function read(){try{setError('');await speech.current?.speak(c.intro+'. '+c.notConnected+'. '+c.privacy,.9)}catch{setError(c.voiceError)}}
 async function listen(){if(!consent||phase!=='ready')return;try{setError('');const text=await speech.current!.listen();update(voiceField,text.slice(0,100))}catch{setError(c.voiceError)}}
 return <section className="travel-workspace" aria-label={c.title}>
  <header className="travel-heading"><div><p className="directory-eyebrow">{c.ready}</p><h2>{c.title}</h2><p>{c.intro}</p></div><CalendarDays size={38}/></header>
  <div className="travel-mode-bar" role="group" aria-label={c.title}>{travelModes.map((id,i)=>{const Icon=icons[i];return <button key={id} aria-pressed={mode===id} onClick={()=>choose(id)}><Icon size={22}/>{c.modes[i]}</button>})}</div>
  <div className="travel-connection" role="status"><ShieldCheck size={21}/><span>{c.notConnected}</span><a href="/ruralos/integrations/">{c.trackingStatus} →</a></div>
  <div className="travel-layout"><div className="travel-primary">
   {!plan?<form onSubmit={e=>{e.preventDefault();speech.current?.stop();try{const checked=validateTravel(mode,draft);setRange(mode==='cab'?null:travelWindow(checked.when));setPlan(checked);setError('')}catch{setError(c.error)}}}>
    <div className="travel-fields"><label>{c.from}<input ref={fromInput} value={draft.origin} onChange={e=>update('origin',e.target.value)} maxLength={100} autoComplete="off" required/></label><label>{c.to}<input value={draft.destination} onChange={e=>update('destination',e.target.value)} maxLength={100} autoComplete="off" required/></label><label>{mode==='cab'?c.date:c.month}<input type={mode==='cab'?'date':'month'} min={indiaToday().slice(0,mode==='cab'?10:7)} value={draft.when} onChange={e=>update('when',e.target.value)} required/></label><label>{c.people}<input inputMode="numeric" value={draft.travellers} maxLength={2} onChange={e=>update('travellers',e.target.value)} required/></label><label className="travel-wide">{c.budget}<input inputMode="numeric" value={draft.budget} maxLength={7} onChange={e=>update('budget',e.target.value)}/></label></div>
    <p className="travel-privacy">{c.privacy}</p><button className="directory-speak" type="submit">{c.review}<ArrowRight size={20}/></button>
    <details className="travel-voice"><summary>{c.voice}</summary><label className="directory-consent"><input type="checkbox" checked={consent} onChange={e=>{setConsent(e.target.checked);if(!e.target.checked)speech.current?.stop()}}/>{c.consent}</label><label>{c.field}<select value={voiceField} onChange={e=>{speech.current?.stop();setVoiceField(e.target.value as 'origin'|'destination')}}><option value="origin">{c.from}</option><option value="destination">{c.to}</option></select></label><button className="directory-listen" type="button" disabled={!consent||phase!=='ready'} onClick={()=>void listen()}><Mic size={18}/>{c.speak}</button></details>
   </form>:<div><p className="directory-eyebrow">{c.status}</p><h3 ref={reviewTitle} tabIndex={-1}>{plan.origin} <ArrowRight aria-label="to" size={22}/> {plan.destination}</h3><dl className="travel-summary"><dt>{mode==='cab'?c.date:c.month}</dt><dd>{plan.when}</dd>{range&&<><dt>{c.window}</dt><dd>{range.from} — {range.to}</dd></>}<dt>{c.people}</dt><dd>{plan.travellers}</dd>{plan.budget&&<><dt>{c.budget}</dt><dd>₹{Number(plan.budget).toLocaleString('en-IN')}<small>{c.cost}</small></dd></>}</dl><section className="travel-no-fares"><h4>{c.noFares}</h4><p>{c.why}</p></section><h4>{c.external}</h4><p>{c.handoff}</p><div className="travel-provider-actions">{travelHandoffs[mode].map(p=>offline?<button key={p.name} disabled>{p.name} · {c.offline}</button>:<a key={p.name} href={p.url} target="_blank" rel="noreferrer">{p.name}<ArrowRight size={18}/></a>)}</div>{mode==='sea'&&<p>{c.noSea}</p>}<p className="travel-privacy">{c.actual}</p><button className="directory-listen" onClick={()=>{setPlan(null);setTimeout(()=>fromInput.current?.focus(),0)}}>{c.edit}</button></div>}
   {plan&&<TravelComparison key={mode+JSON.stringify(plan)} plan={plan} mode={mode} language={language}/>}
   {error&&<p role="alert" className="task-voice-error">{error}</p>}<div className="travel-utility"><button className="directory-listen" onClick={()=>void read()}><Volume2 size={18}/>{c.listen}</button>{phase!=='ready'&&<button className="directory-listen" onClick={()=>speech.current?.stop()}>{c.stop}</button>}<button className="directory-listen" onClick={()=>{speech.current?.stop();setDraft({...blank});setPlan(null);setConsent(false);setError('')}}>{c.reset}</button></div>
  </div><aside className="travel-tracking"><Radio size={28}/><h3>{c.track}</h3><p>{c.trackNote}</p><a href={'/ruralos/?section=live&language='+language}>{c.track}<ArrowRight size={18}/></a><a href="/ruralos/tracking">{c.private}<ShieldCheck size={18}/></a></aside></div>
 </section>
}
