'use client';
import {useEffect,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogDescription,DialogTitle} from '@/components/ui/dialog';
import {Mic,Volume2,Pause,Play,RotateCcw,ArrowRight,ArrowLeft,ExternalLink,ShieldCheck} from 'lucide-react';
import {createSpeechSession,SpeechSession} from '@/lib/speech-client';
import {startVoice,voiceTurn,VoiceState} from '@/lib/voice-engine';
type Props={open:boolean;onClose:()=>void;region:string;onRegion:(region:string)=>void;signedIn:boolean;onSaveReminder:(title:string,due:string,id:string)=>Promise<boolean>};
export default function VoiceGuide({open,onClose,region,onRegion,signedIn,onSaveReminder}:Props){const[state,setState]=useState<VoiceState>(()=>startVoice(region));const[phase,setPhase]=useState<'ready'|'speaking'|'listening'>('ready');const[active,setActive]=useState(false);const[begun,setBegun]=useState(false);const[heard,setHeard]=useState('');const[error,setError]=useState('');const[rate,setRate]=useState(.88);const[working,setWorking]=useState(false);const engine=useRef<SpeechSession|null>(null);const current=useRef(state);const running=useRef(false);const generation=useRef(0);const speed=useRef(rate);const mounted=useRef(true);const reminderId=useRef('');const writeLock=useRef(false);
function update(s:VoiceState){current.current=s;setState(s);if(s.region!==region)onRegion(s.region)}
function halt(){generation.current++;running.current=false;setActive(false);engine.current?.stop()}
useEffect(()=>{mounted.current=true;engine.current=createSpeechSession(p=>{if(mounted.current)setPhase(p)});const hidden=()=>{if(document.hidden)halt()};document.addEventListener('visibilitychange',hidden);return()=>{mounted.current=false;generation.current++;running.current=false;engine.current?.stop();document.removeEventListener('visibilitychange',hidden)}},[]);
useEffect(()=>{if(open){const s=startVoice(region);current.current=s;setState(s);setHeard('');setError('');setBegun(false);reminderId.current=''}else halt()},[open]);
async function playAndListen(s:VoiceState,token:number){if(!running.current||token!==generation.current)return;try{await engine.current!.speak(s.prompt,speed.current);if(!running.current||token!==generation.current)return;if(s.paused||s.stage==='emergency'){halt();return}const text=await engine.current!.listen();if(!running.current||token!==generation.current)return;await respond(text,token)}catch(e:any){if(token!==generation.current||!mounted.current)return;running.current=false;setActive(false);setPhase('ready');setError(e.message==='cancelled'?'Voice guide paused.':e.message)}}
async function respond(text:string,token:number){if(writeLock.current||token!==generation.current)return;setHeard(text);setError('');if(/^(slower|speak slower)$/i.test(text.trim())){speed.current=Math.max(.6,speed.current-.1);setRate(speed.current);await playAndListen(current.current,token);return}const result=voiceTurn(current.current,text);update(result.state);if(result.effect==='pause'){halt();return}if(result.effect==='save_reminder'){if(!signedIn){const s={...result.state,prompt:'Please sign in to save this reminder. Tap Sign in on this screen. You can continue listening to public guidance without an account.'};update(s);running.current=false;setActive(false);try{await engine.current!.speak(s.prompt,speed.current)}catch{}return}writeLock.current=true;setWorking(true);reminderId.current||=crypto.randomUUID();try{const ok=await onSaveReminder(result.state.title!,result.state.due!,reminderId.current);const s={...result.state,stage:ok?'complete' as const:'reminder_confirm' as const,prompt:ok?'Your reminder is saved in Saathi. There is no text-message or background notification. Say start over for another service, or stop.':'The save was not confirmed. Your reminder is still here. Check your connection and say yes to retry.'};if(ok)reminderId.current='';update(s);writeLock.current=false;setWorking(false);if(running.current&&token===generation.current)await playAndListen(s,token)}finally{writeLock.current=false;setWorking(false)}return}if(result.state.stage==='reminder_title'||result.state.stage==='topic')reminderId.current='';await playAndListen(result.state,token)}
function begin(){if(current.current.paused)update({...current.current,paused:false,prompt:current.current.resumePrompt??current.current.prompt});setBegun(true);setError('');generation.current++;running.current=true;setActive(true);playAndListen(current.current,generation.current)}
async function reply(){setBegun(true);setError('');halt();const token=++generation.current;running.current=true;setActive(true);try{const text=await engine.current!.listen();if(token===generation.current)await respond(text,token)}catch(e:any){if(token===generation.current){setError(e.message);running.current=false;setActive(false);setPhase('ready')}}}
function command(text:string){if(working)return;halt();const token=++generation.current;running.current=true;setActive(true);setBegun(true);respond(text,token)}
function close(){halt();onClose()}
const choices=state.stage==='confirm'||state.stage==='age_confirm'||state.stage==='reminder_confirm'?['Yes','No']:state.stage==='bpl'?['Yes','No','Not sure']:state.stage==='region'?['Use current']:state.stage==='steps'?['Next','Back','Repeat']:state.stage==='pension_result'?['Next','Reminder']:state.stage==='complete'?['Start over','Reminder']:[];
return <Dialog open={open} onOpenChange={v=>{if(!v)close()}}><DialogContent className="dialog-body voice-dialog sm:max-w-xl"><DialogTitle className="voice-heading">Let’s talk, one step at a time.</DialogTitle><DialogDescription>Listen to a question. Say your answer. No typing is needed for this guide.</DialogDescription><div className="voice-session-status" role="status"><span className={'voice-orb '+phase}><Mic size={34}/></span><span>{working?'Saving your reminder…':phase==='listening'?'Listening to you…':phase==='speaking'?'Saathi is speaking…':active?'Getting ready…':'Microphone off'}</span></div><div className="spoken-prompt" aria-live="polite">{state.prompt}</div>{heard&&<p className="heard">You said: “{heard}”</p>}{error&&<p className="notice" role="alert">{error}</p>}{!begun?<><p className="voice-consent"><ShieldCheck size={19}/> Starting allows your browser or device speech provider to process audio for this session. Saathi does not store recordings or transcripts. Current guide language: English.</p><button className="primary voice-start" onClick={begin}><Play size={22}/> Start voice guide</button></>:<div className="row voice-controls"><button className="primary" disabled={working} onClick={reply}><Mic size={20}/> Speak reply</button><button className="outline row" disabled={working} onClick={()=>command('repeat')}><Volume2 size={18}/> Repeat</button><button className="outline row" disabled={working} onClick={()=>active?halt():begin()}>{active?<Pause size={18}/>:<Play size={18}/>} {active?'Pause':'Resume'}</button></div>}{choices.length>0&&<div className="row voice-choices">{choices.map(v=><button className="outline" key={v} disabled={working} onClick={()=>command(v)}>{v}</button>)}</div>}{state.link&&<a className="primary row" href={state.link} target={state.link.startsWith('tel:')?undefined:'_blank'} rel="noreferrer" onClick={halt}>{state.stage==='emergency'?'Call 112':'Open official service'} <ExternalLink size={18}/></a>}{!signedIn&&state.stage==='reminder_confirm'&&<a className="primary" href="/signin-with-chatgpt?return_to=/%3Fview%3DReminders" target="_top" onClick={halt}>Sign in to save reminders</a>}<div className="row" style={{justifyContent:'space-between'}}><button className="text-button" onClick={()=>command('start over')} disabled={!begun||working}><RotateCcw size={16}/> Start over</button><button className="text-button" onClick={()=>{speed.current=speed.current<=.65?.88:.65;setRate(speed.current)}}>{rate<=.65?'Normal speed':'Slower voice'}</button></div><p className="source">Say “next”, “repeat”, “back”, or “stop”. Spoken guidance works in supported browsers/devices. Official portals may still require forms, identity checks or a visit. Hindi and Telugu await validation.</p></DialogContent></Dialog>}
