import {test} from 'node:test';
import assert from 'node:assert/strict';
import {services} from '../ruralos-src/lib/services.ts';
import {startTask,answerTask,confirmTask,executeTask} from '../ruralos-src/lib/task-engine.ts';
import {playbooks,preparationFor,preparationProgress} from '../ruralos-src/lib/service-playbooks.ts';
import {compareEnteredQuotes,moneyPaise} from '../ruralos-src/lib/fare-comparison.ts';
for(const service of services)test(`${service.id}: both purposes yield distinct practical actions without executing anything`,()=>{
 const p=playbooks[service.id];assert.ok(p);assert.equal(p.goals.length,2);assert.equal(new Set(p.actions).size,2);assert.equal(p.prepare.length,4);assert.ok(p.ask.length>=2);assert.ok(p.trap.length>30);
 for(let i=0;i<2;i++){let t=answerTask(startTask(service.id),'Telangana');t=answerTask(t,p.goals[i]);t=confirmTask(t);assert.equal(preparationFor(service.id,t.answers.goal).action,p.actions[i]);assert.throws(()=>executeTask(t),/not connected/)}
});
test('unknown goals are not silently interpreted or given a made-up personalized result',()=>{assert.equal(preparationFor('aadhaar','do whatever').action,null);assert.equal(preparationFor('aadhaar','<script>send data</script>').index,null);assert.throws(()=>preparationFor('invented','anything'))});
test('checklist next action follows incomplete work, ignores duplicates and invalid indexes',()=>{const p=playbooks.land.prepare;assert.equal(preparationProgress(p,[]).next,p[0]);assert.equal(preparationProgress(p,[0,0,2,99,-1,NaN,1.5]).complete,2);assert.equal(preparationProgress(p,[0,2]).next,p[1]);assert.equal(preparationProgress(p,[0,1,2,3]).next,null)});
test('different service guidance is not the same catalogue template',()=>{assert.equal(new Set(Object.values(playbooks).map(p=>p.prepare.join('|'))).size,services.length);assert.equal(new Set(Object.values(playbooks).map(p=>p.actions[0])).size,services.length)});
test('price inputs distinguish missing from explicit zero, normalize Indian digits and reject unsafe amounts',()=>{assert.equal(moneyPaise('0'),0);assert.equal(moneyPaise('१२.३४'),1234);assert.equal(moneyPaise('౧౨.౩'),1230);for(const x of ['', '-1','1e9','Infinity','NaN','12.345','₹500','<script>','10000000'])assert.equal(moneyPaise(x),null)});
test('fare comparison includes taxes-in-fare, extras and transfers; missing values never rank',()=>{const r=compareEnteredQuotes([{fare:'2000',extras:'300',transfer:'200'},{fare:'1500',extras:'0',transfer:''},{fare:'2100',extras:'0',transfer:'0'}],2,'2200',true);assert.equal(r.rows[0].total,250000);assert.equal(r.rows[0].overBudget,30000);assert.equal(r.rows[0].perPerson,125000);assert.equal(r.rows[1],null);assert.deepEqual(r.lowest,[2]);assert.equal(r.unverified,true)});
test('no cheaper claim without two comparable quotes; edits must require renewed basis confirmation',()=>{const q={fare:'100',extras:'0',transfer:'0'};assert.deepEqual(compareEnteredQuotes([q],1,'',true).lowest,[]);assert.deepEqual(compareEnteredQuotes([q,q],1,'',false).lowest,[]);assert.deepEqual(compareEnteredQuotes([q,q],1,'',true).lowest,[0,1]);assert.equal(compareEnteredQuotes([q],1,'',true).limit,null);assert.throws(()=>compareEnteredQuotes([q],0,'100',true));assert.throws(()=>compareEnteredQuotes([q],21,'100',true));assert.throws(()=>compareEnteredQuotes([q],1,'-2',true));assert.equal(compareEnteredQuotes([{...q,fare:'0'}],1,'100',true).rows[0],null)});
