'use strict';
const strengths=['Teaching','Writing','Organizing','Technology','Design','Languages','Hands-on skills','Listening'];
const paths=[
{id:'digital',title:'Everyday digital helper',skills:['Technology','Listening'],mode:'local',audience:'People who need patient help using everyday devices.',offer:'A guided session on one task, such as video calls or organizing photos.',sample:'Make a simple illustrated guide to joining a video call.',ai:'Ask AI for a plain-language checklist. You demonstrate patiently and check the person can repeat the task. Never handle passwords or financial accounts.',proof:'Two people can complete the task independently and one requests another session.'},
{id:'learning',title:'Patient learning partner',skills:['Teaching','Listening','Languages'],mode:'either',audience:'Learners who need help with a subject you already know.',offer:'A focused practice session on one clearly defined topic.',sample:'Create a 20-minute practice lesson and three questions to check understanding.',ai:'Generate practice questions and explanations. You check accuracy, adapt the pace, and provide encouragement.',proof:'Two learners complete the practice and ask for another session.'},
{id:'admin',title:'Small-business organizer',skills:['Organizing','Technology'],mode:'either',audience:'Independent business owners losing time to scattered information.',offer:'One organized tracker for tasks, inventory, or appointments.',sample:'Build a simple task tracker with fictional sample data.',ai:'Draft a spreadsheet structure and step-by-step instructions. You confirm the workflow actually fits the business.',proof:'One owner uses the tracker for a week and can describe what became easier.'},
{id:'writing',title:'Clear-writing assistant',skills:['Writing','Languages'],mode:'online',audience:'Small businesses with confusing descriptions or customer instructions.',offer:'Rewrite one page so customers understand the service and next step.',sample:'Write a before-and-after example for a fictional business.',ai:'Draft alternatives and check readability. You verify every factual claim, preserve the owner’s voice, and remove exaggeration.',proof:'One business approves the sample and requests another page.'},
{id:'design',title:'Local design partner',skills:['Design','Writing'],mode:'either',audience:'Local shops and community groups with hard-to-read materials.',offer:'One clear, readable event flyer or service menu.',sample:'Make one fictional event flyer with clear date, location, and next action.',ai:'Explore layout and headline ideas. You verify details, check readability, and use images you have permission to use.',proof:'One organizer uses the design and asks about a future project.'},
{id:'language',title:'Conversation practice host',skills:['Languages','Teaching','Listening'],mode:'either',audience:'Adults practicing a language you speak confidently.',offer:'A structured conversation session around an everyday situation.',sample:'Prepare a conversation exercise for introductions or ordering food.',ai:'Suggest role-play scenarios and vocabulary. You check natural usage and help the learner practice aloud.',proof:'Two participants want to book a repeat practice session.'},
{id:'practical',title:'Practical skills guide',skills:['Hands-on skills','Teaching'],mode:'local',audience:'Beginners interested in a safe practical skill you already use.',offer:'A beginner session in a skill such as sewing or basic gardening.',sample:'Prepare a short demonstration and a materials checklist using items you already have.',ai:'Help organize your lesson and materials list. You verify safe methods and only teach within your competence.',proof:'Two people finish the activity and want to learn the next step.'},
{id:'software',title:'Software problem solver',skills:['Technology','Organizing'],mode:'online',audience:'Small teams with one repetitive or unreliable software workflow.',offer:'A focused review of one workflow with a prioritized improvement plan.',sample:'Demonstrate one small improvement using your own code and synthetic data.',ai:'Help inspect code and draft tests. You verify behavior, failure cases, permissions, and the actual improvement.',proof:'One team confirms the problem matters and agrees to a clearly scoped pilot.'},
{id:'community',title:'Community project helper',skills:['Organizing','Listening'],mode:'local',audience:'Community groups that need help coordinating a small activity.',offer:'Help organize one event checklist or volunteer schedule.',sample:'Create a simple fictional event checklist with owners and deadlines.',ai:'Draft checklists and reminder templates. You confirm the details and coordinate with the organizer.',proof:'One group uses your checklist and invites you to help again.'}
];
function recommend(input){
 if(!input||typeof input!=='object'||Object.keys(input).some(k=>!['skills','hours','setting','goal'].includes(k))||!Array.isArray(input.skills)||input.skills.length>3||new Set(input.skills).size!==input.skills.length||input.skills.some(s=>!strengths.includes(s))||![2,5,10].includes(input.hours)||!['either','online','local'].includes(input.setting)||!['income','confidence','community'].includes(input.goal))throw new Error('Choose up to three supported strengths and valid time, location, and goal options.');
 return paths.filter(p=>input.setting==='either'||p.mode==='either'||p.mode===input.setting).map((p,i)=>({path:p,score:p.skills.filter(s=>input.skills.includes(s)).length*3+(input.goal==='community'&&p.id==='community'?4:0)+(input.skills.length===0&&['digital','community','admin'].includes(p.id)?1:0),order:i})).sort((a,b)=>b.score-a.score||a.order-b.order).slice(0,3).map(x=>x.path);
}
let current={skills:[],hours:5,setting:'either',goal:'income'},selected=null,matches=[],done=new Set();
let experiments={};
function experimentKey(p=selected,input=current){return JSON.stringify([p.id,[...input.skills].sort(),input.hours,input.setting,input.goal]);}
function blankExperiment(){return {done:[],conversations:0,pilots:0,repeats:0,notes:''};}
function record(){const key=experimentKey();return experiments[key]||(experiments[key]=blankExperiment());}
const $=id=>document.getElementById(id);
function planFor(p,input){const outreach=input.hours===2?2:input.hours===5?5:8;return[
`Choose one specific task for ${p.audience.charAt(0).toLowerCase()+p.audience.slice(1)}`,
p.sample,
'Ask one trusted person to try your sample. Note what confused them and improve it.',
`Identify ${outreach} relevant people or organizations. Ask about this problem before offering your solution.`,
input.goal==='income'?'Describe a small pilot, delivery date, and fixed price. Ask if someone wants to buy it; do not promise results.':input.goal==='community'?'Offer one clearly bounded volunteer pilot to a community organization. Agree on what is needed.':'Arrange one practice pilot and agree on the feedback you want.',
'Deliver only the agreed task. Check the result with the person you helped.',
'Write down what worked, time spent, feedback, and any costs or payments. Repeat, adjust, or stop based on that evidence.'
];}
function renderPlan(p){selected=p;done=new Set(record().done);$('plan-title').textContent=p.title;$('plan-intro').textContent=`Your first offer: ${p.offer} Budget about ${Math.floor(current.hours*60/7)} minutes a day. The schedule is a guide, not a deadline.`;$('ai-help').textContent=p.ai;$('prompt').textContent=`Help me prepare this small service: ${p.offer} My strengths are ${current.skills.join(', ')||'still developing'}. I have ${current.hours} hours this week. Suggest a simple sample, three customer discovery questions, and a quality checklist. Label assumptions and do not invent demand or income figures.`;$('signal').textContent=p.proof;$('days').replaceChildren();planFor(p,current).forEach((task,i)=>{const label=document.createElement('label');label.className='day';const cb=document.createElement('input');cb.type='checkbox';cb.checked=done.has(i);cb.setAttribute('aria-label',`Complete day ${i+1}: ${task}`);cb.addEventListener('change',()=>{cb.checked?done.add(i):done.delete(i);record().done=[...done];updateProgress();});const span=document.createElement('span');const title=document.createElement('strong');title.textContent=`DAY ${i+1}`;span.append(title,document.createTextNode(task));label.append(cb,span);$('days').append(label);});updateProgress();renderEvidence();document.querySelectorAll('.opportunity').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.id===p.id)));}
function updateProgress(){$('progress-label').textContent=`${done.size} of 7 done`;$('progress-bar').style.width=`${done.size/7*100}%`;}
function generate(input){const next=recommend(input);current={...input,skills:[...input.skills]};matches=next;$('opportunities').replaceChildren();matches.forEach((p,i)=>{const button=document.createElement('button');button.type='button';button.className='opportunity';button.dataset.id=p.id;button.setAttribute('aria-pressed','false');const top=document.createElement('span');top.className='card-number';top.textContent=`0${i+1}`;const tag=document.createElement('b');tag.textContent=i===0?'START HERE':'ANOTHER PATH';top.append(tag);const title=document.createElement('h3');title.textContent=p.title;const description=document.createElement('p');description.textContent=p.audience;const foot=document.createElement('span');foot.className='card-foot';foot.textContent=`${p.mode==='either'?'Online or local':p.mode==='online'?'Online':'In your community'} · View plan ↗`;button.append(top,title,description,foot);button.addEventListener('click',()=>renderPlan(p));$('opportunities').append(button);});$('summary').textContent=current.skills.length?`Based on ${current.skills.join(', ').toLowerCase()} · ${current.hours} hours/week. Ideas to test, not confirmed demand.`:`Beginner-friendly ideas · ${current.hours} hours/week. Pick one that feels achievable.`;$('match-label').textContent=current.skills.length?'YOUR SHORTLIST':'STARTER IDEAS';renderPlan(matches[0]);return{opportunities:matches.map(p=>({id:p.id,title:p.title})),selected:selected.id,plan:planFor(selected,current)};}
strengths.forEach(s=>{const label=document.createElement('label');label.className='skill';const input=document.createElement('input');input.type='checkbox';input.value=s;input.name='strength';input.addEventListener('change',()=>{if(document.querySelectorAll('[name=strength]:checked').length>3){input.checked=false;$('form-status').textContent='Choose up to 3 strengths. Uncheck one to change your selection.';}else $('form-status').textContent='Ready when you are. Find your next step below.';});const text=document.createElement('span');text.textContent=s;label.append(input,text);$('skills').append(label);});
$('profile').addEventListener('submit',event=>{event.preventDefault();generate({skills:[...document.querySelectorAll('[name=strength]:checked')].map(x=>x.value),hours:Number($('hours').value),setting:$('setting').value,goal:$('goal').value});$('form-status').textContent='Your shortlist and plan are ready. Progress stays with each path and profile during this visit. Download to keep it.';if(matchMedia('(max-width:700px)').matches)$('opportunities').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});});
initializePlan();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'generate_opportunity_plan',description:'Update the visible opportunity shortlist and seven-day plan. Restores progress for the same path and profile during this visit.',inputSchema:{type:'object',properties:{skills:{type:'array',items:{type:'string',enum:strengths},maxItems:3,uniqueItems:true},hours:{type:'integer',enum:[2,5,10]},setting:{type:'string',enum:['either','online','local']},goal:{type:'string',enum:['income','confidence','community']}},required:['skills','hours','setting','goal'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){recommend(input);document.querySelectorAll('[name=strength]').forEach(el=>{el.checked=input.skills.includes(el.value);});$('hours').value=String(input.hours);$('setting').value=input.setting;$('goal').value=input.goal;return generate(input);}})).catch(()=>{});}catch{}}

function evidenceMessage(e){
 if(e.repeats>0&&e.pilots===0)return 'You recorded a repeat request without a completed pilot. Check the counts before drawing a conclusion.';
 if(e.repeats>0)return 'A repeat request is a useful signal. Ask what worked, review your time and costs, and test the offer again. It is not proof of a scalable business.';
 if(e.pilots>0)return 'You have delivery experience to learn from. Ask what improved and whether the person would use the service again.';
 if(e.conversations>=5)return 'You have several conversations to review. Look for a repeated problem and an explicit commitment before expanding the idea.';
 return 'Start with one real conversation. Ask what is difficult, how it is handled today, and what a useful improvement would look like.';
}
function renderEvidence(){const e=record();for(const id of ['conversations','pilots','repeats','notes'])$(id).value=e[id];for(const id of ['conversations','pilots','repeats'])$(id).setCustomValidity('');$('experiment-verdict').textContent=evidenceMessage(e);}
function planText(){const e=record();return ['NEXTSTEP — '+selected.title,'',`Strengths: ${current.skills.join(', ')||'Exploring'}`,`Time: ${current.hours} hours/week`, `Goal: ${current.goal}`,`First offer: ${selected.offer}`,'',...planFor(selected,current).map((t,i)=>`${e.done.includes(i)?'[x]':'[ ]'} Day ${i+1}: ${t}`),'','AI support: '+selected.ai,'Prompt: '+$('prompt').textContent,'','Evidence to look for: '+selected.proof,`Conversations: ${e.conversations}; pilots: ${e.pilots}; repeat requests: ${e.repeats}`,'Notes: '+e.notes,'','Curated ideas, not verified demand or an income guarantee.'].join('\n');}
function snapshot(){return {format:'nextstep-plan',version:1,profile:current,path:selected.id,experiment:{...record(),done:[...record().done]},readablePlan:planText()};}
function validateSnapshot(data){if(!data||data.format!=='nextstep-plan'||data.version!==1)throw new Error('Choose a NextStep plan file downloaded from this app.');recommend(data.profile);if(!recommend(data.profile).some(p=>p.id===data.path))throw new Error('The saved path does not match this profile.');const e=data.experiment;if(!e||!Array.isArray(e.done)||e.done.length>7||new Set(e.done).size!==e.done.length||e.done.some(i=>!Number.isInteger(i)||i<0||i>6)||typeof e.notes!=='string'||e.notes.length>4000||['conversations','pilots','repeats'].some(k=>!Number.isInteger(e[k])||e[k]<0||e[k]>100000))throw new Error('This plan has invalid progress or notes. Your current plan has not changed.');return {profile:{skills:[...data.profile.skills],hours:data.profile.hours,setting:data.profile.setting,goal:data.profile.goal},path:data.path,experiment:{done:[...e.done],conversations:e.conversations,pilots:e.pilots,repeats:e.repeats,notes:e.notes}};}
function applyProfile(input){document.querySelectorAll('[name=strength]').forEach(el=>{el.checked=input.skills.includes(el.value);});$('hours').value=String(input.hours);$('setting').value=input.setting;$('goal').value=input.goal;}
async function copyText(text,status){try{await navigator.clipboard.writeText(text);$(status).textContent='Copied. Ready to paste.';}catch{$(status).textContent='Clipboard is unavailable. Select and copy the text or address manually.';}}
function initializePlan(){
 generate(current);
 for(const id of ['conversations','pilots','repeats'])$(id).addEventListener('input',()=>{const n=Number($(id).value);if($(id).value===''||!Number.isInteger(n)||n<0||n>100000){$(id).setCustomValidity('Enter a whole number from 0 to 100,000.');$('experiment-verdict').textContent='Please enter valid whole-number totals. The last valid totals remain in your download.';return;}$(id).setCustomValidity('');record()[id]=n;$('experiment-verdict').textContent=evidenceMessage(record());});
 $('notes').addEventListener('input',()=>{record().notes=$('notes').value.slice(0,4000);});
 $('download-plan').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(snapshot(),null,2)],{type:'application/json'}),href=URL.createObjectURL(blob),a=document.createElement('a');a.href=href;a.download='nextstep-'+selected.id+'-plan.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(href),1000);$('save-status').textContent='Download started. Keep this file and reopen it here to resume your plan.';});
 $('open-plan').addEventListener('click',()=>$('plan-file').click());
 $('plan-file').addEventListener('change',async()=>{const file=$('plan-file').files[0];if(!file)return;try{if(file.size>100000)throw new Error('This file is too large. Choose a NextStep plan under 100 KB.');const data=validateSnapshot(JSON.parse(await file.text()));const p=paths.find(p=>p.id===data.path);experiments[experimentKey(p,data.profile)]=data.experiment;applyProfile(data.profile);generate(data.profile);renderPlan(p);$('save-status').textContent='Plan restored. Download again after making changes.';}catch(e){$('save-status').textContent=e instanceof SyntaxError?'This is not a valid JSON plan. Your current plan has not changed.':e.message;}$('plan-file').value='';});
 $('copy-prompt').addEventListener('click',()=>copyText($('prompt').textContent,'save-status'));
 window.addEventListener('beforeprint',()=>{$('print-notes').textContent=record().notes||'No notes recorded.';});$('print-plan').addEventListener('click',()=>window.print());
 const url='https://celesys.ai/nextstep/',message='Turn your everyday skills into a useful service idea and a seven-day experiment. Try NextStep: '+url;
 $('share-copy').addEventListener('click',()=>copyText(url,'share-status'));
 $('share-linkedin').href='https://www.linkedin.com/sharing/share-offsite/?url='+encodeURIComponent(url);
 $('share-whatsapp').href='https://wa.me/?text='+encodeURIComponent(message);
 $('share-x').href='https://twitter.com/intent/tweet?text='+encodeURIComponent(message);
}
