export type MobileAccess='yes'|'no'|'first'|'unknown';
export type AppNumber='same'|'different'|'unknown';
export const mobileSource='https://uidai.gov.in/hi/aadhaar-app-faq';
export const mobileChecked='2026-09-28';
export const mobileReviewBy='2026-10-28T00:00:00Z';
export function mobileRoute(access:MobileAccess,app:AppNumber,now=Date.now()){
 if(!Number.isFinite(now)||now>=Date.parse(mobileReviewBy))return 'review';
 if(access==='no'||access==='first')return 'centre';
 if(access!=='yes')return 'unknown';
 return app==='same'?'same':app==='different'?'different':'unknown';
}
// Concise UIDAI mobile-update scenarios; no identity data collected.
export const mobileCopy={
 en:{title:'Changing your Aadhaar mobile number?',access:'Can you access the number currently registered with Aadhaar?',choices:['Yes','No','First registration','Not sure'],app:'Does the Aadhaar app use that same number?',appChoices:['Same number','Different number','Not sure / not set up'],same:'In UIDAI’s Aadhaar app: verify the new number by OTP, complete face authentication and pay the displayed charge.',different:'In UIDAI’s Aadhaar app: verify both old and new numbers by OTP, complete face authentication and pay the displayed charge.',centre:'Visit an authorised Aadhaar enrolment/update centre if the old number is unavailable or this is first registration.',unknown:'Confirm your situation with UIDAI before choosing a route.',review:'This guidance needs review. Check UIDAI for current instructions.',source:'Read UIDAI instructions',listen:'Listen to my route',stop:'Stop',note:'Use only the official app or centre. Never enter identity numbers or OTPs here.',reviewLabel:'India · Source checked',audio:'Voice unavailable. Read the route or open UIDAI.'},
 hi:{title:'आधार का मोबाइल नंबर बदलना है?',access:'क्या आधार में दर्ज नंबर आपके पास चालू है?',choices:['हाँ','नहीं','पहली बार दर्ज करना है','पता नहीं'],app:'क्या आधार ऐप में वही नंबर है?',appChoices:['वही नंबर','अलग नंबर','पता नहीं / ऐप नहीं'],same:'UIDAI आधार ऐप में नए नंबर का OTP, चेहरा सत्यापन और दिखाया गया शुल्क पूरा करें।',different:'UIDAI आधार ऐप में पुराने और नए दोनों नंबरों का OTP, चेहरा सत्यापन और दिखाया गया शुल्क पूरा करें।',centre:'पुराना नंबर नहीं है या पहली बार दर्ज करना है तो अधिकृत आधार केन्द्र जाएँ।',unknown:'रास्ता चुनने से पहले UIDAI से स्थिति पक्की करें।',review:'इस मार्गदर्शन की समीक्षा चाहिए। वर्तमान निर्देश UIDAI पर देखें।',source:'UIDAI के निर्देश पढ़ें',listen:'अपना रास्ता सुनें',stop:'रोकें',note:'केवल आधिकारिक ऐप या केन्द्र इस्तेमाल करें। यहाँ पहचान नंबर या OTP न दें।',reviewLabel:'भारत · स्रोत जाँचा',audio:'आवाज़ उपलब्ध नहीं। निर्देश पढ़ें या UIDAI खोलें।'},
 te:{title:'ఆధార్ మొబైల్ నంబరు మార్చాలా?',access:'ఆధార్‌లో నమోదైన నంబరు మీ వద్ద పనిచేస్తుందా?',choices:['అవును','లేదు','మొదటిసారి నమోదు','తెలియదు'],app:'ఆధార్ యాప్‌లో అదే నంబరా?',appChoices:['అదే నంబరు','వేరే నంబరు','తెలియదు / యాప్ లేదు'],same:'UIDAI ఆధార్ యాప్‌లో కొత్త నంబరు OTP, ముఖ ధ్రువీకరణ, చూపిన రుసుము పూర్తి చేయండి.',different:'UIDAI ఆధార్ యాప్‌లో పాత, కొత్త నంబర్ల OTPలు, ముఖ ధ్రువీకరణ, చూపిన రుసుము పూర్తి చేయండి.',centre:'పాత నంబరు అందుబాటులో లేకపోయినా మొదటిసారి నమోదైనా అధీకృత ఆధార్ కేంద్రానికి వెళ్లండి.',unknown:'మార్గం ఎంచుకునే ముందు UIDAIతో పరిస్థితి నిర్ధారించండి.',review:'ఈ మార్గదర్శకానికి సమీక్ష అవసరం. ప్రస్తుత సూచనలు UIDAIలో చూడండి.',source:'UIDAI సూచనలు చదవండి',listen:'నా మార్గం వినండి',stop:'ఆపండి',note:'అధికారిక యాప్ లేదా కేంద్రం మాత్రమే వాడండి. ఇక్కడ గుర్తింపు నంబర్లు, OTPలు ఇవ్వవద్దు.',reviewLabel:'భారతదేశం · మూలం తనిఖీ',audio:'వాయిస్ అందుబాటులో లేదు. సూచనలు చదవండి లేదా UIDAI తెరవండి.'}
};
