import {regions} from './regions.ts';
export const caseReviewed='2026-09-29';
export const caseReviewDue='2026-10-13T00:00:00Z';
export const caseSources={pmkisan:'https://pmkisan.gov.in/',status:'https://pmkisan.gov.in/BeneficiaryStatus_New.aspx',pib:'https://www.pib.gov.in/PressReleasePage.aspx?PRID=2152566',grievance:'https://pgportal.gov.in/',faq:'https://pgportal.gov.in/Home/Faq'} as const;
export const farmChoices=['unknown','ekyc','land','bank','paid','pending'] as const;
export type FarmChoice=typeof farmChoices[number];
export const farmLabels:Record<FarmChoice,string>={unknown:'I have not checked / cannot understand the status',ekyc:'eKYC is incomplete',land:'Land verification / seeding is incomplete',bank:'Bank or Aadhaar-payment problem is shown',paid:'Portal says paid, but I cannot find the credit',pending:'No payment yet; the reason is unclear'};
export type CaseInput={kind:'farm'|'grievance';region:string;issue:FarmChoice|'delay'|'incorrect'|'unavailable'|'excluded';summary:string;remedy:string};
export type CasePlan={title:string;next:string;why:string;evidence:string[];draft:string;route:string;source:string;followup:string;trace:string[];blocked:boolean};
export function rulesCurrent(now=Date.now()){return Number.isFinite(now)&&now>=Date.parse(caseReviewed)&&now<Date.parse(caseReviewDue)}
export function safeCaseText(value:unknown,min=0){if(typeof value!=='string'||value.trim().length<min||value.length>1200)throw Error('Use a short factual description (up to 1,200 characters).');const t=value.normalize('NFKC').trim();if(/[<>\u0000-\u0008\u000b-\u001f]/u.test(t)||/(?:\p{N}[\s-]*){6,}/u.test(t)||/[\w.+-]+@[\w.-]+\.[a-z]{2,}/iu.test(t)||/\b(?:otp|pin|password|aadhaar|aadhar|account number)\s*[:=]?\s*\p{N}/iu.test(t))throw Error('Remove identity numbers, phone numbers, email, PINs and OTPs. Add private details only on the official portal.');return t}
export function makeCase(input:CaseInput,now=Date.now()):CasePlan{
 if(!rulesCurrent(now))throw Error('Guidance needs a source review. Use the official source; no new action pack can be prepared.');
 if(!(regions as readonly string[]).includes(input.region))throw Error('Choose a valid State or Union Territory.');
 if(!['farm','grievance'].includes(input.kind))throw Error('Unknown service.');
 const summary=safeCaseText(input.summary,input.kind==='grievance'?20:0),remedy=safeCaseText(input.remedy,input.kind==='grievance'?10:0);
 const trace=['Checked service and region','Rejected unsafe or incomplete input','Used reviewed national guidance','Prepared draft for your review; nothing submitted'];
 if(input.kind==='farm'){
  if(!farmChoices.includes(input.issue as FarmChoice))throw Error('Choose the status you actually saw.');
  const issue=input.issue as FarmChoice;
  const actions:Record<FarmChoice,[string,string,string[]]>={
   unknown:['Check Know Your Status first. Keep registration details and OTP entry on the official portal. Return and select the message actually shown.','No cause has been established. This assistant has not read your PM-KISAN record.',['Access to your registered phone, kept privately','Your registration details on the official portal only']],
   ekyc:['Use the PM-KISAN portal’s eKYC instructions or official assistance route. After completion, check that the status changes.','The Ministry identifies eKYC as a required verification. Your selection is not proof that it caused the missing payment.',['The eKYC message you saw','Any official completion acknowledgement, kept privately']],
   land:['Ask the responsible State/UT PM-KISAN agriculture office to check the land verification entry and explain the correction required.','State/UT data verification and correction are part of the scheme; this assistant cannot verify title or eligibility.',['The portal’s land-verification message','Relevant land records for the official, kept privately','Previous correction acknowledgement, if any']],
   bank:['Ask your bank to verify the Aadhaar-based payment mapping and account status against the failure shown. Keep bank details out of this app.','The Ministry lists mapping changes, missing mapping and closed accounts among failed-payment causes. Your bank must identify the actual cause.',['The exact payment failure message','Account statement and transaction reference for the bank only','Bank complaint acknowledgement, if one exists']],
   paid:['Compare the portal’s bank, credit date and transaction reference with the bank statement; ask the bank to trace the stated transaction.','A displayed payment and a missing visible credit need reconciliation. Do not assume theft or create a duplicate application.',['Credit date and transaction reference, kept privately','Statement covering that date','Bank response or trace reference']],
   pending:['Check the latest official status and ask the PM-KISAN help route which verification or payment step is pending.','No release date or entitlement can be inferred from an unexplained delay.',['The current status and date checked','Previous help request and reply, if any','The instalment period you are asking about']]};
  const [next,why,evidence]=actions[issue];
  const draft=['DRAFT — REVIEW BEFORE USE; NOT SUBMITTED','Subject: Request to clarify PM-KISAN payment status',`State/UT: ${input.region}`,`Status category selected by me: ${farmLabels[issue]}.`,summary?`Additional facts supplied by me: ${summary}`:'', 'Please check my official record, identify the pending requirement or payment issue, and explain the corrective action and follow-up route. I will provide my registration/reference details only through your official secure channel.','This draft does not establish eligibility or a payment entitlement.'].filter(Boolean).join('\n\n');
  return {title:'PM-KISAN payment action pack',next,why,evidence,draft,route:issue==='unknown'?caseSources.status:caseSources.pmkisan,source:caseSources.pib,followup:'After the official or bank response, check whether the recorded issue changed. Keep the acknowledgement privately. Escalate with the existing reference rather than repeating an application.',trace,blocked:false};
 }
 if(!['delay','incorrect','unavailable','excluded'].includes(input.issue))throw Error('Choose a complaint category.');
 if(input.issue==='excluded')return {title:'Use the appropriate specialist route',next:'CPGRAMS does not handle RTI matters, court/subjudice matters or personal/family disputes. Consult the relevant official or qualified adviser for that route.',why:'An ordinary government-service grievance draft is not appropriate for the category you selected.',evidence:[],draft:'',route:caseSources.faq,source:caseSources.faq,followup:'Do not wait on this app if a legal or appeal deadline applies.',trace:[...trace,'Stopped: excluded category'],blocked:true};
 return {title:'Government-service complaint pack',next:'Review the draft, then sign in to CPGRAMS and select the responsible department. Add identity details and evidence only there. Submit yourself and keep the acknowledgement.',why:'CPGRAMS routes government-service grievances to the responsible authority. The portal decides handling; this app has not filed a complaint.',evidence:['Earlier request acknowledgement, if available','Relevant official reply or error','Dated evidence of the service problem','The specific remedy you want'],draft:['DRAFT — REVIEW BEFORE USE; NOT SUBMITTED','Subject: Request for resolution of a government-service problem',`State/UT: ${input.region}`,`Issue type: ${input.issue}`,`Facts supplied by me:\n${summary}`,`Resolution requested by me:\n${remedy}`,'Please examine the issue, provide a reasoned response and explain any action or evidence needed from me. I will attach supporting records and identity details through the official portal.'].join('\n\n'),route:caseSources.grievance,source:caseSources.faq,followup:'Track the acknowledgement through CPGRAMS View Status. If a Central Ministry/Department disposes the case unsatisfactorily, check the portal’s feedback/appeal route promptly. Applicable appeal timing must be checked on the official portal; a personal reminder does not extend it.',trace,blocked:false};
}
export function casePack(plan:CasePlan){if(plan.blocked||!plan.draft)throw Error('No draft for this category.');return [plan.title,plan.draft,'NEXT ACTION\n'+plan.next,'WHY\n'+plan.why,'EVIDENCE TO PREPARE PRIVATELY\n'+plan.evidence.map(x=>'• '+x).join('\n'),'FOLLOW UP\n'+plan.followup,`Official route: ${plan.route}\nSource: ${plan.source}\nNational guidance reviewed ${caseReviewed}; review due ${caseReviewDue.slice(0,10)}.`, 'No government submission, account lookup or guaranteed outcome occurred.'].join('\n\n')}
export function followupCalendar(date:string,now=Date.now()){
 if(!Number.isFinite(now)||!/^\d{4}-\d{2}-\d{2}$/.test(date))throw Error('Choose a valid follow-up date.');
 const d=new Date(date+'T00:00:00Z');if(!Number.isFinite(d.getTime())||d.toISOString().slice(0,10)!==date||d.getTime()<Math.floor(now/86400000)*86400000||d.getTime()>now+366*86400000)throw Error('Choose today or a date within the next year.');
 const stamp=new Date(now).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');
 return ['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Saathi//Private follow-up//EN','BEGIN:VEVENT',`UID:saathi-${date}-${Math.floor(now)}@celesys.ai`,`DTSTAMP:${stamp}`,`DTSTART;VALUE=DATE:${date.replaceAll('-','')}`,`DTEND;VALUE=DATE:${new Date(d.getTime()+86400000).toISOString().slice(0,10).replaceAll('-','')}`,'SUMMARY:Review your saved action plan','DESCRIPTION:Check the official response privately. This is a personal reminder\, not an official deadline.','END:VEVENT','END:VCALENDAR',''].join('\r\n');
}
