// Reviewed central-programme information. Discovery filters are not eligibility decisions.
export type Lang='en'|'hi'|'te';
export const reviewed='2026-09-28';
export const reviewBy='2026-10-12T00:00:00Z';
export const L=(en:string,hi:string,te:string)=>({en,hi,te});
export const goals=[
 {id:'start',label:L('Start a small business','छोटा व्यवसाय शुरू करें','చిన్న వ్యాపారం ప్రారంభించండి')},
 {id:'grow',label:L('Grow an existing business','चलता व्यवसाय बढ़ाएँ','ప్రస్తుత వ్యాపారం పెంచండి')},
 {id:'craft',label:L('Artisan or craft work','कारीगर या हस्तकला','చేతివృత్తి లేదా హస్తకళ')},
 {id:'innovation',label:L('Innovative startup','नवाचार वाला स्टार्टअप','వినూత్న స్టార్టప్')},
 {id:'learn',label:L('Learn before investing','पैसा लगाने से पहले सीखें','పెట్టుబడి ముందు నేర్చుకోండి')}
];
export const programmes=[
 {id:'mudra',name:'PM MUDRA / PMMY',goals:['start','grow'],type:L('Repayable loan','चुकाने वाला ऋण','తిరిగి చెల్లించాల్సిన రుణం'),url:'https://financialservices.gov.in/pradhan-mantri-mudra-yojana-pmmy',source:'Department of Financial Services',
 benefit:L('Shishu: up to ₹50,000; Kishore: above ₹50,000–₹5 lakh; Tarun: above ₹5–₹10 lakh. Tarun Plus: above ₹10–₹20 lakh only after successfully repaying a previous Tarun loan.','शिशु: ₹50,000 तक; किशोर: ₹50,000 से अधिक–₹5 लाख; तरुण: ₹5 लाख से अधिक और ₹10 लाख तक। तरुण प्लस: ₹10–₹20 लाख, केवल पिछला तरुण ऋण सफलतापूर्वक चुकाने पर।','శిశు: ₹50,000 వరకు; కిశోర్: ₹50,000 కంటే ఎక్కువ–₹5 లక్షలు; తరుణ్: ₹5 లక్షలకు పైగా–₹10 లక్షలు. తరుణ్ ప్లస్: గత తరుణ్ రుణం విజయవంతంగా చెల్లించిన వారికి మాత్రమే ₹10 లక్షలకు పైగా–₹20 లక్షలు.'),
 fit:L('Micro-enterprise term loans or working capital, including eligible dairy, poultry and beekeeping activities. Not a general personal-spending grant.','सूक्ष्म व्यवसाय के निवेश या कामकाजी पूँजी के लिए; पात्र डेयरी, मुर्गीपालन, मधुमक्खीपालन भी। निजी खर्च का अनुदान नहीं।','సూక్ష్మ వ్యాపార పెట్టుబడి లేదా నిర్వహణ మూలధనం; అర్హమైన పాడి, కోళ్ల, తేనెటీగల వ్యాపారాలు కూడా. వ్యక్తిగత ఖర్చులకు గ్రాంటు కాదు.'),
 next:L('Take your cost estimate and expected monthly sales to a participating bank or lender. Ask for the appropriate category and written repayment terms.','लागत और अनुमानित मासिक बिक्री लेकर भागीदार बैंक जाएँ। सही श्रेणी और लिखित भुगतान शर्तें पूछें।','ఖర్చు అంచనా, నెలవారీ అమ్మకాల అంచనాతో భాగస్వామి బ్యాంకును సంప్రదించండి. సరైన కేటగిరీ, రాతపూర్వక చెల్లింపు షరతులు అడగండి.'),
 caution:L('Collateral-free does not mean automatic approval, no repayment, or a fixed cheap rate. Compare the lender’s interest, fees and total repayment.','बिना जमानत का अर्थ पक्की मंज़ूरी, माफी या तय सस्ता ब्याज नहीं। ब्याज, शुल्क और कुल भुगतान तुलना करें।','తాకట్టు లేకపోవడం అంటే ఖచ్చితమైన ఆమోదం, మాఫీ లేదా తక్కువ వడ్డీ హామీ కాదు. వడ్డీ, రుసుములు, మొత్తం చెల్లింపు పోల్చండి.')},
 {id:'pmegp',name:'PMEGP',goals:['start'],type:L('Bank loan + conditional subsidy','बैंक ऋण + शर्तों वाला अनुदान','బ్యాంకు రుణం + షరతులతో సబ్సిడీ'),url:'https://www.kviconline.gov.in/pmegpeportal/pmegphome/index.jsp',source:'Ministry of MSME / KVIC',evidence:'https://www.pib.gov.in/PressNoteDetails.aspx?ModuleId=3&NoteId=158608&lang=1&reg=6',
 benefit:L('Published subsidy-eligible project ceilings: ₹50 lakh manufacturing; ₹20 lakh service/business. These are project costs, not free cash. Subsidy is back-ended; category and rural/urban location matter.','प्रकाशित अनुदान-योग्य परियोजना सीमा: निर्माण ₹50 लाख; सेवा/व्यवसाय ₹20 लाख। यह परियोजना लागत है, मुफ्त नकद नहीं। अनुदान बाद में समायोजित होता है; श्रेणी और ग्रामीण/शहरी स्थान मायने रखते हैं।','ప్రచురించిన సబ్సిడీ-అర్హ ప్రాజెక్టు పరిమితి: తయారీ ₹50 లక్షలు; సేవ/వ్యాపారం ₹20 లక్షలు. ఇవి ప్రాజెక్టు ఖర్చులు, ఉచిత నగదు కాదు. సబ్సిడీ తరువాత సర్దుబాటు అవుతుంది; కేటగిరీ, గ్రామీణ/పట్టణ స్థానం ముఖ్యం.'),
 fit:L('Explore for a new non-farm micro-enterprise. Confirm activity exclusions, own contribution, education and training requirements with KVIC/DIC.','नए गैर-कृषि सूक्ष्म व्यवसाय के लिए देखें। गतिविधि प्रतिबंध, अपना योगदान, शिक्षा और प्रशिक्षण की शर्तें KVIC/DIC से पक्की करें।','కొత్త వ్యవసాయేతర సూక్ష్మ వ్యాపారం కోసం చూడండి. మినహాయించిన పనులు, సొంత వాటా, విద్య, శిక్షణ షరతులు KVIC/DICతో నిర్ధారించండి.'),
 next:L('Before buying equipment, ask the official portal or District Industries Centre about current intake and your activity. Prepare a project report and supplier quotations.','मशीन खरीदने से पहले पोर्टल या जिला उद्योग केंद्र से वर्तमान आवेदन और गतिविधि की पुष्टि करें। परियोजना रिपोर्ट और विक्रेता के भाव तैयार करें।','పరికరాలు కొనే ముందు పోర్టల్ లేదా జిల్లా పరిశ్రమల కేంద్రంలో ప్రస్తుత దరఖాస్తుల స్వీకరణ, మీ పని గురించి నిర్ధారించండి. ప్రాజెక్టు నివేదిక, సరఫరాదారు ధరల పత్రాలు సిద్ధం చేయండి.'),
 caution:L('Current-year intake, local targets and personal subsidy are not verified here. Bank appraisal and scheme conditions apply; do not count subsidy as money available on day one.','चालू वर्ष के आवेदन, स्थानीय लक्ष्य और आपका अनुदान यहाँ सत्यापित नहीं। बैंक जाँच और योजना शर्तें लागू हैं; पहले दिन अनुदान मिलने का अनुमान न करें।','ప్రస్తుత సంవత్సరం దరఖాస్తులు, స్థానిక లక్ష్యాలు, మీ సబ్సిడీ ఇక్కడ ధ్రువీకరించలేదు. బ్యాంకు సమీక్ష, పథకం షరతులు వర్తిస్తాయి; మొదటి రోజే సబ్సిడీ వస్తుందని అనుకోకండి.')},
 {id:'vishwakarma',name:'PM Vishwakarma',goals:['craft'],type:L('Training + toolkit + conditional credit','प्रशिक्षण + औज़ार + सशर्त ऋण','శిక్షణ + పనిముట్లు + షరతులతో రుణం'),url:'https://pmvishwakarma.gov.in/',source:'Ministry of MSME',evidence:'https://www.pib.gov.in/Pressreleaseshare.aspx?PRID=1959098&lang=2&reg=48',
 benefit:L('For covered traditional trades: training, toolkit support and loans in ₹1 lakh then ₹2 lakh tranches at a published 5% beneficiary rate. The second tranche is conditional, not an immediate ₹3 lakh payment.','निर्धारित पारंपरिक कामों के लिए प्रशिक्षण, औज़ार सहायता और ₹1 लाख फिर ₹2 लाख ऋण किस्तें; प्रकाशित लाभार्थी ब्याज 5%। दूसरी किस्त सशर्त है, तुरंत ₹3 लाख नहीं।','గుర్తించిన సాంప్రదాయ వృత్తులకు శిక్షణ, పనిముట్ల సహాయం, మొదట ₹1 లక్ష తరువాత ₹2 లక్షల రుణం; ప్రచురించిన లబ్ధిదారు వడ్డీ 5%. రెండో విడతకు షరతులున్నాయి; వెంటనే ₹3 లక్షలు రావు.'),
 fit:L('Check the 18 covered trades, minimum age, family restrictions and previous similar loan rules. Basic training precedes the first loan; further conditions apply to the next tranche.','18 काम, न्यूनतम उम्र, परिवार की सीमा और पिछले समान ऋण के नियम जाँचें। पहले ऋण से पहले बुनियादी प्रशिक्षण; अगली किस्त की अतिरिक्त शर्तें हैं।','18 వృత్తులు, కనీస వయస్సు, కుటుంబ పరిమితులు, గత సారూప్య రుణ నియమాలు చూడండి. మొదటి రుణం ముందు ప్రాథమిక శిక్షణ; తదుపరి విడతకు అదనపు షరతులు వర్తిస్తాయి.'),
 next:L('Use the official portal or an authorized CSC to confirm your trade and current registration availability. Ask which training and verification step comes next.','आधिकारिक पोर्टल या अधिकृत CSC से अपना काम और वर्तमान पंजीकरण उपलब्धता पक्की करें। अगला प्रशिक्षण/सत्यापन कदम पूछें।','అధికారిక పోర్టల్ లేదా అధీకృత CSCలో మీ వృత్తి, ప్రస్తుత నమోదు అందుబాటు నిర్ధారించండి. తదుపరి శిక్షణ/ధ్రువీకరణ దశ అడగండి.'),
 caution:L('No slot, registration or loan is reserved here. Keep identity and OTP steps on the official channel; never pay someone promising guaranteed sanction.','यहाँ स्लॉट, पंजीकरण या ऋण आरक्षित नहीं। पहचान और OTP केवल आधिकारिक सेवा पर; पक्की मंज़ूरी का वादा करने वाले को पैसे न दें।','ఇక్కడ స్లాట్, నమోదు లేదా రుణం రిజర్వు కాదు. గుర్తింపు, OTP దశలు అధికారిక సేవలోనే చేయండి; ఖచ్చితమైన మంజూరు హామీ ఇచ్చేవారికి డబ్బు ఇవ్వవద్దు.')},
 {id:'seed',name:'Startup India Seed Fund',goals:['innovation'],type:L('Competitive grant / debt / convertible funding','चयन आधारित अनुदान / ऋण / परिवर्तनीय निवेश','ఎంపిక ఆధారిత గ్రాంటు / రుణం / మార్పిడి పెట్టుబడి'),url:'https://seedfund.startupindia.gov.in/faq',source:'Startup India / DPIIT',
 benefit:L('Published support: up to ₹20 lakh for proof of concept/prototypes/trials; up to ₹50 lakh through debt or convertible instruments for market entry and scaling. These are distinct funding types.','प्रकाशित सहायता: अवधारणा/नमूने/परीक्षण के लिए ₹20 लाख तक; बाज़ार और विस्तार के लिए ऋण या परिवर्तनीय निवेश से ₹50 लाख तक। ये अलग तरह की सहायता हैं।','ప్రచురించిన సహాయం: భావన/నమూనా/పరీక్షలకు ₹20 లక్షల వరకు; మార్కెట్ ప్రవేశం, విస్తరణకు రుణం లేదా మార్పిడి పెట్టుబడిగా ₹50 లక్షల వరకు. ఇవి వేర్వేరు నిధుల రకాలు.'),
 fit:L('For qualifying DPIIT-recognized startups incorporated no more than two years before application, subject to the full criteria. An individual with only an idea is not enough.','पूरी शर्तों के अनुसार आवेदन से अधिकतम दो साल पहले स्थापित DPIIT-मान्य स्टार्टअप। केवल व्यक्तिगत विचार पर्याप्त नहीं।','పూర్తి షరతులతో, దరఖాస్తుకు గరిష్ఠంగా రెండేళ్ల ముందు స్థాపించిన DPIIT గుర్తింపు ఉన్న స్టార్టప్. వ్యక్తిగత ఆలోచన మాత్రమే సరిపోదు.'),
 next:L('Check active participating incubators and available funds first. Prepare evidence of the problem, prototype milestones, team and use of funds; selection is by the incubator.','पहले सक्रिय इनक्यूबेटर और उपलब्ध निधि जाँचें। समस्या, नमूने के लक्ष्य, टीम और धन उपयोग का प्रमाण तैयार करें; चयन इनक्यूबेटर करता है।','ముందుగా క్రియాశీల ఇంక్యుబేటర్లు, నిధుల అందుబాటు చూడండి. సమస్య, నమూనా లక్ష్యాలు, బృందం, నిధుల వినియోగ ఆధారాలు సిద్ధం చేయండి; ఇంక్యుబేటర్ ఎంపిక చేస్తుంది.'),
 caution:L('Open intake and remaining allocations are not verified. A convertible instrument may dilute ownership; debt must be repaid. A published ceiling is not an offer.','खुले आवेदन और बची निधि सत्यापित नहीं। परिवर्तनीय निवेश से हिस्सेदारी घट सकती है; ऋण चुकाना होता है। प्रकाशित सीमा प्रस्ताव नहीं।','దరఖాస్తుల స్వీకరణ, మిగిలిన నిధులు ధ్రువీకరించలేదు. మార్పిడి పెట్టుబడితో యాజమాన్య వాటా తగ్గవచ్చు; రుణం చెల్లించాలి. ప్రచురించిన పరిమితి ఆఫర్ కాదు.')},
 {id:'cgtmse',name:'CGTMSE',goals:['grow','start'],type:L('Guarantee to a participating lender','भागीदार ऋणदाता को गारंटी','భాగస్వామి రుణదాతకు హామీ'),url:'https://www.cgtmse.in/Home/VS/96',source:'CGTMSE',
 benefit:L('Helps eligible lenders extend credit to micro and small enterprises. It is not a direct government loan or cash grant to you.','पात्र ऋणदाताओं से सूक्ष्म और छोटे व्यवसायों को ऋण दिलाने में मदद। यह आपको सीधा सरकारी ऋण या नकद अनुदान नहीं।','అర్హ రుణదాతల ద్వారా సూక్ష్మ, చిన్న వ్యాపారాలకు రుణ సదుపాయానికి సహాయం. ఇది మీకు నేరుగా ప్రభుత్వ రుణం లేదా నగదు గ్రాంటు కాదు.'),
 fit:L('Ask a member lending institution whether your viable business proposal can use its applicable guarantee scheme. Lender and facility-specific rules differ.','सदस्य बैंक से पूछें कि आपके व्यवहार्य व्यवसाय प्रस्ताव पर कौन सी गारंटी लागू हो सकती है। बैंक और सुविधा के नियम अलग हैं।','మీ ఆచరణయోగ్య వ్యాపార ప్రతిపాదనకు వర్తించే హామీ పథకం గురించి సభ్య బ్యాంకును అడగండి. బ్యాంకు, సదుపాయం ఆధారంగా నియమాలు మారతాయి.'),
 next:L('Give the bank a project plan and ask it to explain collateral, primary security, any personal guarantee and guarantee fees in writing. The lender applies for cover.','बैंक को योजना दें। जमानत, प्राथमिक सुरक्षा, व्यक्तिगत गारंटी और गारंटी शुल्क लिखित में पूछें। कवर के लिए बैंक आवेदन करता है।','బ్యాంకుకు ప్రణాళిక ఇవ్వండి. తాకట్టు, ప్రాథమిక భద్రత, వ్యక్తిగత హామీ, హామీ రుసుములను రాతపూర్వకంగా అడగండి. కవర్ కోసం బ్యాంకు దరఖాస్తు చేస్తుంది.'),
 caution:L('The guarantee does not cancel your debt or ensure approval. Do not pay an intermediary claiming to issue a CGTMSE loan.','गारंटी आपका कर्ज माफ या मंज़ूरी पक्की नहीं करती। CGTMSE ऋण देने का दावा करने वाले बिचौलिए को पैसे न दें।','హామీ మీ అప్పును మాఫీ చేయదు, ఆమోదానికి హామీ కాదు. CGTMSE రుణం ఇస్తామని చెప్పే మధ్యవర్తికి డబ్బు ఇవ్వవద్దు.')},
 {id:'udyam',name:'Udyam',goals:['start','grow','craft'],type:L('Free MSME registration','मुफ़्त MSME पंजीकरण','ఉచిత MSME నమోదు'),url:'https://udyamregistration.gov.in/',source:'Ministry of MSME',
 benefit:L('Official MSME registration is free and paperless. No renewal is required. Registration is not loan approval or a grant.','आधिकारिक MSME पंजीकरण मुफ़्त और कागज़रहित है। नवीनीकरण नहीं चाहिए। पंजीकरण ऋण मंज़ूरी या अनुदान नहीं।','అధికారిక MSME నమోదు ఉచితం, కాగితరహితం. పునరుద్ధరణ అవసరం లేదు. నమోదు రుణ ఆమోదం లేదా గ్రాంటు కాదు.'),
 fit:L('Check the official investment/turnover classification and applicable PAN/GST requirements. Do not create a second registration for an already registered enterprise.','आधिकारिक निवेश/टर्नओवर वर्ग और लागू PAN/GST शर्तें देखें। पहले से पंजीकृत व्यवसाय का दूसरा पंजीकरण न करें।','అధికారిక పెట్టుబడి/టర్నోవర్ వర్గం, వర్తించే PAN/GST షరతులు చూడండి. నమోదైన సంస్థకు రెండో నమోదు చేయవద్దు.'),
 next:L('Read requirements on the official portal, then complete identity steps there yourself. Use its update or recovery option if already registered.','आधिकारिक पोर्टल पर शर्तें पढ़ें और पहचान की प्रक्रिया वहीं स्वयं करें। पुराना पंजीकरण हो तो अपडेट या पुनःप्राप्ति विकल्प लें।','అధికారిక పోర్టల్‌లో అవసరాలు చదివి గుర్తింపు దశలను అక్కడే స్వయంగా చేయండి. పాత నమోదు ఉంటే నవీకరణ లేదా తిరిగి పొందే ఎంపిక వాడండి.'),
 caution:L('Udyam is MSME registration, not company incorporation. Your legal structure and activity may require separate incorporation, licences or tax registrations.','उद्यम MSME पंजीकरण है, कंपनी गठन नहीं। कानूनी स्वरूप और काम के अनुसार अलग गठन, लाइसेंस या टैक्स पंजीकरण लग सकते हैं।','ఉద్యమ్ MSME నమోదు మాత్రమే, కంపెనీ స్థాపన కాదు. చట్టపరమైన రూపం, పని ఆధారంగా ప్రత్యేక స్థాపన, లైసెన్సులు లేదా పన్ను నమోదు అవసరం కావచ్చు.')},
 {id:'training',name:'MSME entrepreneurship training',goals:['learn','start'],type:L('Training and preparation','प्रशिक्षण और तैयारी','శిక్షణ, తయారీ'),url:'https://ati.msme.gov.in/',source:'Ministry of MSME · ATI',
 benefit:L('Government-supported institutions offer entrepreneurship and skill-development programmes. Training support is not a personal business-capital grant.','सरकार-समर्थित संस्थान उद्यमिता और कौशल प्रशिक्षण देते हैं। प्रशिक्षण सहायता व्यवसाय पूँजी का व्यक्तिगत अनुदान नहीं।','ప్రభుత్వ మద్దతు సంస్థలు వ్యవస్థాపకత, నైపుణ్య శిక్షణ అందిస్తాయి. శిక్షణ సహాయం వ్యక్తిగత వ్యాపార మూలధన గ్రాంటు కాదు.'),
 fit:L('Useful before committing money: validate demand, costing, bookkeeping and the skills needed for your activity. Course-specific admission rules apply.','पैसा लगाने से पहले माँग, लागत, हिसाब और काम का कौशल समझें। हर कोर्स की प्रवेश शर्तें हैं।','డబ్బు పెట్టే ముందు డిమాండ్, ఖర్చులు, లెక్కలు, పనికి అవసరమైన నైపుణ్యాలు తెలుసుకోండి. కోర్సు ప్రవేశ నియమాలు వర్తిస్తాయి.'),
 next:L('Ask the official training institution about the next batch, language, location, duration, fees and any stipend before travelling or paying.','जाने या भुगतान से पहले आधिकारिक संस्थान से अगला बैच, भाषा, स्थान, अवधि, शुल्क और भत्ता पूछें।','వెళ్లే లేదా చెల్లించే ముందు అధికారిక సంస్థను తదుపరి బ్యాచ్, భాష, స్థలం, వ్యవధి, రుసుము, భత్యం గురించి అడగండి.'),
 caution:L('No local batch, free seat, stipend or job placement is verified or reserved here.','यहाँ स्थानीय बैच, मुफ्त सीट, भत्ता या नौकरी सत्यापित या आरक्षित नहीं।','ఇక్కడ స్థానిక బ్యాచ్, ఉచిత సీటు, భత్యం లేదా ఉద్యోగం ధ్రువీకరించలేదు, రిజర్వు చేయలేదు.')}
];
export function forGoal(goal:string){return goal==='all'?programmes:goals.some(g=>g.id===goal)?programmes.filter(p=>p.goals.includes(goal)):[]}
export function fresh(now=Date.now()){return Number.isFinite(now)&&now>=Date.parse(reviewed)&&now<Date.parse(reviewBy)}
