import type {DirectoryLanguage} from './service-directory.ts';
export const deskActions=['schemes','aadhaar','flight','land','education','farm'] as const;
export const deskCopy:Record<DirectoryLanguage,{
 eyebrow:string;title:string;accent:string;intro:string;start:string;how:string;openGuide:string;
 steps:string[];stepDetails:string[];labels:string[];details:string[];catalog:string;catalogIntro:string;
 family:string;live:string;trust:string;region:string;language:string;private:string;
}>={
 en:{eyebrow:'YOUR EVERYDAY HELP DESK',title:'What do you need',accent:'help with today?',intro:'Benefits, documents, travel, health, farming and more. Choose a service. Get a clear next step.',start:'Start with your need',how:'New here? It works in 3 steps.',openGuide:'Show me how',steps:['Speak or choose','Answer a few questions','Take the next step'],stepDetails:['Use your language, type or tap a service.','Share only the details needed for guidance.','Review the checklist and open the official service.'],labels:['Family benefits','Aadhaar & documents','Plan a journey','Land & property','School & scholarships','Farming support'],details:['Pensions, family support, housing','Updates, certificates, digital records','Flights, trains, cabs, holidays','Land records, registration preparation','Scholarship routes and learning','PM-KISAN, crops, market information'],catalog:'Explore every service',catalogIntro:'Choose a topic or search. Each card tells you what you can do here.',family:'Family tools',live:'Tracking & live info',trust:'Free guidance · No account needed to explore',region:'India · State / UT official routes',language:'English · हिन्दी / తెలుగు previews',private:'Sign-in required to save private records'},
 hi:{eyebrow:'आपकी रोज़मर्रा की सहायता',title:'आज आपको किस',accent:'मदद की ज़रूरत है?',intro:'योजनाएँ, दस्तावेज़, यात्रा, स्वास्थ्य, खेती और बहुत कुछ। सेवा चुनें और अगला कदम जानें।',start:'अपनी ज़रूरत से शुरू करें',how:'पहली बार आए हैं? 3 आसान कदम।',openGuide:'इस्तेमाल करना सीखें',steps:['बोलें या चुनें','कुछ सवालों के जवाब दें','अगला कदम उठाएँ'],stepDetails:['अपनी भाषा में बोलें, लिखें या सेवा चुनें।','केवल मार्गदर्शन के लिए ज़रूरी जानकारी दें।','सूची देखें और आधिकारिक सेवा खोलें।'],labels:['परिवार की योजनाएँ','आधार और दस्तावेज़','यात्रा की तैयारी','जमीन और संपत्ति','स्कूल और छात्रवृत्ति','खेती में सहायता'],details:['पेंशन, परिवार सहायता, आवास','अपडेट, प्रमाणपत्र, डिजिटल रिकॉर्ड','उड़ान, रेल, कैब, छुट्टियाँ','भूमि रिकॉर्ड, पंजीकरण की तैयारी','छात्रवृत्ति और पढ़ाई के रास्ते','पीएम-किसान, फसल, बाज़ार जानकारी'],catalog:'सभी सेवाएँ देखें',catalogIntro:'विषय चुनें या खोजें। हर कार्ड बताता है कि यहाँ क्या कर सकते हैं।',family:'परिवार के साधन',live:'ट्रैकिंग और जानकारी',trust:'मुफ़्त मार्गदर्शन · देखने के लिए खाता ज़रूरी नहीं',region:'भारत · राज्य / केंद्र शासित प्रदेश के आधिकारिक रास्ते',language:'English · हिन्दी / తెలుగు पूर्वावलोकन',private:'निजी रिकॉर्ड सहेजने के लिए साइन इन करें'},
 te:{eyebrow:'మీ రోజువారీ సహాయ కేంద్రం',title:'ఈ రోజు మీకు',accent:'ఏ సహాయం కావాలి?',intro:'పథకాలు, పత్రాలు, ప్రయాణం, ఆరోగ్యం, వ్యవసాయం ఇంకా మరెన్నో. సేవను ఎంచుకుని తదుపరి అడుగు తెలుసుకోండి.',start:'మీ అవసరంతో ప్రారంభించండి',how:'మొదటిసారి వచ్చారా? 3 సులభమైన దశలు.',openGuide:'ఎలా వాడాలో చూపించండి',steps:['చెప్పండి లేదా ఎంచుకోండి','కొన్ని ప్రశ్నలకు జవాబివ్వండి','తదుపరి అడుగు వేయండి'],stepDetails:['మీ భాషలో మాట్లాడండి, రాయండి లేదా సేవ ఎంచుకోండి.','మార్గదర్శనానికి అవసరమైన వివరాలే ఇవ్వండి.','జాబితాను చూసి అధికారిక సేవను తెరవండి.'],labels:['కుటుంబ పథకాలు','ఆధార్, పత్రాలు','ప్రయాణం ప్లాన్ చేయండి','భూమి, ఆస్తి','పాఠశాల, ఉపకారవేతనాలు','వ్యవసాయ సహాయం'],details:['పెన్షన్, కుటుంబ సహాయం, గృహాలు','మార్పులు, ధృవపత్రాలు, డిజిటల్ రికార్డులు','విమానాలు, రైళ్లు, క్యాబ్‌లు, సెలవులు','భూ రికార్డులు, రిజిస్ట్రేషన్ తయారీ','ఉపకారవేతనాలు, అభ్యాస మార్గాలు','పీఎం-కిసాన్, పంటలు, మార్కెట్ సమాచారం'],catalog:'అన్ని సేవలను చూడండి',catalogIntro:'అంశాన్ని ఎంచుకోండి లేదా వెతకండి. ప్రతి కార్డు ఇక్కడ ఏమి చేయవచ్చో చెబుతుంది.',family:'కుటుంబ సాధనాలు',live:'ట్రాకింగ్, సమాచారం',trust:'ఉచిత మార్గదర్శనం · చూడటానికి ఖాతా అవసరం లేదు',region:'భారతదేశం · రాష్ట్ర / కేంద్రపాలిత ప్రాంత అధికారిక మార్గాలు',language:'English · हिन्दी / తెలుగు ముందస్తు రూపాలు',private:'వ్యక్తిగత రికార్డులు సేవ్ చేయడానికి సైన్ ఇన్ చేయండి'}
};
