import {services} from './services.ts';
import {serviceTranslations} from './service-translations.ts';
import {regionGuide} from './regional-guidance.ts';
export type Language='en'|'hi'|'te';
export const locales={en:'en-IN',hi:'hi-IN',te:'te-IN'} as const;
export const languageNames={en:'English',hi:'हिन्दी',te:'తెలుగు'};
export const languageRelease={en:'early_access',hi:'review_preview',te:'review_preview'} as const;
const rows:Record<string,[string,string,string]>={
"next_actions":["Your next steps", "आपके अगले कदम", "మీ తదుపరి చర్యలు"],
"next_action_note":["Based on your saved details. These are your dates and progress, not official deadlines or approval status.", "आपकी सहेजी जानकारी के आधार पर। ये आपकी तारीखें और प्रगति हैं, सरकारी अंतिम तारीख या मंज़ूरी की स्थिति नहीं।", "మీరు భద్రపరిచిన వివరాల ఆధారంగా. ఇవి మీ తేదీలు, పురోగతి; అధికారిక గడువులు లేదా ఆమోద స్థితి కాదు."],
"no_next_action":["Choose a service to start. Your saved tasks will appear here.", "शुरू करने के लिए सेवा चुनें। सहेजे काम यहाँ दिखेंगे।", "ప్రారంభించడానికి సేవ ఎంచుకోండి. భద్రపరిచిన పనులు ఇక్కడ కనిపిస్తాయి."],
"overdue":["Your date has passed", "आपकी तारीख बीत गई", "మీ తేదీ దాటింది"],
"due_today":["Your task is due today", "आपका काम आज है", "మీ పని ఈరోజు"],
"upcoming":["Upcoming task", "आने वाला काम", "రాబోయే పని"],
"expired":["Recorded expiry has passed", "दर्ज समाप्ति तारीख बीत गई", "నమోదైన గడువు దాటింది"],
"expiring":["Recorded expiry is approaching", "दर्ज समाप्ति तारीख पास है", "నమోదైన గడువు దగ్గరలో ఉంది"],
"missing_document":["You marked this document as missing", "आपने यह दस्तावेज़ अधूरा बताया", "ఈ పత్రం సిద్ధం కాలేదని మీరు గుర్తించారు"],
"unfinished_task":["Your preparation step is unfinished", "तैयारी का कदम अधूरा है", "మీ సన్నాహక చర్య పూర్తికాలేదు"],
"feedback":["Was this helpful?", "क्या यह मददगार था?", "ఇది ఉపయోగపడిందా?"],
"feedback_title":["Help us improve Saathi", "साथी को बेहतर बनाएँ", "సాథిని మెరుగుపరచడంలో సహాయపడండి"],
"understanding":["Did you understand the next step?", "क्या अगला कदम समझ आया?", "తదుపరి చర్య అర్థమైందా?"],
"clear":["Yes, it was clear", "हाँ, स्पष्ट था", "అవును, స్పష్టంగా ఉంది"],
"unclear":["I need a clearer explanation", "और स्पष्ट जानकारी चाहिए", "ఇంకా స్పష్టమైన వివరణ కావాలి"],
"outcome":["What happened next?", "इसके बाद क्या हुआ?", "తర్వాత ఏమైంది?"],
"completed":["I completed my task", "मैंने अपना काम पूरा किया", "నా పని పూర్తిచేశాను"],
"not_completed":["Not completed yet", "अभी पूरा नहीं हुआ", "ఇంకా పూర్తికాలేదు"],
"blocked":["I could not continue", "आगे नहीं बढ़ पाया", "ముందుకు వెళ్లలేకపోయాను"],
"feedback_note":["Optional comment — no private numbers", "वैकल्पिक टिप्पणी — निजी संख्या न दें", "అభిప్రాయం ఇవ్వవచ్చు — గోప్య సంఖ్యలు వద్దు"],
"feedback_consent":["Share these answers with the pilot administrator to improve the service.", "सेवा सुधारने के लिए ये उत्तर पायलट प्रशासक से साझा करें।", "సేవను మెరుగుపరచడానికి ఈ సమాధానాలను పైలట్ నిర్వాహకుడితో పంచుకోండి."],
hello:['Hello. What help do you need today?','नमस्ते। आज आपको किस मदद की ज़रूरत है?','నమస్కారం. ఈ రోజు మీకు ఏ సహాయం కావాలి?'],
speak:['Speak your problem','अपनी समस्या बोलें','మీ సమస్య చెప్పండి'],
home:['Home','मुख्य पृष्ठ','మొదటి పేజీ'],back:['Back','पीछे','వెనక్కి'],next:['Next','आगे','తరువాత'],repeat:['Listen again','फिर सुनें','మళ్లీ వినండి'],listen:['Listen','सुनें','వినండి'],stop:['Stop','रोकें','ఆపండి'],start:['Start voice guide','बोलकर शुरू करें','మాట్లాడటం ప్రారంభించండి'],reply:['Speak reply','जवाब बोलें','సమాధానం చెప్పండి'],
yes:['Yes','हाँ','అవును'],no:['No','नहीं','కాదు'],unknown:['Not sure','पता नहीं','తెలియదు'],current:['Use current region','यही क्षेत्र रखें','ఇదే ప్రాంతం'],
services:['All services','सभी सेवाएँ','అన్ని సేవలు'],benefits:['Family benefits','परिवार की योजनाएँ','కుటుంబ పథకాలు'],documents:['Document help','दस्तावेज़ सहायता','పత్రాల సహాయం'],reminders:['My reminders','मेरे अनुस्मारक','నా గుర్తుచేసే పనులు'],helper:['Get help','मदद लें','సహాయం పొందండి'],family:['My family','मेरा परिवार','నా కుటుంబం'],
region:['State / Union Territory','राज्य / केंद्र शासित प्रदेश','రాష్ట్రం / కేంద్రపాలిత ప్రాంతం'],regional:['Your region’s official directory','आपके क्षेत्र की आधिकारिक निर्देशिका','మీ ప్రాంత అధికారిక డైరెక్టరీ'],national:['National service','राष्ट्रीय सेवा','జాతీయ సేవ'],land:['State land-record route','राज्य भू-अभिलेख सेवा','రాష్ట్ర భూ రికార్డుల సేవ'],regionNote:['This directory identifies official departments. It does not verify local eligibility, fees, deadlines or application availability.','यह निर्देशिका आधिकारिक विभाग बताती है। स्थानीय पात्रता, शुल्क, अंतिम तारीख या आवेदन उपलब्धता की पुष्टि अलग से करें।','ఈ డైరెక్టరీ అధికారిక శాఖలను చూపుతుంది. స్థానిక అర్హత, రుసుములు, గడువులు, దరఖాస్తు లభ్యతను విడిగా నిర్ధారించండి.'],
preview:['Language review preview','भाषा समीक्षा पूर्वावलोकन','భాష సమీక్ష ముందస్తు రూపం'],previewNote:['Hindi and Telugu translations are available for voluntary review. Native-speaker comprehension and device speech checks are pending. Do not rely on this preview alone for a decision.','हिन्दी और तेलुगु अनुवाद समीक्षा के लिए हैं। स्थानीय भाषा बोलने वालों और वास्तविक उपकरणों पर जाँच बाकी है। निर्णय के लिए केवल इस पूर्वावलोकन पर निर्भर न रहें।','హిందీ, తెలుగు అనువాదాలు సమీక్ష కోసం ఉన్నాయి. స్థానిక భాష మాట్లాడేవారితో, నిజమైన పరికరాలతో పరీక్షలు ఇంకా జరగాలి. నిర్ణయానికి ఈ ముందస్తు రూపం మీద మాత్రమే ఆధారపడకండి.'],acceptPreview:['Try the review preview','समीक्षा पूर्वावलोकन आज़माएँ','సమీక్ష రూపాన్ని ప్రయత్నించండి'],language:['Language','भाषा','భాష'],
consentVoice:['Starting allows your device or browser speech provider to process audio. Saathi does not store recordings or transcripts. Never say PINs, OTPs or identity numbers.','शुरू करने पर उपकरण या ब्राउज़र की आवाज़ सेवा ऑडियो संसाधित कर सकती है। साथी रिकॉर्डिंग या बातचीत नहीं रखता। पिन, ओटीपी या पहचान संख्या न बोलें।','ప్రారంభిస్తే పరికరం లేదా బ్రౌజర్ వాయిస్ సేవ ఆడియోను ప్రాసెస్ చేయవచ్చు. సాథి రికార్డింగ్‌లు, సంభాషణలను నిల్వ చేయదు. పిన్, ఓటీపీ, గుర్తింపు సంఖ్యలు చెప్పవద్దు.'],
voiceOff:['Microphone off','माइक्रोफोन बंद','మైక్రోఫోన్ ఆఫ్'],listening:['Listening…','सुन रहे हैं…','వింటున్నాం…'],speaking:['Speaking…','बोल रहे हैं…','చెబుతున్నాం…'],voiceError:['Voice is unavailable or unclear. Check microphone permission and an installed voice for this language, then retry. You can use the large answer buttons.','आवाज़ उपलब्ध नहीं है या स्पष्ट नहीं है। माइक्रोफोन की अनुमति और इस भाषा की आवाज़ जाँचकर फिर कोशिश करें। बड़े उत्तर बटन भी इस्तेमाल कर सकते हैं।','వాయిస్ అందుబాటులో లేదు లేదా స్పష్టంగా లేదు. మైక్రోఫోన్ అనుమతి, ఈ భాష వాయిస్ ఉన్నాయో చూసి మళ్లీ ప్రయత్నించండి. పెద్ద సమాధాన బటన్లు కూడా ఉపయోగించవచ్చు.'],
heard:['You said','आपने कहा','మీరు చెప్పింది'],steps:['Show steps','चरण देखें','చర్యలు చూడండి'],checklist:['My preparation checklist','मेरी तैयारी सूची','నా సన్నాహక జాబితా'],complete:['Mark complete','पूरा चिन्हित करें','పూర్తయిందని గుర్తించండి'],remove:['Remove','हटाएँ','తొలగించండి'],save:['Save','सहेजें','భద్రపరచండి'],saved:['Saved privately.','निजी रूप से सहेजा गया।','గోప్యంగా భద్రపరిచాం.'],saveError:['Save was not confirmed. Your input remains here. Check the connection and retry.','सहेजने की पुष्टि नहीं हुई। जानकारी यहीं है। कनेक्शन जाँचें और फिर कोशिश करें।','భద్రపరిచినట్టు నిర్ధారణ కాలేదు. మీ సమాచారం ఇక్కడే ఉంది. కనెక్షన్ చూసి మళ్లీ ప్రయత్నించండి.'],saving:['Saving…','सहेज रहे हैं…','భద్రపరుస్తున్నాం…'],
signin:['Sign in to save','सहेजने के लिए साइन इन करें','భద్రపరచడానికి సైన్ ఇన్ చేయండి'],signinNote:['Explore without an account. Private records currently require Sign in with ChatGPT.','बिना खाते जानकारी देखें। निजी रिकॉर्ड सहेजने के लिए अभी चैटजीपीटी से साइन इन करना होगा।','ఖాతా లేకుండా సమాచారం చూడవచ్చు. గోప్యంగా వివరాలు భద్రపరచడానికి ప్రస్తుతం చాట్‌జీపీటీతో సైన్ ఇన్ అవసరం.'],
logout:['Sign out','साइन आउट','సైన్ అవుట్'],shared:['Shared phone? Sign out when finished. Private records are not cached offline.','साझा फ़ोन है? काम के बाद साइन आउट करें। निजी रिकॉर्ड ऑफलाइन नहीं रखे जाते।','ఉమ్మడి ఫోనా? పూర్తయిన తర్వాత సైన్ అవుట్ చేయండి. గోప్యమైన రికార్డులు ఆఫ్‌లైన్‌లో నిల్వ కావు.'],
offline:['Offline: public guidance may be outdated. Reconnect to save.','ऑफलाइन: जानकारी पुरानी हो सकती है। सहेजने के लिए इंटरनेट जोड़ें।','ఆఫ్‌లైన్: సమాచారం పాతది కావచ్చు. భద్రపరచడానికి ఇంటర్నెట్ కలపండి.'],
source:['Official source','आधिकारिक स्रोत','అధికారిక మూలం'],review:['Source checked 28 Sep 2026 · Review due 28 Oct 2026','स्रोत जाँच: 28 सितंबर 2026 · अगली समीक्षा: 28 अक्टूबर 2026','మూలం పరిశీలన: 28 సెప్టెంబర్ 2026 · తదుపరి సమీక్ష: 28 అక్టోబర్ 2026'],stale:['Review overdue. Confirm current information with the official department.','समीक्षा की तारीख बीत गई है। विभाग से वर्तमान जानकारी की पुष्टि करें।','సమీక్ష గడువు దాటింది. శాఖతో ప్రస్తుత సమాచారం నిర్ధారించండి.'],
routeWarning:['Official portals may require forms, identity checks or a visit. Saathi does not submit applications or approve benefits.','आधिकारिक पोर्टल पर फ़ॉर्म, पहचान जाँच या कार्यालय जाना ज़रूरी हो सकता है। साथी आवेदन जमा या लाभ मंज़ूर नहीं करता।','అధికారిక పోర్టల్‌లో ఫారాలు, గుర్తింపు ధ్రువీకరణ లేదా కార్యాలయ సందర్శన అవసరం కావచ్చు. సాథి దరఖాస్తులు సమర్పించదు, ప్రయోజనాలు మంజూరు చేయదు.'],
propertyWarning:['Land records or a RERA listing do not prove clear title. Ask a qualified local professional to review the property before payment.','भू-अभिलेख या रेरा सूची से निर्विवाद स्वामित्व साबित नहीं होता। भुगतान से पहले योग्य स्थानीय विशेषज्ञ से जाँच कराएँ।','భూ రికార్డులు లేదా రెరా నమోదు వివాదరహిత యాజమాన్యానికి రుజువు కాదు. చెల్లింపుకు ముందు అర్హత కలిగిన స్థానిక నిపుణుడితో పరిశీలించండి.'],moneyWarning:['Information only: no investment recommendations, live quotes, loans, insurance sales or transactions in Saathi. Never share PINs or OTPs.','केवल जानकारी: साथी निवेश सलाह, लाइव भाव, ऋण, बीमा बिक्री या लेनदेन नहीं करता। पिन या ओटीपी साझा न करें।','సమాచారం మాత్రమే: సాథిలో పెట్టుబడి సిఫార్సులు, ప్రత్యక్ష ధరలు, రుణాలు, బీమా అమ్మకాలు, లావాదేవీలు లేవు. పిన్ లేదా ఓటీపీ పంచుకోవద్దు.'],healthWarning:['Service navigation only, not diagnosis. For immediate danger in India, call 112.','केवल सेवा का मार्ग, बीमारी का निदान नहीं। भारत में तुरंत खतरा हो तो 112 पर कॉल करें।','సేవకు మార్గం మాత్రమే, వ్యాధి నిర్ధారణ కాదు. భారతదేశంలో తక్షణ ప్రమాదం ఉంటే 112కు కాల్ చేయండి.'],
name:['First name or nickname','नाम या उपनाम','పేరు లేదా ముద్దుపేరు'],age:['Age','उम्र','వయసు'],relation:['Relationship','रिश्ता','సంబంధం'],memberConsent:['I have permission to save this person’s minimal details.','मुझे इस व्यक्ति की न्यूनतम जानकारी सहेजने की अनुमति है।','ఈ వ్యక్తి కనీస వివరాలు భద్రపరచడానికి నాకు అనుమతి ఉంది.'],
Self:['Self','स्वयं','నేను'],Parent:['Parent','माता / पिता','తల్లి / తండ్రి'],Spouse:['Spouse','जीवनसाथी','భార్య / భర్త'],Child:['Child','बच्चा','బిడ్డ'],Other:['Other','अन्य','ఇతరులు'],addMember:['Add family member','परिवार का सदस्य जोड़ें','కుటుంబ సభ్యుడిని చేర్చండి'],empty:['Nothing saved yet.','अभी कुछ सहेजा नहीं गया।','ఇంకా ఏమీ భద్రపరచలేదు.'],
title:['Task or document name','काम या दस्तावेज़ का नाम','పని లేదా పత్రం పేరు'],due:['Date (India time)','तारीख (भारत समय)','తేదీ (భారత సమయం)'],expires:['Expiry date, if any','समाप्ति तारीख, यदि हो','గడువు తేదీ ఉంటే'],ready:['Document ready','दस्तावेज़ तैयार','పత్రం సిద్ధం'],addDocument:['Add document','दस्तावेज़ जोड़ें','పత్రం చేర్చండి'],
reminderNote:['Reminders appear inside Saathi. SMS and background delivery are not connected. Dates are chosen by you, not official deadlines.','अनुस्मारक साथी के अंदर दिखते हैं। एसएमएस या बैकग्राउंड संदेश जुड़े नहीं हैं। तारीख आपकी चुनी हुई है, सरकारी अंतिम तारीख नहीं।','గుర్తుచేసే పనులు సాథిలో కనిపిస్తాయి. ఎస్ఎంఎస్, బ్యాక్‌గ్రౌండ్ సందేశాలు అనుసంధానం కాలేదు. తేదీ మీరు ఎంచుకున్నది; ప్రభుత్వ గడువు కాదు.'],
helperNote:['₹0 service charge. A staffed helper network is not connected. Requests go to the pilot administrator; no response time or external dispatch is promised.','सेवा शुल्क ₹0। सहायता कर्मचारियों का नेटवर्क अभी नहीं जुड़ा है। अनुरोध पायलट प्रशासक देख सकता है; जवाब का समय या बाहरी सहायता का वादा नहीं है।','సేవ రుసుము ₹0. సిబ్బందితో సహాయక వ్యవస్థ ఇంకా అనుసంధానం కాలేదు. అభ్యర్థనలను పైలట్ నిర్వాహకుడు చూడవచ్చు; స్పందన సమయం లేదా బయటి సహాయం హామీ లేదు.'],helpConsent:['Share only this request with the pilot administrator.','केवल यह अनुरोध पायलट प्रशासक से साझा करें।','ఈ అభ్యర్థనను మాత్రమే పైలట్ నిర్వాహకుడితో పంచుకోండి.'],helpNote:['Describe the help needed. Do not enter private identity or account numbers.','ज़रूरी मदद बताएँ। निजी पहचान या खाता संख्या न दें।','కావాల్సిన సహాయం చెప్పండి. గోప్య గుర్తింపు లేదా ఖాతా సంఖ్యలు ఇవ్వవద్దు.'],unassigned:['Awaiting review','समीक्षा की प्रतीक्षा','సమీక్ష కోసం వేచి ఉంది'],reviewed:['Reviewed','समीक्षा हुई','సమీక్షించారు'],closed:['Closed','बंद','ముగిసింది'],
emergency:['Emergency help · Call 112','आपातकालीन मदद · 112 पर कॉल','అత్యవసర సహాయం · 112కు కాల్'],emergencyNote:['Saathi cannot dispatch emergency services. Call the official service directly.','साथी आपातकालीन सेवा नहीं भेज सकता। सीधे आधिकारिक सेवा को कॉल करें।','సాథి అత్యవసర సేవలను పంపించదు. అధికారిక సేవకు నేరుగా కాల్ చేయండి.'],privacy:['Privacy','गोपनीयता','గోప్యత'],delete:['Delete my saved data','मेरी सहेजी जानकारी मिटाएँ','నా భద్రపరిచిన వివరాలు తొలగించండి'],deleteConfirm:['Permanently delete all your saved family records, reminders and requests? Your ChatGPT account is unchanged.','सभी सहेजे परिवार रिकॉर्ड, अनुस्मारक और अनुरोध हमेशा के लिए मिटाएँ? चैटजीपीटी खाता नहीं बदलेगा।','మీ కుటుంబ రికార్డులు, గుర్తుచేసే పనులు, అభ్యర్థనలు శాశ్వతంగా తొలగించాలా? మీ చాట్‌జీపీటీ ఖాతా మారదు.'],cancel:['Cancel','रद्द करें','రద్దు'],
};
export function text(key:string,lang:Language):string{return rows[key]?.[lang==='hi'?1:lang==='te'?2:0]??rows[key]?.[0]??key}
export function serviceText(id:string,lang:Language){const s=services.find(s=>s.id===id);if(!s)return null;return lang==='en'?{title:s.title,steps:s.steps}:serviceTranslations[lang][id]??null}
export function regionText(name:string,lang:Language){const r=regionGuide(name);return r?(lang==='en'?r.name:r[lang]):name}
export function serviceWarning(id:string,lang:Language){const keys=['routeWarning'];if(['land','flat'].includes(id))keys.unshift('propertyWarning');if(['stocks','credit','cropinsurance'].includes(id))keys.unshift('moneyWarning');if(['health','telemedicine','nutrition'].includes(id))keys.unshift('healthWarning');return keys.map(k=>text(k,lang)).join(' ')}
export const translationKeys=Object.keys(rows);
