import {landPortals} from "./regions.ts";
export const regionalGuidance=[
  {
    "name": "Andaman and Nicobar Islands",
    "code": "AN",
    "hi": "अंडमान और निकोबार द्वीपसमूह",
    "te": "అండమాన్ నికోబార్ దీవులు",
    "kind": "UT",
    "directory": "https://igod.gov.in/sg/AN/categories",
    "checked": "2026-09-28",
    "reviewDue": "2026-10-28",
    "verification": "directory_verified"
  },
  {
    "name": "Andhra Pradesh",
    "code": "AP",
    "hi": "आंध्र प्रदेश",
    "te": "ఆంధ్ర ప్రదేశ్",
    "kind": "state",
    "directory": "https://igod.gov.in/sg/AP/categories",
    "checked": "2026-09-28",
    "reviewDue": "2026-10-28",
    "verification": "directory_verified"
  },
  {
    "name": "Arunachal Pradesh",
    "code": "AR",
    "hi": "अरुणाचल प्रदेश",
    "te": "అరుణాచల్ ప్రదేశ్",
    "kind": "state",
    "directory": "https://igod.gov.in/sg/AR/categories",
    "checked": "2026-09-28",
    "reviewDue": "2026-10-28",
    "verification": "directory_verified"
  },
  {
    "name": "Assam",
    "code": "AS",
    "hi": "असम",
    "te": "అస్సాం",
    "kind": "state",
    "directory": "https://igod.gov.in/sg/AS/categories",
    "checked": "2026-09-28",
    "reviewDue": "2026-10-28",
    "verification": "directory_verified"
  },
  {
    "name": "Bihar",
    "code": "BR",
    "hi": "बिहार",
    "te": "బీహార్",
    "kind": "state",
    "directory": "https://igod.gov.in/sg/BR/categories",
    "checked": "2026-09-28",
    "reviewDue": "2026-10-28",
    "verification": "directory_verified"
  },
  {
    "name": "Chandigarh",
    "code": "CH",
    "hi": "चंडीगढ़",
    "te": "చండీగఢ్",
    "kind": "UT",
    "directory": "https://igod.gov.in/sg/CH/categories",
    "checked": "2026-09-28",
    "reviewDue": "2026-10-28",
    "verification": "directory_verified"
  },
  {
    "name": "Chhattisgarh",
    "code": "CG",
    "hi": "छत्तीसगढ़",
    "te": "ఛత్తీస్‌గఢ్",
    "kind": "state",
    "directory": "https://igod.gov.in/sg/CG/categories",
    "checked": "2026-09-28",
    "reviewDue": "2026-10-28",
    "verification": "directory_verified"
  },
  {
    "name": "Dadra and Nagar Haveli and Daman and Diu",
    "code": "ND",
    "hi": "दादरा और नगर हवेली और दमन और दीव",
    "te": "దాద్రా నగర్ హవేలీ డామన్ డయ్యూ",
    "kind": "UT",
    "directory": "https://igod.gov.in/sg/ND/categories",
    "checked": "2026-09-28",
    "reviewDue": "2026-10-28",
    "verification": "directory_verified"
  },
  {
    "name": "Delhi",
    "code": "DL",
    "hi": "दिल्ली",
    "te": "ఢిల్లీ",
    "kind": "UT",
    "directory": "https://igod.gov.in/sg/DL/categories",
    "checked": "2026-09-28",
    "reviewDue": "2026-10-28",
    "verification": "directory_verified"
  },
  {
    "name": "Goa",
    "code": "GA",
    "hi": "गोवा",
    "te": "గోవా",
    "kind": "state",
    "directory": "https://igod.gov.in/sg/GA/categories",
    "checked": "2026-09-28",
    "reviewDue": "2026-10-28",
    "verification": "directory_verified"
  },
  {
    "name": "Gujarat",
    "code": "GJ",
    "hi": "गुजरात",
    "te": "గుజరాత్",
    "kind": "state",
    "directory": "https://igod.gov.in/sg/GJ/categories",
    "checked": "2026-09-28",
    "reviewDue": "2026-10-28",
    "verification": "directory_verified"
  },
  {
    "name": "Haryana",
    "code": "HR",
    "hi": "हरियाणा",
    "te": "హర్యానా",
    "kind": "state",
    "directory": "https://igod.gov.in/sg/HR/categories",
    "checked": "2026-09-28",
    "reviewDue": "2026-10-28",
    "verification": "directory_verified"
  },
  {
    "name": "Himachal Pradesh",
    "code": "HP",
    "hi": "हिमाचल प्रदेश",
    "te": "హిమాచల్ ప్రదేశ్",
    "kind": "state",
    "directory": "https://igod.gov.in/sg/HP/categories",
    "checked": "2026-09-28",
    "reviewDue": "2026-10-28",
    "verification": "directory_verified"
  },
  {
    "name": "Jammu and Kashmir",
    "code": "JK",
    "hi": "जम्मू और कश्मीर",
    "te": "జమ్మూ కాశ్మీర్",
    "kind": "UT",
    "directory": "https://igod.gov.in/sg/JK/categories",
    "checked": "2026-09-28",
    "reviewDue": "2026-10-28",
    "verification": "directory_verified"
  },
  {
    "name": "Jharkhand",
    "code": "JH",
    "hi": "झारखंड",
    "te": "జార్ఖండ్",
    "kind": "state",
    "directory": "https://igod.gov.in/sg/JH/categories",
    "checked": "2026-09-28",
    "reviewDue": "2026-10-28",
    "verification": "directory_verified"
  },
  {
    "name": "Karnataka",
    "code": "KA",
    "hi": "कर्नाटक",
    "te": "కర్ణాటక",
    "kind": "state",
    "directory": "https://igod.gov.in/sg/KA/categories",
    "checked": "2026-09-28",
    "reviewDue": "2026-10-28",
    "verification": "directory_verified"
  },
  {
    "name": "Kerala",
    "code": "KL",
    "hi": "केरल",
    "te": "కేరళ",
    "kind": "state",
    "directory": "https://igod.gov.in/sg/KL/categories",
    "checked": "2026-09-28",
    "reviewDue": "2026-10-28",
    "verification": "directory_verified"
  },
  {
    "name": "Ladakh",
    "code": "LA",
    "hi": "लद्दाख",
    "te": "లడఖ్",
    "kind": "UT",
    "directory": "https://igod.gov.in/sg/LA/categories",
    "checked": "2026-09-28",
    "reviewDue": "2026-10-28",
    "verification": "directory_verified"
  },
  {
    "name": "Lakshadweep",
    "code": "LD",
    "hi": "लक्षद्वीप",
    "te": "లక్షద్వీప్",
    "kind": "UT",
    "directory": "https://igod.gov.in/sg/LD/categories",
    "checked": "2026-09-28",
    "reviewDue": "2026-10-28",
    "verification": "directory_verified"
  },
  {
    "name": "Madhya Pradesh",
    "code": "MP",
    "hi": "मध्य प्रदेश",
    "te": "మధ్య ప్రదేశ్",
    "kind": "state",
    "directory": "https://igod.gov.in/sg/MP/categories",
    "checked": "2026-09-28",
    "reviewDue": "2026-10-28",
    "verification": "directory_verified"
  },
  {
    "name": "Maharashtra",
    "code": "MH",
    "hi": "महाराष्ट्र",
    "te": "మహారాష్ట్ర",
    "kind": "state",
    "directory": "https://igod.gov.in/sg/MH/categories",
    "checked": "2026-09-28",
    "reviewDue": "2026-10-28",
    "verification": "directory_verified"
  },
  {
    "name": "Manipur",
    "code": "MN",
    "hi": "मणिपुर",
    "te": "మణిపూర్",
    "kind": "state",
    "directory": "https://igod.gov.in/sg/MN/categories",
    "checked": "2026-09-28",
    "reviewDue": "2026-10-28",
    "verification": "directory_verified"
  },
  {
    "name": "Meghalaya",
    "code": "ML",
    "hi": "मेघालय",
    "te": "మేఘాలయ",
    "kind": "state",
    "directory": "https://igod.gov.in/sg/ML/categories",
    "checked": "2026-09-28",
    "reviewDue": "2026-10-28",
    "verification": "directory_verified"
  },
  {
    "name": "Mizoram",
    "code": "MZ",
    "hi": "मिजोरम",
    "te": "మిజోరం",
    "kind": "state",
    "directory": "https://igod.gov.in/sg/MZ/categories",
    "checked": "2026-09-28",
    "reviewDue": "2026-10-28",
    "verification": "directory_verified"
  },
  {
    "name": "Nagaland",
    "code": "NL",
    "hi": "नागालैंड",
    "te": "నాగాలాండ్",
    "kind": "state",
    "directory": "https://igod.gov.in/sg/NL/categories",
    "checked": "2026-09-28",
    "reviewDue": "2026-10-28",
    "verification": "directory_verified"
  },
  {
    "name": "Odisha",
    "code": "OD",
    "hi": "ओडिशा",
    "te": "ఒడిశా",
    "kind": "state",
    "directory": "https://igod.gov.in/sg/OD/categories",
    "checked": "2026-09-28",
    "reviewDue": "2026-10-28",
    "verification": "directory_verified"
  },
  {
    "name": "Puducherry",
    "code": "PY",
    "hi": "पुदुचेरी",
    "te": "పుదుచ్చేరి",
    "kind": "UT",
    "directory": "https://igod.gov.in/sg/PY/categories",
    "checked": "2026-09-28",
    "reviewDue": "2026-10-28",
    "verification": "directory_verified"
  },
  {
    "name": "Punjab",
    "code": "PB",
    "hi": "पंजाब",
    "te": "పంజాబ్",
    "kind": "state",
    "directory": "https://igod.gov.in/sg/PB/categories",
    "checked": "2026-09-28",
    "reviewDue": "2026-10-28",
    "verification": "directory_verified"
  },
  {
    "name": "Rajasthan",
    "code": "RJ",
    "hi": "राजस्थान",
    "te": "రాజస్థాన్",
    "kind": "state",
    "directory": "https://igod.gov.in/sg/RJ/categories",
    "checked": "2026-09-28",
    "reviewDue": "2026-10-28",
    "verification": "directory_verified"
  },
  {
    "name": "Sikkim",
    "code": "SK",
    "hi": "सिक्किम",
    "te": "సిక్కిం",
    "kind": "state",
    "directory": "https://igod.gov.in/sg/SK/categories",
    "checked": "2026-09-28",
    "reviewDue": "2026-10-28",
    "verification": "directory_verified"
  },
  {
    "name": "Tamil Nadu",
    "code": "TN",
    "hi": "तमिलनाडु",
    "te": "తమిళనాడు",
    "kind": "state",
    "directory": "https://igod.gov.in/sg/TN/categories",
    "checked": "2026-09-28",
    "reviewDue": "2026-10-28",
    "verification": "directory_verified"
  },
  {
    "name": "Telangana",
    "code": "TS",
    "hi": "तेलंगाना",
    "te": "తెలంగాణ",
    "kind": "state",
    "directory": "https://igod.gov.in/sg/TS/categories",
    "checked": "2026-09-28",
    "reviewDue": "2026-10-28",
    "verification": "directory_verified"
  },
  {
    "name": "Tripura",
    "code": "TR",
    "hi": "त्रिपुरा",
    "te": "త్రిపుర",
    "kind": "state",
    "directory": "https://igod.gov.in/sg/TR/categories",
    "checked": "2026-09-28",
    "reviewDue": "2026-10-28",
    "verification": "directory_verified"
  },
  {
    "name": "Uttar Pradesh",
    "code": "UP",
    "hi": "उत्तर प्रदेश",
    "te": "ఉత్తర ప్రదేశ్",
    "kind": "state",
    "directory": "https://igod.gov.in/sg/UP/categories",
    "checked": "2026-09-28",
    "reviewDue": "2026-10-28",
    "verification": "directory_verified"
  },
  {
    "name": "Uttarakhand",
    "code": "UK",
    "hi": "उत्तराखंड",
    "te": "ఉత్తరాఖండ్",
    "kind": "state",
    "directory": "https://igod.gov.in/sg/UK/categories",
    "checked": "2026-09-28",
    "reviewDue": "2026-10-28",
    "verification": "directory_verified"
  },
  {
    "name": "West Bengal",
    "code": "WB",
    "hi": "पश्चिम बंगाल",
    "te": "పశ్చిమ బెంగాల్",
    "kind": "state",
    "directory": "https://igod.gov.in/sg/WB/categories",
    "checked": "2026-09-28",
    "reviewDue": "2026-10-28",
    "verification": "directory_verified"
  }
] as const;
export function regionGuide(name:string){return regionalGuidance.find(r=>r.name===name)??null}
export function regionalRoute(name:string,serviceId:string){const r=regionGuide(name);if(!r)return null;return {region:r.name,url:(serviceId==='land'||serviceId==='flat')?(landPortals[name]??r.directory):r.directory,directory:r.directory,checked:r.checked,reviewDue:r.reviewDue,coverage:'official_directory_only' as const,automatedLocalEligibility:false};}
