import {regions} from './regions.ts';
export type Text3={en:string;hi:string;te:string};
const L=(en:string,hi:string,te:string):Text3=>({en,hi,te});
export const scenarioChecked='2026-09-28';
export const scenarioReviewBy='2026-10-12T00:00:00Z';
export const scenarioSources={
 farm:{name:'PM-KISAN · Agriculture Ministry',url:'https://pmkisan.gov.in/',published:'Undated portal; reviewed 28 September 2026'},
 bank:{name:'Agriculture Ministry · PIB',url:'https://www.pib.gov.in/PressReleseDetailm.aspx?PRID=2225989&lang=1&reg=3',published:'10 February 2026'},
 status:{name:'PM-KISAN · Know Your Status',url:'https://pmkisan.gov.in/BeneficiaryStatus_New.aspx',published:'Portal update label: 17 February 2026'},
 pension:{name:'Rural Development Ministry · PIB',url:'https://www.pib.gov.in/PressReleasePage.aspx?PRID=2210378&lang=1&reg=1',published:'1 January 2026'},
 portability:{name:'Government of India · PIB',url:'https://www.pib.gov.in/PressReleseDetailm.aspx?PRID=1847504',published:'2 August 2022; portability corroborated on DFPD portal'},
 ration:{name:'NFSA · Food and Public Distribution',url:'https://www.nfsa.gov.in/',published:'Undated portal; reviewed 28 September 2026'}
};
export type ServiceScenario={id:string;service:'farm'|'schemes'|'ration';title:Text3;fact:Text3;next:Text3;prepare:Text3;followup:Text3;source:keyof typeof scenarioSources;url:string};
export const serviceScenarios:ServiceScenario[]=[
 {id:'farm-unknown',service:'farm',source:'status',url:scenarioSources.status.url,
 title:L('Payment missing; I do not know why','पैसा नहीं आया; कारण नहीं पता','డబ్బు రాలేదు; కారణం తెలియదు'),
 fact:L('Know Your Status shows payment details, including bank, credit date and transaction reference. Saathi cannot see your record.','Know Your Status में बैंक, जमा तारीख और लेनदेन संदर्भ दिखते हैं। साथी आपका रिकॉर्ड नहीं देख सकता।','Know Your Statusలో బ్యాంకు, జమ తేదీ, లావాదేవీ రిఫరెన్స్ కనిపిస్తాయి. సాథీ మీ రికార్డు చూడలేదు.'),
 next:L('Open Know Your Status. Read the exact message, then choose the matching situation below. Do not guess the cause.','Know Your Status खोलें। सही संदेश पढ़कर नीचे उससे मिलता विकल्प चुनें। कारण का अनुमान न लगाएँ।','Know Your Status తెరవండి. సందేశం చదివి కింద తగిన పరిస్థితిని ఎంచుకోండి. కారణం ఊహించవద్దు.'),
 prepare:L('Keep your registration number and access to the registered phone privately. Use “Know Your Registration No.” there if needed.','पंजीकरण संख्या और पंजीकृत फ़ोन अपने पास रखें। ज़रूरत हो तो वहीं “Know Your Registration No.” चुनें।','నమోదు సంఖ్య, నమోదైన ఫోన్ మీ వద్ద ఉంచుకోండి. అవసరమైతే అక్కడ “Know Your Registration No.” ఎంచుకోండి.'),
 followup:L('If you cannot open the record, use the portal’s state/district Point of Contact search. Keep the enquiry reference.','रिकॉर्ड न खुले तो पोर्टल पर राज्य/ज़िला Point of Contact खोजें। पूछताछ का संदर्भ रखें।','రికార్డు తెరుచుకోకపోతే పోర్టల్‌లో రాష్ట్రం/జిల్లా Point of Contact వెతకండి. విచారణ రిఫరెన్స్ ఉంచుకోండి.')},
 {id:'farm-ekyc',service:'farm',source:'farm',url:'https://pmkisan.gov.in/',
 title:L('The message says eKYC is pending','संदेश में eKYC बाकी है','సందేశంలో eKYC పెండింగ్ ఉంది'),
 fact:L('PM-KISAN requires eKYC. Completing it is a verification step, not a guarantee that a payment is approved.','PM-KISAN में eKYC ज़रूरी है। इसे पूरा करना सत्यापन है, भुगतान की मंज़ूरी की गारंटी नहीं।','PM-KISANకు eKYC అవసరం. ఇది ధ్రువీకరణ దశ మాత్రమే; చెల్లింపు ఆమోదానికి హామీ కాదు.'),
 next:L('Use the official PM-KISAN app or ask a CSC/state-authorised operator about the biometric eKYC route listed on the portal.','आधिकारिक PM-KISAN ऐप इस्तेमाल करें या CSC/राज्य-अधिकृत ऑपरेटर से पोर्टल पर दी बायोमेट्रिक eKYC प्रक्रिया पूछें।','అధికారిక PM-KISAN యాప్ వాడండి లేదా పోర్టల్‌లో పేర్కొన్న బయోమెట్రిక్ eKYC కోసం CSC/రాష్ట్ర అధీకృత ఆపరేటర్‌ను అడగండి.'),
 prepare:L('Keep the pending message and any earlier eKYC receipt privately. Enter any OTP yourself only in the official service.','बाकी होने का संदेश और पुरानी eKYC रसीद रखें। OTP केवल आधिकारिक सेवा में खुद भरें।','పెండింగ్ సందేశం, గత eKYC రసీదు భద్రంగా ఉంచండి. OTPను అధికారిక సేవలో మీరే నమోదు చేయండి.'),
 followup:L('Recheck status after completion. If it still shows pending, raise the specific mismatch with the official Point of Contact; do not repeatedly register.','पूरा होने पर स्थिति फिर देखें। बाकी दिखे तो आधिकारिक संपर्क को वही समस्या बताएँ; बार-बार पंजीकरण न करें।','పూర్తయిన తర్వాత స్థితి చూడండి. ఇంకా పెండింగ్ ఉంటే అధికారిక సంప్రదింపు వ్యక్తికి అదే సమస్య చెప్పండి; మళ్లీ మళ్లీ నమోదు చేయవద్దు.')},
 {id:'farm-bank',service:'farm',source:'bank',url:'https://pmkisan.gov.in/SearchSNODetails.aspx',
 title:L('Aadhaar–bank linking is pending','आधार–बैंक लिंक बाकी है','ఆధార్–బ్యాంకు అనుసంధానం పెండింగ్'),
 fact:L('PM-KISAN payments use Aadhaar-seeded bank accounts. The ministry says payments cannot be processed when this linking is missing.','PM-KISAN भुगतान आधार से जुड़े बैंक खाते में होता है। मंत्रालय के अनुसार लिंक न होने पर भुगतान प्रोसेस नहीं होता।','PM-KISAN చెల్లింపులు ఆధార్ అనుసంధానిత బ్యాంకు ఖాతాకు వస్తాయి. అనుసంధానం లేకపోతే చెల్లింపులు ప్రాసెస్ కావని మంత్రిత్వ శాఖ తెలిపింది.'),
 next:L('Ask your bank to check Aadhaar seeding for benefit payments and the account being used. Completing PM-KISAN eKYC alone does not answer this bank issue.','बैंक से लाभ भुगतान के लिए आधार लिंक और इस्तेमाल हो रहा खाता जाँचने को कहें। केवल PM-KISAN eKYC से बैंक की यह समस्या स्पष्ट नहीं होती।','లబ్ధి చెల్లింపుల కోసం ఆధార్ అనుసంధానం, ఉపయోగించే ఖాతాను బ్యాంకులో తనిఖీ చేయించండి. PM-KISAN eKYC ఒక్కటే ఈ బ్యాంకు సమస్యకు సమాధానం కాదు.'),
 prepare:L('Take the exact status message and the bank’s requested identification privately. Ask for an acknowledgement of any correction.','सही स्थिति संदेश और बैंक द्वारा माँगी पहचान साथ रखें। सुधार की पावती लें।','స్థితి సందేశం, బ్యాంకు కోరిన గుర్తింపు పత్రాలు మీ వద్ద ఉంచండి. సవరణకు రసీదు అడగండి.'),
 followup:L('Compare the corrected bank record with PM-KISAN status. If they disagree, use the official state/district contact. No credit date is promised here.','सुधरे बैंक रिकॉर्ड की PM-KISAN स्थिति से तुलना करें। अंतर हो तो राज्य/ज़िला संपर्क लें। यहाँ जमा तारीख का वादा नहीं है।','సవరించిన బ్యాంకు రికార్డును PM-KISAN స్థితితో పోల్చండి. తేడా ఉంటే రాష్ట్రం/జిల్లా అధికారిని సంప్రదించండి. జమ తేదీకి ఇక్కడ హామీ లేదు.')},
 {id:'farm-verification',service:'farm',source:'farm',url:'https://pmkisan.gov.in/SearchSNODetails.aspx',
 title:L('Land or eligibility verification is pending','भूमि या पात्रता सत्यापन बाकी है','భూమి లేదా అర్హత ధ్రువీకరణ పెండింగ్'),
 fact:L('States/UTs identify eligible families. The portal says some suspected exclusion cases are held for physical verification. A delay alone does not identify your reason.','पात्र परिवार राज्य/UT पहचानते हैं। पोर्टल कुछ संदिग्ध अपात्रता मामलों में भौतिक सत्यापन तक रोक बताता है। केवल देरी से आपका कारण पता नहीं चलता।','అర్హ కుటుంబాలను రాష్ట్రాలు/UTలు గుర్తిస్తాయి. కొన్ని అనర్హత అనుమానాల కేసులు ప్రత్యక్ష ధ్రువీకరణ వరకు నిలిపినట్లు పోర్టల్ చెబుతోంది. ఆలస్యం ఒక్కటే మీ కారణాన్ని నిర్ధారించదు.'),
 next:L('Use Search your Point of Contact on PM-KISAN. Select your state/district and ask which recorded condition needs verification.','PM-KISAN पर Search your Point of Contact में राज्य/ज़िला चुनें। पूछें कि रिकॉर्ड की किस शर्त का सत्यापन बाकी है।','PM-KISANలో Search your Point of Contactలో రాష్ట్రం/జిల్లా ఎంచుకోండి. రికార్డులో ఏ షరతు ధ్రువీకరణ అవసరమో అడగండి.'),
 prepare:L('Keep the exact message, registration acknowledgement and relevant land records privately. Ask for a written correction or verification request.','सही संदेश, पंजीकरण पावती और संबंधित भूमि रिकॉर्ड रखें। सुधार या सत्यापन की लिखित माँग पूछें।','ఖచ్చితమైన సందేశం, నమోదు రసీదు, సంబంధిత భూమి రికార్డులు భద్రంగా ఉంచండి. సవరణ లేదా ధ్రువీకరణ అభ్యర్థనను రాతపూర్వకంగా అడగండి.'),
 followup:L('Follow up using the existing reference. Do not pay anyone promising to remove an eligibility hold. Only the authority decides the case.','पुराने संदर्भ से आगे पता करें। पात्रता की रोक हटाने का वादा करने वाले को पैसे न दें। निर्णय अधिकारी करता है।','పాత రిఫరెన్స్‌తోనే తదుపరి సమాచారం అడగండి. అర్హత నిలుపుదల తొలగిస్తామని చెప్పేవారికి డబ్బు ఇవ్వవద్దు. నిర్ణయం అధికారిదే.')},
 {id:'farm-credit',service:'farm',source:'status',url:scenarioSources.status.url,
 title:L('Status says credited, but I cannot find the money','जमा दिखता है, लेकिन पैसा नहीं मिला','జమ అయినట్లు ఉంది, కానీ డబ్బు కనిపించదు'),
 fact:L('The official status screen includes bank name, credited date and UTR transaction reference. A general instalment announcement is not your bank statement.','आधिकारिक स्थिति में बैंक, जमा तारीख और UTR संदर्भ है। सामान्य किस्त घोषणा आपका बैंक स्टेटमेंट नहीं है।','అధికారిక స్థితిలో బ్యాంకు పేరు, జమ తేదీ, UTR రిఫరెన్స్ ఉంటాయి. సాధారణ విడత ప్రకటన మీ బ్యాంకు స్టేట్‌మెంట్ కాదు.'),
 next:L('Compare those details with your bank statement. Ask the named bank to trace the credit using the UTR; do not make a fresh benefit application.','बैंक स्टेटमेंट से ये विवरण मिलाएँ। उसी बैंक से UTR द्वारा भुगतान खोजने को कहें; नया लाभ आवेदन न करें।','ఆ వివరాలను బ్యాంకు స్టేట్‌మెంట్‌తో పోల్చండి. చూపిన బ్యాంకును UTRతో చెల్లింపు వెతకమని అడగండి; కొత్త లబ్ధి దరఖాస్తు చేయవద్దు.'),
 prepare:L('Keep the status result, credited date, UTR and relevant statement privately. Never upload account numbers or statements here.','स्थिति, जमा तारीख, UTR और संबंधित स्टेटमेंट अपने पास रखें। यहाँ खाता संख्या या स्टेटमेंट अपलोड न करें।','స్థితి, జమ తేదీ, UTR, సంబంధిత స్టేట్‌మెంట్ భద్రంగా ఉంచండి. ఖాతా సంఖ్యలు లేదా స్టేట్‌మెంట్ ఇక్కడ ఇవ్వవద్దు.'),
 followup:L('If the bank cannot locate it, obtain its complaint reference and contact the PM-KISAN state/district official with both references.','बैंक न खोज पाए तो शिकायत संदर्भ लेकर PM-KISAN राज्य/ज़िला अधिकारी को दोनों संदर्भ दें।','బ్యాంకు గుర్తించలేకపోతే ఫిర్యాదు రిఫరెన్స్ తీసుకుని రెండు రిఫరెన్స్‌లతో PM-KISAN రాష్ట్రం/జిల్లా అధికారిని సంప్రదించండి.')},
 {id:'pension-oldage',service:'schemes',source:'pension',url:'https://www.myscheme.gov.in/',
 title:L('Old-age pension for a parent','माता-पिता की वृद्धावस्था पेंशन','తల్లిదండ్రులకు వృద్ధాప్య పెన్షన్'),
 fact:L('Central IGNOAPS covers eligible BPL people aged 60+. The central monthly share is ₹200 at 60–79 and ₹500 at 80+. State additions and approval differ. These are not your total sanctioned amounts.','केंद्रीय IGNOAPS पात्र BPL व्यक्तियों के लिए 60+ उम्र से है। केंद्रीय मासिक हिस्सा 60–79 में ₹200 और 80+ में ₹500 है। राज्य का अतिरिक्त हिस्सा और मंज़ूरी अलग हैं; यह आपकी कुल मंज़ूर राशि नहीं है।','కేంద్ర IGNOAPS అర్హ BPL వ్యక్తులకు 60+ వయస్సు నుంచి వర్తిస్తుంది. కేంద్ర నెలవారీ వాటా 60–79కు ₹200, 80+కు ₹500. రాష్ట్ర అదనపు మొత్తం, ఆమోదం వేరు; ఇవి మీ మొత్తం మంజూరు మొత్తాలు కావు.'),
 next:L('Check the parent’s age and whether the household is officially identified as BPL. On myScheme choose your state and compare IGNOAPS with the state pension scheme.','उम्र और परिवार की आधिकारिक BPL पहचान जाँचें। myScheme पर राज्य चुनकर IGNOAPS और राज्य पेंशन की शर्तें मिलाएँ।','వయస్సు, కుటుంబం అధికారికంగా BPLగా గుర్తించబడిందా చూడండి. mySchemeలో రాష్ట్రం ఎంచుకుని IGNOAPS, రాష్ట్ర పెన్షన్ నిబంధనలను పోల్చండి.'),
 prepare:L('Keep age evidence, BPL-status evidence if applicable and any existing pension reference. Confirm the local document list before a visit.','उम्र प्रमाण, लागू हो तो BPL प्रमाण और पुराना पेंशन संदर्भ रखें। जाने से पहले स्थानीय दस्तावेज़ सूची पूछें।','వయస్సు ఆధారం, వర్తిస్తే BPL ఆధారం, పాత పెన్షన్ రిఫరెన్స్ ఉంచండి. వెళ్లే ముందు స్థానిక పత్రాల జాబితా నిర్ధారించండి.'),
 followup:L('If under 60 or BPL status is unknown, this central route is not established. Ask the state social-welfare service about other support; do not assume all pensions are ruled out.','60 से कम उम्र या BPL अज्ञात हो तो यह केंद्रीय रास्ता पक्का नहीं। राज्य समाज कल्याण सेवा से दूसरी सहायता पूछें; सभी पेंशन से अपात्र न मानें।','60 కంటే తక్కువ లేదా BPL స్థితి తెలియకపోతే ఈ కేంద్ర మార్గం నిర్ధారణ కాలేదు. ఇతర సహాయం కోసం రాష్ట్ర సంక్షేమ సేవను అడగండి; అన్ని పెన్షన్లు రావని భావించవద్దు.')},
 {id:'pension-widow',service:'schemes',source:'pension',url:'https://www.myscheme.gov.in/',
 title:L('Support after a husband’s death','पति की मृत्यु के बाद सहायता','భర్త మరణం తర్వాత సహాయం'),
 fact:L('Central IGNWPS is a possible route for eligible BPL widows aged 40–79, with a ₹300 monthly central share; ₹500 at 80+. State schemes can differ. This is not approval.','केंद्रीय IGNWPS पात्र BPL विधवाओं के लिए 40–79 में ₹300 मासिक केंद्रीय हिस्सा, 80+ में ₹500 का संभावित रास्ता है। राज्य योजनाएँ अलग हो सकती हैं। यह मंज़ूरी नहीं है।','కేంద్ర IGNWPS అర్హ BPL వితంతువులకు 40–79లో నెలకు ₹300 కేంద్ర వాటా, 80+లో ₹500 ఉండే సాధ్యమైన మార్గం. రాష్ట్ర పథకాలు భిన్నంగా ఉండవచ్చు. ఇది ఆమోదం కాదు.'),
 next:L('Compare the central widow-pension conditions with your state’s scheme on myScheme. Confirm which authority accepts the application.','myScheme पर केंद्रीय विधवा पेंशन और राज्य योजना की शर्तें मिलाएँ। आवेदन लेने वाला विभाग पक्का करें।','mySchemeలో కేంద్ర వితంతు పెన్షన్, రాష్ట్ర పథకం షరతులు పోల్చండి. దరఖాస్తు స్వీకరించే అధికారిని నిర్ధారించండి.'),
 prepare:L('Keep age and death-registration evidence privately, plus BPL evidence if applicable. Ask the receiving authority for its exact list.','उम्र, मृत्यु-पंजीकरण और लागू हो तो BPL प्रमाण अपने पास रखें। विभाग से पूरी सूची पूछें।','వయస్సు, మరణ నమోదు ఆధారం, వర్తిస్తే BPL ఆధారం భద్రంగా ఉంచండి. స్వీకరించే శాఖ నుంచి పూర్తి జాబితా అడగండి.'),
 followup:L('If these central conditions do not fit, ask about state support rather than submitting under an incorrect category. No local amount or processing date is verified here.','केंद्रीय शर्तें न मिलें तो गलत श्रेणी में आवेदन की जगह राज्य सहायता पूछें। स्थानीय राशि या समय यहाँ सत्यापित नहीं है।','కేంద్ర షరతులు సరిపోకపోతే తప్పు కేటగిరీలో దరఖాస్తు చేయకుండా రాష్ట్ర సహాయం గురించి అడగండి. స్థానిక మొత్తం లేదా సమయం ఇక్కడ ధ్రువీకరించలేదు.')},
 {id:'pension-stopped',service:'schemes',source:'pension',url:'https://www.myscheme.gov.in/',
 title:L('An existing pension has stopped','मिल रही पेंशन रुक गई','వస్తున్న పెన్షన్ ఆగిపోయింది'),
 fact:L('Pension administration includes beneficiary and payment verification. A missed credit does not establish the cause; Saathi has no access to your pension account.','पेंशन में लाभार्थी और भुगतान सत्यापन होता है। जमा न आने से कारण तय नहीं होता; साथी आपका पेंशन खाता नहीं देख सकता।','పెన్షన్ నిర్వహణలో లబ్ధిదారు, చెల్లింపు ధ్రువీకరణ ఉంటుంది. డబ్బు రాకపోవడం వల్ల కారణం నిర్ధారణ కాదు; సాథీ మీ పెన్షన్ ఖాతా చూడలేదు.'),
 next:L('Identify the exact scheme from the last payment or sanction. Ask its state welfare office whether the issue is verification, sanction status or a returned bank payment.','पिछले भुगतान या मंज़ूरी से योजना पहचानें। राज्य कल्याण कार्यालय से पूछें: सत्यापन बाकी है, मंज़ूरी बदली है, या बैंक भुगतान लौटा है?','గత చెల్లింపు లేదా మంజూరు నుంచి పథకం గుర్తించండి. రాష్ట్ర సంక్షేమ కార్యాలయాన్ని అడగండి: ధ్రువీకరణ పెండింగా, మంజూరు స్థితి మారిందా, బ్యాంకు చెల్లింపు తిరిగిందా?'),
 prepare:L('Keep the last credited month, scheme/beneficiary reference and bank entry privately. Ask whether a life-verification step applies to this scheme.','आखिरी जमा महीना, योजना/लाभार्थी संदर्भ और बैंक एंट्री रखें। पूछें कि इस योजना में जीवन सत्यापन की ज़रूरत है या नहीं।','చివరిగా జమ అయిన నెల, పథకం/లబ్ధిదారు రిఫరెన్స్, బ్యాంకు ఎంట్రీ భద్రంగా ఉంచండి. ఈ పథకానికి జీవన ధ్రువీకరణ అవసరమా అడగండి.'),
 followup:L('Request the reason and complaint acknowledgement in writing, then use that department’s grievance route. Do not start a duplicate application merely because a payment is late.','कारण और शिकायत पावती लिखित में लें, फिर विभाग के शिकायत रास्ते से बढ़ें। केवल देरी पर दूसरा आवेदन न करें।','కారణం, ఫిర్యాదు రసీదు రాతపూర్వకంగా తీసుకుని శాఖ ఫిర్యాదు మార్గం వాడండి. ఆలస్యం వల్ల మాత్రమే రెండో దరఖాస్తు చేయవద్దు.')},
 {id:'ration-away',service:'ration',source:'portability',url:'https://www.nfsa.gov.in/',
 title:L('I am away from my home state','मैं अपने राज्य से बाहर हूँ','నేను నా రాష్ట్రానికి దూరంగా ఉన్నాను'),
 fact:L('ONORC lets existing NFSA beneficiaries use their existing ration card at an ePoS-enabled fair-price shop through biometric authentication. This does not issue a new card or establish new eligibility.','ONORC में मौजूदा NFSA लाभार्थी पुराने राशन कार्ड से ePoS वाली दुकान पर बायोमेट्रिक सत्यापन द्वारा राशन ले सकते हैं। इससे नया कार्ड या नई पात्रता नहीं बनती।','ONORC ద్వారా ప్రస్తుత NFSA లబ్ధిదారులు పాత రేషన్ కార్డుతో ePoS ఉన్న దుకాణంలో బయోమెట్రిక్ ధ్రువీకరణ ద్వారా రేషన్ పొందవచ్చు. ఇది కొత్త కార్డు లేదా కొత్త అర్హత ఇవ్వదు.'),
 next:L('Ask the destination fair-price shop to check ONORC portability and your remaining entitlement before travelling again or applying for another card.','दोबारा यात्रा या दूसरा कार्ड आवेदन करने से पहले गंतव्य दुकान से ONORC और बचा हक जाँचने को कहें।','మళ్లీ ప్రయాణం లేదా మరో కార్డుకు దరఖాస్తు చేసే ముందు గమ్యస్థాన దుకాణాన్ని ONORC, మిగిలిన కోటా తనిఖీ చేయమని అడగండి.'),
 prepare:L('Keep the existing card and the current month’s transaction receipts privately. Coordinate with family members who may already have collected part of the ration.','पुराना कार्ड और इस महीने की रसीदें रखें। परिवार ने कुछ राशन लिया हो तो उनसे मिलाकर देखें।','పాత కార్డు, ఈ నెల లావాదేవీ రసీదులు భద్రంగా ఉంచండి. కుటుంబ సభ్యులు కొంత రేషన్ తీసుకున్నారో తెలుసుకోండి.'),
 followup:L('If it fails, note whether the problem is authentication, the card record or quantity. Use the NFSA state food-department/grievance route with that reason.','न चले तो सत्यापन, कार्ड रिकॉर्ड या मात्रा में किसकी समस्या है लिखें। उसी कारण से NFSA राज्य खाद्य विभाग/शिकायत रास्ता लें।','విఫలమైతే ధ్రువీకరణ, కార్డు రికార్డు లేదా పరిమాణం—ఏ సమస్యో నమోదు చేసుకోండి. ఆ కారణంతో NFSA రాష్ట్ర ఆహార శాఖ/ఫిర్యాదు మార్గం వాడండి.')},
 {id:'ration-denied',service:'ration',source:'ration',url:'https://nfsa.gov.in/public/frmRegisterPublicGrievance.aspx',
 title:L('Ration refused, less quantity or failed authentication','राशन मना, कम मात्रा या सत्यापन विफल','రేషన్ నిరాకరణ, తక్కువ పరిమాణం లేదా ధ్రువీకరణ విఫలం'),
 fact:L('NFSA provides a grievance route for ration-service problems. A complaint is different from a new-card application; this screen files neither.','राशन सेवा की समस्या के लिए NFSA शिकायत रास्ता देता है। शिकायत और नए कार्ड का आवेदन अलग हैं; यहाँ दोनों जमा नहीं होते।','రేషన్ సేవ సమస్యలకు NFSA ఫిర్యాదు మార్గం అందిస్తుంది. ఫిర్యాదు, కొత్త కార్డు దరఖాస్తు వేరు; ఇక్కడ ఏదీ సమర్పించబడదు.'),
 next:L('Ask the shop for the exact reason or transaction result. On the official grievance page select the relevant state and describe the supply problem.','दुकान से सही कारण या लेनदेन नतीजा पूछें। आधिकारिक शिकायत पेज पर संबंधित राज्य और राशन की समस्या दें।','దుకాణం నుంచి ఖచ్చితమైన కారణం లేదా లావాదేవీ ఫలితం అడగండి. అధికారిక ఫిర్యాదు పేజీలో సంబంధిత రాష్ట్రం ఎంచుకుని సరఫరా సమస్య వివరించండి.'),
 prepare:L('Keep the shop name/ID, date, month, quantity requested/received and any receipt. Do not post ration-card numbers or biometrics here.','दुकान का नाम/ID, तारीख, महीना, माँगी/मिली मात्रा और रसीद रखें। यहाँ कार्ड नंबर या बायोमेट्रिक न दें।','దుకాణం పేరు/ID, తేదీ, నెల, కోరిన/అందిన పరిమాణం, రసీదు ఉంచండి. కార్డు సంఖ్యలు లేదా బయోమెట్రిక్స్ ఇక్కడ ఇవ్వవద్దు.'),
 followup:L('Keep the complaint acknowledgement. If the page is unavailable, use your state food department listed on NFSA and ask for its grievance officer. Resolution time is not verified here.','शिकायत पावती रखें। पेज न खुले तो NFSA में दिए राज्य खाद्य विभाग से शिकायत अधिकारी पूछें। समाधान का समय यहाँ पक्का नहीं।','ఫిర్యాదు రసీదు ఉంచండి. పేజీ పనిచేయకపోతే NFSAలోని రాష్ట్ర ఆహార శాఖను సంప్రదించి ఫిర్యాదు అధికారిని అడగండి. పరిష్కార సమయం ఇక్కడ ధ్రువీకరించలేదు.')},
 {id:'ration-card',service:'ration',source:'ration',url:'https://www.nfsa.gov.in/',
 title:L('New card, member change or pending application','नया कार्ड, सदस्य बदलाव या आवेदन बाकी','కొత్త కార్డు, సభ్యుల మార్పు లేదా పెండింగ్ దరఖాస్తు'),
 fact:L('NFSA links to state ration-card services. Household identification and the particular application process need state verification; selecting a state here does not prove entitlement.','NFSA राज्य राशन कार्ड सेवाओं के लिंक देता है। परिवार की पहचान और आवेदन प्रक्रिया राज्य से पक्की करनी होगी; यहाँ राज्य चुनने से हक सिद्ध नहीं होता।','NFSA రాష్ట్ర రేషన్ కార్డు సేవలకు లింకులు ఇస్తుంది. కుటుంబ గుర్తింపు, దరఖాస్తు ప్రక్రియను రాష్ట్రంతో నిర్ధారించాలి; ఇక్కడ రాష్ట్రం ఎంచుకోవడం అర్హతకు రుజువు కాదు.'),
 next:L('Open your state on NFSA and choose its ration-card management service. For an existing application, check the acknowledgement first instead of choosing new registration.','NFSA पर राज्य का राशन कार्ड प्रबंधन खोलें। पुराने आवेदन के लिए नया पंजीकरण चुनने से पहले पावती से स्थिति देखें।','NFSAలో మీ రాష్ట్ర రేషన్ కార్డు నిర్వహణ సేవ తెరవండి. పాత దరఖాస్తు ఉంటే కొత్త నమోదు ఎంచుకునే ముందు రసీదుతో స్థితి చూడండి.'),
 prepare:L('Identify the exact change and keep any existing card/application reference privately. Confirm the current state document list and published fee before a visit.','सही बदलाव पहचानें और पुराना कार्ड/आवेदन संदर्भ रखें। जाने से पहले वर्तमान राज्य दस्तावेज़ सूची और प्रकाशित शुल्क पूछें।','ఏ మార్పు కావాలో గుర్తించి పాత కార్డు/దరఖాస్తు రిఫరెన్స్ భద్రంగా ఉంచండి. వెళ్లే ముందు రాష్ట్ర పత్రాల జాబితా, ప్రచురించిన రుసుము తెలుసుకోండి.'),
 followup:L('For a stalled application, record the missing step and ask the state service for a correction or grievance reference. No approval or issue date is promised here.','रुके आवेदन का बाकी कदम लिखें और राज्य सेवा से सुधार या शिकायत संदर्भ लें। यहाँ मंज़ूरी या जारी तारीख का वादा नहीं।','ఆగిన దరఖాస్తులో మిగిలిన దశను తెలుసుకుని రాష్ట్ర సేవ నుంచి సవరణ లేదా ఫిర్యాదు రిఫరెన్స్ తీసుకోండి. ఇక్కడ ఆమోదం లేదా జారీ తేదీకి హామీ లేదు.')}
];
export function scenariosFor(service:string){return serviceScenarios.filter(s=>s.service===service)}
const goalTranslations:Record<string,Record<string,Text3>>={
 farm:{'Check PM-KISAN registration':L('Check PM-KISAN registration','PM-KISAN पंजीकरण जाँचें','PM-KISAN నమోదు చూడండి'),'Investigate a pending benefit':L('Investigate a pending benefit','रुके लाभ का कारण जानें','పెండింగ్ లబ్ధి కారణం తెలుసుకోండి')},
 schemes:{'Find pension or family support':L('Find pension or family support','पेंशन या परिवार सहायता खोजें','పెన్షన్ లేదా కుటుంబ సహాయం చూడండి'),'Resolve a pending benefit application':L('Resolve a pending benefit application','रुका लाभ आवेदन सुलझाएँ','పెండింగ్ లబ్ధి దరఖాస్తు పరిష్కరించండి')},
 ration:{'Apply or change household details':L('Apply or change household details','आवेदन या परिवार विवरण बदलें','దరఖాస్తు లేదా కుటుంబ వివరాలు మార్చండి'),'Resolve missing ration or a pending request':L('Resolve missing ration or a pending request','राशन न मिलने या रुके आवेदन में मदद','రేషన్ రాకపోవడం లేదా పెండింగ్ అభ్యర్థనకు సహాయం')}
};
export function scenarioGoalTitle(service:string,goal:string,language:keyof Text3){return goalTranslations[service]?.[goal]?.[language]??goal}
export function scenarioResult(service:string,id:string,region:string,now=Date.now()){
 if(!regions.includes(region as any))return {status:'region' as const,scenario:null};
 const scenario=scenariosFor(service).find(s=>s.id===id)??null;
 if(!scenario)return {status:'unknown' as const,scenario:null};
 if(!Number.isFinite(now)||now<Date.parse(scenarioChecked)||now>=Date.parse(scenarioReviewBy))return {status:'stale' as const,scenario:null};
 return {status:'guidance' as const,scenario};
}
