import {exactCountryVoice} from './country-config.ts';
export type SpeechSession={speak:(text:string,rate:number)=>Promise<void>;listen:()=>Promise<string>;stop:()=>void};
export function createSpeechSession(onPhase:(phase:'speaking'|'listening'|'ready')=>void,locale='en-IN'):SpeechSession{
 let cancelCurrent:(()=>void)|undefined;let generation=0;
 const native=()=>typeof window!=='undefined'?(window as any).saathiNative:undefined;
 function stop(){generation++;const cancel=cancelCurrent;cancelCurrent=undefined;cancel?.();window.speechSynthesis?.cancel();native()?.stop?.();onPhase('ready')}
 async function nativeCall(method:'speak'|'listen',args:any[]){const token=generation;return new Promise<any>((resolve,reject)=>{let done=false;const finish=(value?:any,error?:Error)=>{if(done)return;done=true;clearTimeout(timer);if(token===generation)cancelCurrent=undefined;onPhase('ready');error?reject(error):resolve(value)};const timer=window.setTimeout(()=>{native()?.stop?.();finish(undefined,new Error('Speech timed out.'))},method==='speak'?90000:20000);cancelCurrent=()=>finish(undefined,new Error('cancelled'));Promise.resolve(native()[method](...args)).then(v=>finish(v),e=>finish(undefined,new Error(String(e?.message??e))))})}
 return {stop,async speak(text,rate){stop();onPhase('speaking');if(native())return nativeCall('speak',[text,rate,locale]);if(!window.speechSynthesis)throw new Error('Spoken audio is unavailable.');return new Promise<void>((resolve,reject)=>{let settled=false;const token=generation;const utterance=new SpeechSynthesisUtterance(text);utterance.lang=locale;utterance.rate=rate;const voices=window.speechSynthesis.getVoices();const voice=exactCountryVoice(voices,locale);if(voice)utterance.voice=voice;else {onPhase('ready');reject(new Error('Install an Indian speech voice for this language, then retry.'));return}const finish=(error?:Error)=>{if(settled)return;settled=true;clearTimeout(timer);utterance.onend=null;utterance.onerror=null;if(token===generation)cancelCurrent=undefined;onPhase('ready');error?reject(error):resolve()};const timer=window.setTimeout(()=>{finish(new Error('Audio timed out.'));window.speechSynthesis.cancel()},90000);cancelCurrent=()=>finish(new Error('cancelled'));utterance.onend=()=>finish();utterance.onerror=()=>finish(new Error('Audio could not play.'));window.speechSynthesis.speak(utterance)})},async listen(){stop();onPhase('listening');if(native())return nativeCall('listen',[locale]);const Speech=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!Speech){onPhase('ready');throw new Error('Voice recognition is unavailable in this browser.')}return new Promise<string>((resolve,reject)=>{const token=generation;const rec=new Speech();let settled=false;rec.lang=locale;rec.continuous=false;rec.interimResults=false;rec.maxAlternatives=1;const finish=(value?:string,error?:Error)=>{if(settled)return;settled=true;clearTimeout(timer);rec.onresult=rec.onerror=rec.onend=null;rec.abort();if(token===generation)cancelCurrent=undefined;onPhase('ready');error?reject(error):resolve(value??'')};const timer=window.setTimeout(()=>finish(undefined,new Error('No speech heard within 15 seconds.')),15000);cancelCurrent=()=>finish(undefined,new Error('cancelled'));rec.onresult=(e:any)=>{const r=e.results?.[0]?.[0];if(!r?.transcript||(r.confidence>0&&r.confidence<.45)){finish(undefined,new Error('Speech was unclear.'));return}finish(String(r.transcript).slice(0,300))};rec.onerror=()=>finish(undefined,new Error('Speech could not be recognized. Check microphone permission and connection.'));rec.onend=()=>finish(undefined,new Error('No answer was heard.'));try{rec.start()}catch{finish(undefined,new Error('Microphone could not start.'))}})}}
}
