import {services} from './services.ts';
import {regions} from './regions.ts';
import {hasIdentityNumber} from './private-input.ts';
export const travel=[
 {id:'rail',title:'Railway tickets',source:'https://www.irctc.co.in/',steps:['Review your route and travel date.','Check live availability, full fare and cancellation terms on IRCTC.','Confirm and pay only on the provider. Keep its booking confirmation.']},
 {id:'flight',title:'Airplane tickets',source:'',steps:['Review your route, date and traveller count.','Choose an airline or authorised booking provider and check live fares, baggage and cancellation terms.','Confirm and pay only on the provider. Keep its booking confirmation.']},
 {id:'cab',title:'Cab comparison & booking',source:'',steps:['Review your pickup area, destination and time.','Compare current total fares and waiting/cancellation charges in available cab apps.','Confirm the pickup and booking with the chosen provider. Saathi has no live quotes and cannot identify the cheapest cab.']},
 {id:'holiday',title:'Holiday planning & booking',source:'',steps:['Review your destination, dates, traveller count and budget.','Choose travel and accommodation providers and check availability, total costs and refund terms.','Confirm each reservation with its provider. Saathi has not reserved anything.']}
];
export const workflows=[...services,...travel].map(s=>({id:s.id,title:s.title,source:s.source,steps:s.steps,providerStatus:'not_connected' as const,transactionEnabled:false,fields:travel.some(t=>t.id===s.id)?['origin','destination','date','travellers','budget']:['region','goal']}));
export type Task={serviceId:string;answers:Record<string,string>;status:'collecting'|'review'|'handoff';events:{event:string;at:string}[]};
export function startTask(id:string):Task{if(!workflows.some(w=>w.id===id))throw Error('Unknown service');return {serviceId:id,answers:{},status:'collecting',events:[{event:'started',at:new Date().toISOString()}]}}
export function nextField(task:Task){return workflows.find(w=>w.id===task.serviceId)!.fields.find(f=>!task.answers[f])}
export function answerTask(task:Task,value:string):Task{if(task.status!=='collecting')throw Error('Review or restart this task.');const key=nextField(task)!;const v=value.trim();if(!v||v.length>250)throw Error('Use a short answer, up to 250 characters.');if(hasIdentityNumber(v)||/\b(otp|pin|password|cvv)\b|@/i.test(v))throw Error('Do not enter identity numbers, passwords, OTPs or private contact details.');if(key==='region'&&!regions.includes(v as any))throw Error('Choose a listed Indian State or Union Territory.');if(key==='travellers'&&(!/^\d{1,2}$/.test(v)||+v<1||+v>20))throw Error('Enter a traveller count from 1 to 20.');if(key==='budget'&&(!/^\d{1,7}$/.test(v)||+v<1))throw Error('Enter a positive budget in rupees.');if(key==='date'){const d=new Date(v+'T00:00:00Z');const today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'});if(!/^\d{4}-\d{2}-\d{2}$/.test(v)||!Number.isFinite(d.getTime())||d.toISOString().slice(0,10)!==v||v<today)throw Error('Choose today or a future date.');}const next={...task,answers:{...task.answers,[key]:v},events:[...task.events,{event:'answered:'+key,at:new Date().toISOString()}]};if(!nextField(next))next.status='review';return next;}
export function confirmTask(task:Task):Task{if(task.status!=='review'||nextField(task))throw Error('Complete and review your details first.');return {...task,status:'handoff',events:[...task.events,{event:'details_confirmed_not_submitted',at:new Date().toISOString()}]};}
export function executeTask(_task:Task):never{throw Error('Provider not connected. No booking, payment or application has been submitted.');}
export function matchTasks(query:string){const q=query.toLowerCase().trim();if(q.length<3)return [];const aliases:Record<string,string[]>={rail:['train','railway','रेल','రైలు'],flight:['flight','airplane','विमान','విమానం'],cab:['cab','taxi','टैक्सी','క్యాబ్'],holiday:['holiday','hotel','vacation','छुट्टी','విహార'],aadhaar:['aadhaar','aadhar','आधार','ఆధార్']};return workflows.filter(w=>[w.title.toLowerCase(),...(aliases[w.id]??[])].some(term=>q.includes(term)||term.includes(q))).sort((a,b)=>Number((aliases[b.id]??[]).some(t=>q.includes(t)))-Number((aliases[a.id]??[]).some(t=>q.includes(t)))).slice(0,6);}
