import type {DirectoryLanguage} from './service-directory.ts';

export const taskCopy={
 en:{close:'Close guide',open:'Plan a task — travel, documents or family services',question:'What would you like to do?',preview:'Guided preview · no booking or application is submitted here. This uses structured workflows; no general AI model is connected. Answers stay in this tab and are cleared when you close or restart.',language:'Spoken guidance language',languageNote:'English guidance is available. Hindi and Telugu are review previews.',describe:'Describe your task',requestPlaceholder:'Book a train, update Aadhaar, find document help…',speakRequest:'Speak your request',choose:'Choose the matching service below. Your spoken text is not submitted.',chooseRegion:'Choose region',listenQuestion:'Listen to question',speakAnswer:'Speak answer',confirm:'Confirm answer & continue',review:'Check your details',confirmDetails:'These details are correct — show next steps',status:'Prepared · not submitted · official approval required',next:'Your next action',listen:'Listen',show:'Show steps',reminder:'Save reminder',help:'Get help',checklist:'Checklist before you continue',connection:'Connection status',official:'Official handoff only',guidance:'Guidance only · no provider selected',works:'What works here',notConnected:'Not connected',notSent:'Your answers have not been sent to the provider. Enter login, identity and payment details only after you open and verify the official service.',offline:'You are offline. Reconnect before opening the official service; cached steps may be outdated.',reconnect:'Reconnect to open',openOfficial:'Open official service · new screen',chooseProvider:'Choose a provider you trust. Provider search and booking are unavailable here.',region:'Applicable region',regionTitle:'Check your State/UT route',regionInfo:'This verified government directory helps you locate the responsible regional service. It does not prove local online availability or eligibility.',openRegion:'Open official regional route',openDirectory:'Open government department directory',directoryChecked:'Directory checked',reviewDue:'review due',localEligibility:'local eligibility is not automated',onlyOfficial:'Only a confirmation from the official service or provider proves completion.',progress:'Task progress in this session',restart:'Start again / clear answers',stop:'Stop audio',gaps:'See all integration gaps',important:'Important',englishDetail:'Service-specific caution in English:',guided:'Guided questions and a preparation checklist',handoff:'Official service handoff link',providerChoice:'Provider-selection guidance; no booking provider is selected',started:'Task started',answered:'Answer added',confirmed:'Details confirmed · not submitted',updated:'Progress updated'},
 hi:{close:'मार्गदर्शन बंद करें',open:'काम की योजना बनाएँ — यात्रा, दस्तावेज़ या परिवार सेवा',question:'आप क्या करना चाहते हैं?',preview:'मार्गदर्शित पूर्वावलोकन · यहाँ कोई बुकिंग या आवेदन जमा नहीं होता। यह तय नियमों वाला मार्गदर्शन है; सामान्य AI मॉडल जुड़ा नहीं है। जवाब इसी टैब में रहते हैं और बंद या दोबारा शुरू करने पर मिट जाते हैं।',language:'आवाज़ में मार्गदर्शन की भाषा',languageNote:'हिन्दी और तेलुगु मार्गदर्शन समीक्षा पूर्वावलोकन हैं।',describe:'अपना काम बताएँ',requestPlaceholder:'रेल टिकट, आधार अपडेट या दस्तावेज़ सहायता…',speakRequest:'अपनी ज़रूरत बोलें',choose:'नीचे सही सेवा चुनें। आपकी बोली हुई बात जमा नहीं की जाती।',chooseRegion:'राज्य या केंद्र शासित प्रदेश चुनें',listenQuestion:'सवाल सुनें',speakAnswer:'जवाब बोलें',confirm:'जवाब पक्का करें और आगे बढ़ें',review:'अपनी जानकारी जाँचें',confirmDetails:'जानकारी सही है — अगले कदम दिखाएँ',status:'तैयार · जमा नहीं हुआ · आधिकारिक मंज़ूरी ज़रूरी',next:'आपका अगला कदम',listen:'सुनें',show:'कदम दिखाएँ',reminder:'याद दिलाने के लिए सहेजें',help:'मदद लें',checklist:'आगे बढ़ने से पहले सूची',connection:'सेवा की स्थिति',official:'केवल आधिकारिक सेवा का लिंक',guidance:'केवल मार्गदर्शन · सेवा प्रदाता नहीं चुना गया',works:'यहाँ क्या उपलब्ध है',notConnected:'क्या जुड़ा नहीं है',notSent:'आपके जवाब सेवा प्रदाता को नहीं भेजे गए हैं। लॉगिन, पहचान और भुगतान की जानकारी केवल आधिकारिक सेवा खोलकर जाँचने के बाद दें।',offline:'आप ऑफलाइन हैं। आधिकारिक सेवा खोलने से पहले इंटरनेट जोड़ें; सहेजे गए कदम पुराने हो सकते हैं।',reconnect:'इंटरनेट जोड़कर खोलें',openOfficial:'आधिकारिक सेवा खोलें · नई स्क्रीन',chooseProvider:'विश्वसनीय सेवा प्रदाता चुनें। यहाँ सेवा खोज और बुकिंग उपलब्ध नहीं है।',region:'लागू क्षेत्र',regionTitle:'अपने राज्य या केंद्र शासित प्रदेश की सेवा देखें',regionInfo:'यह सत्यापित सरकारी निर्देशिका संबंधित क्षेत्रीय सेवा खोजने में मदद करती है। इससे स्थानीय ऑनलाइन उपलब्धता या पात्रता सिद्ध नहीं होती।',openRegion:'आधिकारिक क्षेत्रीय सेवा खोलें',openDirectory:'सरकारी विभाग निर्देशिका खोलें',directoryChecked:'निर्देशिका जाँच की तारीख',reviewDue:'अगली समीक्षा',localEligibility:'स्थानीय पात्रता अपने आप तय नहीं होती',onlyOfficial:'काम पूरा होने की पुष्टि केवल आधिकारिक सेवा या प्रदाता से होती है।',progress:'इस सत्र में काम की प्रगति',restart:'दोबारा शुरू करें / जवाब मिटाएँ',stop:'आवाज़ रोकें',gaps:'सभी उपलब्ध और अनुपलब्ध सुविधाएँ देखें',important:'ज़रूरी सूचना',englishDetail:'सेवा की विशेष सावधानी अंग्रेज़ी में:',guided:'सरल सवाल और तैयारी की सूची',handoff:'आधिकारिक सेवा का लिंक',providerChoice:'सेवा चुनने का मार्गदर्शन; बुकिंग प्रदाता नहीं चुना गया',started:'काम शुरू हुआ',answered:'जवाब जोड़ा गया',confirmed:'जानकारी पक्की की · जमा नहीं हुई',updated:'प्रगति बदली'},
 te:{close:'మార్గదర్శనం మూసివేయండి',open:'పని సిద్ధం చేయండి — ప్రయాణం, పత్రాలు లేదా కుటుంబ సేవ',question:'మీరు ఏ పని చేయాలనుకుంటున్నారు?',preview:'మార్గదర్శక ముందస్తు రూపం · ఇక్కడ బుకింగ్ లేదా దరఖాస్తు సమర్పించబడదు. ఇది నిర్ణీత నియమాల మార్గదర్శనం; సాధారణ AI మోడల్ అనుసంధానం కాలేదు. సమాధానాలు ఈ ట్యాబ్‌లోనే ఉంటాయి; మూసినా, మళ్లీ ప్రారంభించినా తొలగిపోతాయి.',language:'వాయిస్ మార్గదర్శక భాష',languageNote:'హిందీ, తెలుగు మార్గదర్శనం సమీక్ష ముందస్తు రూపం.',describe:'మీ పని వివరించండి',requestPlaceholder:'రైలు టికెట్, ఆధార్ మార్పు లేదా పత్రాల సహాయం…',speakRequest:'మీ అవసరం చెప్పండి',choose:'కింద సరైన సేవను ఎంచుకోండి. మీరు చెప్పిన మాటలు సమర్పించబడవు.',chooseRegion:'రాష్ట్రం లేదా కేంద్ర పాలిత ప్రాంతం ఎంచుకోండి',listenQuestion:'ప్రశ్న వినండి',speakAnswer:'సమాధానం చెప్పండి',confirm:'సమాధానం నిర్ధారించి కొనసాగండి',review:'మీ వివరాలు పరిశీలించండి',confirmDetails:'వివరాలు సరైనవి — తదుపరి దశలు చూపండి',status:'సిద్ధం · సమర్పించలేదు · అధికారిక ఆమోదం అవసరం',next:'మీ తదుపరి పని',listen:'వినండి',show:'దశలు చూపండి',reminder:'గుర్తు చేయడానికి భద్రపరచండి',help:'సహాయం పొందండి',checklist:'కొనసాగించే ముందు జాబితా',connection:'సేవ స్థితి',official:'అధికారిక సేవకు లింక్ మాత్రమే',guidance:'మార్గదర్శనం మాత్రమే · సేవాదారు ఎంపిక కాలేదు',works:'ఇక్కడ ఏమి అందుబాటులో ఉంది',notConnected:'ఏమి అనుసంధానం కాలేదు',notSent:'మీ సమాధానాలు సేవాదారుకు పంపబడలేదు. అధికారిక సేవను తెరిచి నిర్ధారించిన తర్వాత మాత్రమే లాగిన్, గుర్తింపు, చెల్లింపు వివరాలు ఇవ్వండి.',offline:'మీరు ఆఫ్‌లైన్‌లో ఉన్నారు. అధికారిక సేవ తెరవడానికి ముందు ఇంటర్నెట్ కలపండి; భద్రపరచిన దశలు పాతవి కావచ్చు.',reconnect:'ఇంటర్నెట్ కలిపి తెరవండి',openOfficial:'అధికారిక సేవ తెరవండి · కొత్త తెర',chooseProvider:'మీరు నమ్మే సేవాదారును ఎంచుకోండి. ఇక్కడ సేవ శోధన, బుకింగ్ అందుబాటులో లేవు.',region:'వర్తించే ప్రాంతం',regionTitle:'మీ రాష్ట్రం లేదా కేంద్ర పాలిత ప్రాంత సేవ చూడండి',regionInfo:'ఈ ధృవీకరించిన ప్రభుత్వ డైరెక్టరీ సంబంధిత ప్రాంతీయ సేవను గుర్తించడానికి సహాయపడుతుంది. ఇది స్థానిక ఆన్‌లైన్ అందుబాటు లేదా అర్హతను నిర్ధారించదు.',openRegion:'అధికారిక ప్రాంతీయ సేవ తెరవండి',openDirectory:'ప్రభుత్వ శాఖల డైరెక్టరీ తెరవండి',directoryChecked:'డైరెక్టరీ పరిశీలించిన తేదీ',reviewDue:'తదుపరి సమీక్ష',localEligibility:'స్థానిక అర్హత స్వయంచాలకంగా నిర్ణయించబడదు',onlyOfficial:'పని పూర్తయినట్లు అధికారిక సేవ లేదా సేవాదారు మాత్రమే నిర్ధారిస్తారు.',progress:'ఈ సెషన్‌లో పని పురోగతి',restart:'మళ్లీ ప్రారంభించండి / సమాధానాలు తొలగించండి',stop:'ఆడియో ఆపండి',gaps:'అందుబాటులో ఉన్నవి, లేనివి చూడండి',important:'ముఖ్యమైన సమాచారం',englishDetail:'సేవకు సంబంధించిన ప్రత్యేక జాగ్రత్త ఇంగ్లీష్‌లో:',guided:'సరళమైన ప్రశ్నలు, సిద్ధం చేసుకునే జాబితా',handoff:'అధికారిక సేవకు లింక్',providerChoice:'సేవాదారు ఎంపిక మార్గదర్శనం; బుకింగ్ సేవాదారు ఎంపిక కాలేదు',started:'పని ప్రారంభమైంది',answered:'సమాధానం చేర్చబడింది',confirmed:'వివరాలు నిర్ధారించబడ్డాయి · సమర్పించలేదు',updated:'పురోగతి మారింది'}
} satisfies Record<DirectoryLanguage,Record<string,string>>;

const providerTranslations:Record<'hi'|'te',Record<string,string>>={
 hi:{'Guided questions and a preparation checklist':'सरल सवाल और तैयारी की सूची','Provider-selection guidance; no booking provider is selected':'सेवा चुनने का मार्गदर्शन; बुकिंग प्रदाता नहीं चुना गया','Live availability, prices or provider tracking':'लाइव उपलब्धता, कीमत या सेवा की स्थिति','Reservation, booking, payment or cancellation':'आरक्षण, बुकिंग, भुगतान या रद्द करना','Live rates, quotes, recommendations or account status':'लाइव दर, भाव, सिफारिश या खाते की स्थिति','Application, purchase, trade, payment or approval':'आवेदन, खरीद, ट्रेड, भुगतान या मंज़ूरी','Diagnosis, clinical triage or provider availability':'बीमारी की पहचान, चिकित्सकीय जाँच या सेवा की उपलब्धता','Consultation booking, payment or medical-record access':'परामर्श बुकिंग, भुगतान या चिकित्सा रिकॉर्ड','Provider account, application or status inside Saathi':'साथी में सेवा खाता, आवेदन या स्थिति','Submission, payment, appointment or official approval':'जमा करना, भुगतान, अपॉइंटमेंट या आधिकारिक मंज़ूरी'},
 te:{'Guided questions and a preparation checklist':'సరళమైన ప్రశ్నలు, సిద్ధం చేసుకునే జాబితా','Provider-selection guidance; no booking provider is selected':'సేవాదారు ఎంపిక మార్గదర్శనం; బుకింగ్ సేవాదారు ఎంపిక కాలేదు','Live availability, prices or provider tracking':'ప్రత్యక్ష అందుబాటు, ధరలు లేదా సేవ స్థితి','Reservation, booking, payment or cancellation':'రిజర్వేషన్, బుకింగ్, చెల్లింపు లేదా రద్దు','Live rates, quotes, recommendations or account status':'ప్రత్యక్ష రేట్లు, ధరలు, సిఫార్సులు లేదా ఖాతా స్థితి','Application, purchase, trade, payment or approval':'దరఖాస్తు, కొనుగోలు, ట్రేడ్, చెల్లింపు లేదా ఆమోదం','Diagnosis, clinical triage or provider availability':'రోగ నిర్ధారణ, వైద్య ప్రాథమిక అంచనా లేదా సేవ అందుబాటు','Consultation booking, payment or medical-record access':'సంప్రదింపు బుకింగ్, చెల్లింపు లేదా వైద్య రికార్డులు','Provider account, application or status inside Saathi':'సాథీలో సేవ ఖాతా, దరఖాస్తు లేదా స్థితి','Submission, payment, appointment or official approval':'సమర్పణ, చెల్లింపు, అపాయింట్‌మెంట్ లేదా అధికారిక ఆమోదం'}
};

export function localizeProviderItem(item:string,language:DirectoryLanguage){
 if(language==='en')return item;
 if(item.startsWith('A handoff link to '))return taskCopy[language].handoff;
 return providerTranslations[language][item]??item;
}

const errorTranslations:Record<'hi'|'te',Record<string,string>>={
 hi:{'Review or restart this task.':'इस काम की जानकारी जाँचें या दोबारा शुरू करें।','Use a short answer, up to 250 characters.':'250 अक्षरों तक छोटा जवाब दें।','Do not enter identity numbers, passwords, OTPs or private contact details.':'पहचान संख्या, पासवर्ड, OTP या निजी संपर्क जानकारी न डालें।','Choose a listed Indian State or Union Territory.':'सूची में दिया भारतीय राज्य या केंद्र शासित प्रदेश चुनें।','Enter a traveller count from 1 to 20.':'यात्रियों की संख्या 1 से 20 तक डालें।','Enter a positive budget in rupees.':'रुपये में शून्य से अधिक बजट डालें।','Choose today or a future date.':'आज या आगे की तारीख चुनें।','Complete and review your details first.':'पहले अपनी जानकारी पूरी करके जाँचें।'},
 te:{'Review or restart this task.':'ఈ పని వివరాలు పరిశీలించండి లేదా మళ్లీ ప్రారంభించండి.','Use a short answer, up to 250 characters.':'250 అక్షరాల వరకు చిన్న సమాధానం ఇవ్వండి.','Do not enter identity numbers, passwords, OTPs or private contact details.':'గుర్తింపు సంఖ్యలు, పాస్‌వర్డ్‌లు, OTPలు లేదా వ్యక్తిగత సంప్రదింపు వివరాలు నమోదు చేయవద్దు.','Choose a listed Indian State or Union Territory.':'జాబితాలో ఉన్న భారత రాష్ట్రం లేదా కేంద్ర పాలిత ప్రాంతం ఎంచుకోండి.','Enter a traveller count from 1 to 20.':'ప్రయాణికుల సంఖ్య 1 నుంచి 20 వరకు నమోదు చేయండి.','Enter a positive budget in rupees.':'రూపాయల్లో సున్నా కంటే ఎక్కువ బడ్జెట్ నమోదు చేయండి.','Choose today or a future date.':'ఈ రోజు లేదా భవిష్యత్తు తేదీ ఎంచుకోండి.','Complete and review your details first.':'ముందుగా మీ వివరాలు పూర్తి చేసి పరిశీలించండి.'}
};
export function localizeTaskError(message:string,language:DirectoryLanguage){if(language==='en')return message;return errorTranslations[language][message]??taskCopy[language].updated}
export function taskEventLabel(event:string,language:DirectoryLanguage){const c=taskCopy[language];if(event==='started')return c.started;if(event.startsWith('answered:'))return c.answered;if(event==='details_confirmed_not_submitted')return c.confirmed;return c.updated}
