import {services} from './services.ts';
import {regions} from './regions.ts';
import {evaluatePension} from './rules.ts';
export type VoiceState={stage:'topic'|'confirm'|'region'|'steps'|'age'|'age_confirm'|'bpl'|'pension_result'|'reminder_title'|'reminder_date'|'reminder_confirm'|'complete'|'emergency';prompt:string;region:string;serviceId?:string;step:number;age?:number|null;title?:string;due?:string;link?:string;paused?:boolean;resumePrompt?:string};
export type VoiceResult={state:VoiceState;effect?:'save_reminder'|'pause'|'offer_link'};
const normal=(s:string)=>s.toLowerCase().replace(/[’']/g,'').replace(/[^a-z0-9\s-]/g,' ').replace(/\s+/g,' ').trim();
const yes=(s:string)=>/^(yes|yes please|correct|thats right|confirm|save|save it|okay|ok|go ahead|right)$/.test(s);
const no=(s:string)=>/^(no|no thanks|incorrect|wrong|not correct)$/.test(s);
export const serviceAliases:Record<string,string[]>={water:['water','drinking water'],sanitation:['toilet','sanitation'],transport:['bus','transport'],women:['self help group','women group','shg'],nutrition:['nutrition','anganwadi'],farmweather:['weather','forecast','seasonal farming'],jobcard:['job card','nrega'],pension:['pension','old age','elderly'],ration:['ration','food card','food support'],health:['health card','ayushman','hospital'],telemedicine:['doctor','telemedicine','consultation'],education:['scholarship','school fees'],learning:['school learning','homework','lessons'],farm:['pm kisan','farmer support','farm support'],jobs:['job','jobs','employment'],documents:['income certificate','caste certificate','residence certificate','certificate','document'],land:['land registration','land records','land','mutation','survey number'],flat:['flat','apartment','rera','property purchase'],stocks:['stocks','stock','shares','investing','investment'],schemes:['scheme','benefit','widow','women support'],grievance:['government complaint','grievance'],credit:['loan','loans','credit'],workers:['e shram','eshram','worker registration'],fraud:['fraud','scam','cybercrime'],aadhaar:['aadhaar','aadhar'],digilocker:['digilocker','digital locker'],driving:['driving','licence','license','vehicle','rc renewal'],voter:['voter','voting','electoral'],passport:['passport'],birthdeath:['birth certificate','death certificate'],disability:['disability','disabled','udid'],housing:['housing','pmay','house scheme'],lpg:['lpg','gas connection','gas cylinder','ujjwala'],legal:['legal aid','lawyer','court case'],consumer:['consumer','refund','product complaint'],cropinsurance:['crop insurance','pmfby'],markets:['mandi','crop price','market price','enam'],skills:['skill','training','course'],business:['udyam','business registration','msme'],reminder:['reminder','remind','appointment']};
export function matchTopic(raw:string):string|null {const s=normal(raw);if(/\b(emergency|unconscious|bleeding|chest pain|cannot breathe|cant breathe|accident|gas leak|fire)\b/.test(s))return 'emergency';let best:string|null=null,score=0,tie=false;for(const [id,aliases]of Object.entries(serviceAliases)){if(id!=='pension'&&id!=='reminder'&&!services.some(v=>v.id===id))continue;for(const alias of aliases){const found=(' '+s+' ').includes(' '+alias+' ');if(found&&alias.length>score){score=alias.length;best=id;tie=false}else if(found&&alias.length===score&&best!==id)tie=true}}return tie?null:best;}
export function parseRegion(raw:string):string|null{const s=normal(raw);const alias:Record<string,string>={'ap':'Andhra Pradesh','up':'Uttar Pradesh','mp':'Madhya Pradesh','orissa':'Odisha','pondicherry':'Puducherry','new delhi':'Delhi','jammu kashmir':'Jammu and Kashmir','andaman nicobar':'Andaman and Nicobar Islands'};if(alias[s])return alias[s];const found=regions.filter(r=>(' '+s+' ').includes(' '+normal(r)+' '));return found.length===1?found[0]:null;}
const numberWords:Record<string,number>={zero:0,one:1,two:2,three:3,four:4,five:5,six:6,seven:7,eight:8,nine:9,ten:10,eleven:11,twelve:12,thirteen:13,fourteen:14,fifteen:15,sixteen:16,seventeen:17,eighteen:18,nineteen:19,twenty:20,thirty:30,forty:40,fifty:50,sixty:60,seventy:70,eighty:80,ninety:90};
export function parseAge(raw:string):number|null{if(/-\s*\d|minus|negative|\d\.\d/i.test(raw))return null;const s=normal(raw).replace(/-/g,' ');const digits=s.match(/\b\d+\b/g);if(digits){if(digits.length!==1)return null;const n=Number(digits[0]);return n<=120?n:null}const cleaned=s.replace(/^(she is|he is|i am|age is|age|about) /,'').replace(/ years?( old)?$/,'').trim();const parts=cleaned.split(' ');let n:number|undefined;if(parts.length===1)n=numberWords[parts[0]];else if(parts.length===2&&numberWords[parts[0]]>=20&&numberWords[parts[0]]%10===0&&numberWords[parts[1]]>0&&numberWords[parts[1]]<10)n=numberWords[parts[0]]+numberWords[parts[1]];else if(/^one hundred(?: (?:and )?(?:[a-z]+))?$/.test(cleaned)){const tail=parts.filter(x=>!['one','hundred','and'].includes(x));n=100+(tail.length?(numberWords[tail[0]]??999):0)}return n!==undefined&&n<=120?n:null;}
export function indiaToday(now=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(now)}
export function parseSpokenDate(raw:string,now=new Date()):string|null{const s=normal(raw);const today=indiaToday(now);const date=new Date(today+'T12:00:00Z');let result:string|null=null;if(s==='today')result=today;else if(s==='tomorrow'){date.setUTCDate(date.getUTCDate()+1);result=date.toISOString().slice(0,10)}else{const days=s.match(/^in (\d{1,3}|one|two|three|four|five|six|seven|eight|nine|ten) days?$/);if(days){date.setUTCDate(date.getUTCDate()+(numberWords[days[1]]??Number(days[1])));result=date.toISOString().slice(0,10)}else if(/^\d{4}-\d{2}-\d{2}$/.test(s))result=s;else {const months=['january','february','march','april','may','june','july','august','september','october','november','december'];const m=s.match(/^(\d{1,2})(?:st|nd|rd|th)? (\w+) (\d{4})$|^(\w+) (\d{1,2})(?:st|nd|rd|th)? (\d{4})$/);if(m){const month=months.indexOf(m[2]||m[4]);const day=Number(m[1]||m[5]);const year=m[3]||m[6];if(month>=0)result=`${year}-${String(month+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`}}}if(!result||result<today)return null;const check=new Date(result+'T12:00:00Z');return !isNaN(check.getTime())&&check.toISOString().slice(0,10)===result?result:null;}
export function spokenDate(s:string){return new Date(s+'T12:00:00Z').toLocaleDateString('en-IN',{day:'numeric',month:'long',year:'numeric',timeZone:'Asia/Kolkata'})}
export function startVoice(region:string):VoiceState{return {stage:'topic',region,step:0,prompt:'Hello, I am Saathi. Tell me what you need. You can say pension, ration card, land registration, doctor, jobs, or set a reminder. Do not say an Aadhaar number, bank details, PIN or OTP.'}}
function servicePrompt(s:VoiceState){const service=services.find(x=>x.id===s.serviceId);if(!service)return 'Please choose another service.';return `${service.title}. Step ${s.step+1} of ${service.steps.length}. ${service.steps[s.step]} Say next, repeat, back, or stop.`}
export function voiceTurn(state:VoiceState,raw:string,now=new Date()):VoiceResult {const text=normal(raw);const next=(patch:Partial<VoiceState>,effect?:VoiceResult['effect']):VoiceResult=>({state:{...state,paused:false,...patch},effect});if(!text)return next({prompt:'I did not hear an answer. Please tap the microphone and try again.'});if(/^(stop|pause|be quiet|stop listening)$/.test(text))return next({paused:true,resumePrompt:state.prompt,prompt:'Paused. The microphone is off. Tap Resume when you are ready.'},'pause');if(/^(cancel|start over|home|new question|another service)$/.test(text))return {state:startVoice(state.region)};if(/^(repeat|say again|again)$/.test(text))return {state:{...state,paused:false}};
if(matchTopic(raw)==='emergency')return next({stage:'emergency',link:'tel:112',prompt:'If you are in immediate danger in India, call 112 now. Tap Call 112 on this screen, or ask someone nearby to call. Saathi cannot dispatch emergency services.'},'offer_link');
if(state.stage==='topic'){const id=matchTopic(raw);if(!id)return next({prompt:'I am not sure which service you need. Say one topic, such as ration, passport, disability support, legal aid, stocks, or reminder.'});if(id==='reminder')return next({stage:'reminder_title',title:undefined,due:undefined,prompt:'What should I remind you about? Say a short task, without private identity or account numbers.'});const title=id==='pension'?'older-person pension support':services.find(x=>x.id===id)!.title;return next({stage:'confirm',serviceId:id,prompt:`I heard ${title}. Is that correct? Say yes or no.`})}
if(state.stage==='confirm'){if(no(text))return {state:startVoice(state.region)};if(yes(text))return next({stage:'region',prompt:`Which State or Union Territory is this for? Say its name, or say use current for ${state.region}.`});return next({prompt:'Please say yes to confirm the service, or no to choose again.'})}
if(state.stage==='region'){const r=text==='use current'||text==='current'?state.region:parseRegion(raw);if(!r||!regions.includes(r as any))return next({prompt:'I could not identify one Indian State or Union Territory. Please say its full name, for example Tamil Nadu or Maharashtra.'});if(state.serviceId==='pension')return next({region:r,stage:'age',prompt:`For ${r}, let us check the national pension criteria. How old is the person? Say their age, or say not sure.`});const service=services.find(x=>x.id===state.serviceId)!;const s={...state,region:r,stage:'steps' as const,step:0,link:service.source};const freshness=now>new Date('2026-10-28T23:59:59+05:30')?'This source is due for a fresh review. Confirm everything on the official service. ':'';return {state:{...s,prompt:freshness+`For ${r}. ${service.caution} `+servicePrompt(s)}}}
if(state.stage==='age'){if(/not sure|dont know|unknown/.test(text))return next({age:null,stage:'bpl',prompt:'Is the household officially listed as Below Poverty Line, or BPL? Say yes, no, or not sure.'});const n=parseAge(raw);if(n===null)return next({prompt:'Please say an age from zero to one hundred and twenty, for example sixty five. Or say not sure.'});return next({age:n,stage:'age_confirm',prompt:`I heard age ${n}. Is that correct? Say yes or no.`})}
if(state.stage==='age_confirm'){if(no(text))return next({stage:'age',prompt:'Please say the age again, or say not sure.'});if(yes(text))return next({stage:'bpl',prompt:'Is this household officially listed as Below Poverty Line, or BPL? Say yes, no, or not sure. Low income alone does not prove BPL status.'});return next({prompt:'Please say yes to confirm the age, or no to correct it.'})}
if(state.stage==='bpl'){const bpl=yes(text)?'yes':no(text)?'no':/not sure|dont know|unknown/.test(text)?'unknown':null;if(!bpl)return next({prompt:'For official BPL status, please say yes, no, or not sure.'});const result=evaluatePension({country:'IN',state:state.region,age:state.age??null,bpl},now);return next({stage:'pension_result',link:'https://www.myscheme.gov.in/schemes/nsap-ignoaps',prompt:`${result.title}. ${result.reason} Say next to hear the preparation steps, or say reminder to save a follow-up.`})}
if(state.stage==='pension_result'){if(text==='reminder')return next({stage:'reminder_date',title:'Check pension requirements with the Gram Panchayat',prompt:'When should I remind you to check pension requirements? Say tomorrow, in three days, or an exact date such as 5 October 2026.'});if(text==='next')return next({stage:'complete',prompt:'Ask the Gram Panchayat about the current pension application route and accepted documents. Keep the official acknowledgement. Tap Open official service to read the source. Say start over for another service.'},'offer_link')}
if(state.stage==='steps'){const service=services.find(x=>x.id===state.serviceId)!;if(text==='next'||text==='continue'){if(state.step+1>=service.steps.length)return next({stage:'complete',prompt:'You have heard all the preparation steps. Tap Open official service to continue there. That service may require its own forms, identity checks or a visit. Say reminder to save a follow-up, or start over for another service.'},'offer_link');const s={...state,step:state.step+1};return {state:{...s,prompt:servicePrompt(s)}}}if(text==='back'||text==='previous'){const s={...state,step:Math.max(0,state.step-1)};return {state:{...s,prompt:servicePrompt(s)}}}if(text==='reminder'||text==='set a reminder')return next({stage:'reminder_date',title:'Follow up: '+service.title,prompt:'When should I remind you? Say tomorrow, in three days, or an exact date such as 5 October 2026.'});if(text==='open'||text==='open service')return next({prompt:'Tap Open official service on this screen. The official portal may require its own forms or identity checks.'},'offer_link');return next({prompt:servicePrompt(state)})}
if(state.stage==='complete'&&text==='reminder')return next({stage:'reminder_date',title:'Follow up: '+(services.find(s=>s.id===state.serviceId)?.title??'pension support'),prompt:'When should I remind you? Say tomorrow or a date such as 5 October 2026.'});
if(state.stage==='reminder_title'){if(raw.trim().length>120||/\d{6,}/.test(raw.replace(/[ -]/g,'')))return next({prompt:'Please use a short task name without identity or account numbers.'});return next({stage:'reminder_date',title:raw.trim(),prompt:`The task is ${raw.trim()}. When should I remind you? Say tomorrow, in three days, or an exact date such as 5 October 2026.`})}
if(state.stage==='reminder_date'){const due=parseSpokenDate(raw,now);if(!due)return next({prompt:'I could not confirm that date. Say tomorrow, in three days, or a full date like 5 October 2026. Past dates are not accepted.'});return next({stage:'reminder_confirm',due,prompt:`Save the reminder ${state.title}, for ${spokenDate(due)}, India time? Say yes to save, or no to change the date. It will appear inside Saathi; it will not send a text message.`})}
if(state.stage==='reminder_confirm'){if(no(text))return next({stage:'reminder_date',due:undefined,prompt:'What date should I use instead?'});if(yes(text))return next({prompt:'Saving your reminder. Please wait.'},'save_reminder');return next({prompt:`Please say yes to save ${state.title} for ${spokenDate(state.due!)}, or no to change the date.`})}
return next({prompt:'Say start over to choose another service, or stop to pause.'});}
