"""Build a dated, traceable public service audit; never infer provider completion."""
import json,html
from pathlib import Path
root=Path(__file__).resolve().parents[1]
data=json.loads((root/'data/ruralos-service-audit.json').read_text())
items=data['services']
assert len(items)==42 and len({s['id'] for s in items})==42
assert all(s['transaction']=='pending' and s['ruralValidation']=='pending' for s in items)
esc=lambda x:html.escape(str(x),quote=True)
cards=[]
for s in items:
 assert s['id'].isalnum() and s['browser'] in ('passed','pending','failed')
 assert s['fieldValidation'] in ('passed','pending','failed')
 checks=''.join('<li><span class="'+('done' if state=='passed' else 'pending')+'">'+('✓ Checked' if state=='passed' else '○ Pending' if state=='pending' else '! Failed')+'</span> '+esc(label)+'</li>' for label,state in [('Public browser journey',s['browser']),('Automated workflow safeguards',s['fieldValidation']),('Live provider execution','pending'),('Rural-user outcome study','pending')])
 cards.append(f'''<article id="{esc(s['id'])}"><div class="cardtop"><span>{esc(s['category'])}</span><span class="partial">Partial service</span></div><h2>{esc(s['title'])}</h2><p>{esc(s['depth'])}</p><ul>{checks}</ul><details><summary>Scenario and remaining work</summary><p><strong>Scenarios reviewed:</strong> {esc('; '.join(s['goals']))}</p><p><strong>Browser example:</strong> {esc(s['browserScenario'])}</p><p><strong>Still needed:</strong> {esc(s['gap'])}</p><p>Passing the app journey means guidance was displayed. It does not establish eligibility, available inventory or completion with the provider.</p></details><a class="open" href="/ruralos/?service={esc(s['id'])}&amp;language=en">Open this service →</a></article>''')
css='''*{box-sizing:border-box}body{margin:0;background:#f5f7f4;color:#183c31;font:17px/1.6 system-ui,sans-serif}header,main,footer{max-width:1200px;margin:auto;padding:24px}a{color:#245844}header{display:flex;gap:24px;align-items:center}header strong{font-size:24px}h1{font-size:clamp(2rem,5vw,3.4rem);line-height:1.12;max-width:800px}h2{font-size:1.25rem;line-height:1.3}.intro{max-width:850px}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:28px 0}.stats div{border-radius:16px;background:#e7f0e8;padding:20px}.stats strong{display:block;font-size:2rem}.notice{padding:20px;background:#fff2d8;border-radius:14px}.cards{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px;margin-top:28px}article{background:white;border:1px solid #d5e0d8;border-radius:18px;padding:24px;scroll-margin-top:20px}.cardtop{display:flex;justify-content:space-between;gap:10px;font-size:.8rem;font-weight:700}.partial,.pending{color:#744716}.done{color:#205f41}ul{list-style:none;padding:0}li{border-bottom:1px solid #ecf0ed;padding:9px 0}li span{display:inline-block;min-width:100px;font-weight:650}.open{display:inline-block;margin-top:16px;font-weight:700;min-height:48px;padding:12px 0}summary{min-height:48px;padding:12px 0;cursor:pointer;font-weight:650}details p{font-size:.95rem}.jump{display:flex;gap:10px;flex-wrap:wrap;margin-top:22px}.jump a{background:white;border:1px solid #b8cbbd;border-radius:10px;padding:10px 14px;text-decoration:none}a:focus-visible,summary:focus-visible{outline:3px solid #ab651d;outline-offset:4px}@media(max-width:700px){.cards{grid-template-columns:1fr}.stats{grid-template-columns:1fr}header,main,footer{padding:18px}}'''
passed=sum(s['browser']=='passed' for s in items)
page=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Saathi · Every service checked</title><style>{css}</style></head><body><header><a href="/ruralos/"><strong>Saathi</strong> · Home</a><a href="/ruralos/?section=live">Tracking &amp; internet data</a></header><main><p>SERVICE AUDIT · {esc(data['reviewed'])}</p><h1>What works. What still needs work.</h1><p class="intro">An honest check of all 42 services. A tick applies to the named check only. Every service still has gaps; no provider booking, payment or application completion is verified.</p><div class="stats"><div><strong>{passed} / 42</strong>public browser journeys checked</div><div><strong>0 / 42</strong>integrated provider transactions</div><div><strong>Pending</strong>rural-household outcome validation</div></div><p class="notice">Live flight, train, ship and satellite tracking inside Saathi is pending. Available public feeds are airport weather observations and reported earthquakes. Neither is a flight tracker. Owner-only tracking access remains protected.</p><p class="intro">{esc(data['scope'])} This is a dated engineering review, not a real-time service guarantee. Hindi and Telugu remain review previews; this detailed audit is in English.</p><nav class="jump" aria-label="Find a service">{''.join(f'<a href="#{esc(s["id"])}">{esc(s["title"])}</a>' for s in items)}</nav><div class="cards">{''.join(cards)}</div></main><footer><a href="/ruralos/">Back to Saathi</a><p>We mark completion only when the responsible provider confirms it. Household data is not used to train or self-modify the app.</p></footer></body></html>'''
(root/'ruralos/integrations/index.html').write_text(page)
print(f'Built audited cards: {len(items)}; browser checks: {passed}; provider completions: 0')
